export type Check = { q: string; options: [string, string, string]; answer: number; explanation?: string; visual?: "ac-wave"|"dc-line"|"ac-dc-devices" };
export type CourseLevel = { id: string; title: string; objective: string; theory: string; practice: string; formula?: string };
export type Category = { id: string; name: string; role: string; color: string; levels: CourseLevel[]; checks: Check[] };

const makeLevels = (category: string, rows: Array<[string,string,string,string,string?]>): CourseLevel[] => rows.map((r,i)=>({id:`${category}-${i+1}`,title:r[0],objective:r[1],theory:r[2],practice:r[3],formula:r[4]}));

export const categories: Category[] = [
  { id:"aprendiz", name:"Aprendiz", role:"Fundamentos", color:"#1268f4", levels:makeLevels("aprendiz",[
    ["Grandezas elétricas","Distinguir tensão, corrente e resistência.","A tensão cria diferença de potencial; a corrente é movimento de carga; a resistência limita a corrente.","Identifica V, A e Ω num multímetro.","U = R × I"],
    ["Lei de Ohm","Relacionar tensão, corrente e resistência.","Num elemento resistivo, a corrente aumenta com a tensão e diminui com a resistência.","Calcula a corrente de uma carga de 46 Ω ligada a 230 V.","I = U ÷ R"],
    ["Potência e energia","Distinguir potência instantânea de energia consumida.","Potência mede a taxa de conversão de energia; o consumo resulta da potência multiplicada pelo tempo.","Compara uma carga de 1 kW durante 2 h com uma de 2 kW durante 1 h.","E = P × t"],
    ["Corrente alternada e contínua","Reconhecer CA e CC e as suas aplicações.","Na CA a polaridade varia periodicamente; na CC mantém-se definida.","Classifica rede doméstica, bateria e saída USB."],
    ["Circuito fechado","Compreender fonte, carga, condutores e comando.","A corrente necessita de um percurso fechado e de uma diferença de potencial.","Segue o caminho da corrente num circuito simples de lâmpada."],
    ["Série e paralelo","Prever o comportamento de associações básicas.","Em série a corrente é comum; em paralelo a tensão é comum aos ramos.","Decide por que razão as cargas de uma habitação são ligadas em paralelo."],
    ["Fase, neutro e proteção","Distinguir condutores pela função, não apenas pela cor.","A fase está ativa, o neutro é o condutor de retorno do sistema e o PE conduz correntes de defeito.","Identifica L, N e PE num esquema monofásico."],
    ["Frequência e valor eficaz","Interpretar 230 V e 50 Hz.","O valor eficaz permite comparar o efeito térmico da CA; a frequência indica ciclos por segundo.","Lê os dados nominais de um equipamento para a rede portuguesa.","f = 1 ÷ T"],
    ["Símbolos elétricos","Ler um esquema elementar.","Os símbolos representam funções elétricas e não a aparência física dos componentes.","Localiza proteção, comando, carga e condutores num esquema."],
    ["Projeto de fundamentos","Aplicar as grandezas num circuito completo.","O dimensionamento começa pelos dados da carga e pelas condições do circuito.","Resolve um caso com tensão, potência, corrente e escolha da proteção."],
  ]), checks:[
    {q:"Qual é a unidade da corrente elétrica?",options:["Ampere","Volt","Ohm"],answer:0},{q:"O que representa a tensão?",options:["Diferença de potencial","Tempo de utilização","Comprimento do cabo"],answer:0},{q:"Num circuito em paralelo, o que é comum aos ramos?",options:["A tensão","A corrente total em cada ramo","A resistência"],answer:0},{q:"Que expressão corresponde à Lei de Ohm?",options:["U = R × I","P = t ÷ E","I = P × t"],answer:0},{q:"Qual é a unidade da potência?",options:["Watt","Ampere-hora","Ohm"],answer:0},{q:"O que significa 50 Hz?",options:["50 ciclos por segundo","50 volts por segundo","50 watts por hora"],answer:0},{q:"Qual é a função principal do PE?",options:["Conduzir corrente de defeito para proteção","Alimentar a carga normalmente","Controlar a potência"],answer:0},{q:"O consumo elétrico resulta de quê?",options:["Potência e tempo","Tensão apenas","Resistência apenas"],answer:0},{q:"Um circuito aberto permite corrente contínua no percurso?",options:["Não","Sim, sempre","Só em paralelo"],answer:0}
  ]},
  { id:"ajudante", name:"Ajudante", role:"Materiais e ferramentas", color:"#00a67e", levels:makeLevels("ajudante",[
    ["Ferramentas isoladas","Selecionar ferramentas adequadas ao trabalho elétrico.","Isolamento, categoria e estado da ferramenta devem corresponder ao risco e ao método de trabalho.","Inspeciona punhos, lâminas e marcações antes da utilização."],
    ["Multímetro","Conhecer bornes, escalas e categorias de medição.","Uma ligação errada do cabo de prova ou da função pode criar curto-circuito ou danificar o instrumento.","Configura o aparelho para medir tensão alternada."],
    ["Detetor de tensão","Distinguir indicação preliminar de verificação de ausência de tensão.","Um detetor sem contacto ajuda a localizar tensão, mas não substitui um procedimento completo de verificação.","Compara detetor sem contacto e instrumento de dois polos."],
    ["Condutores e cabos","Distinguir alma, isolamento e bainha.","A constituição do cabo depende do ambiente, esforço mecânico e modo de instalação.","Compara condutor rígido, flexível e cabo multicondutor."],
    ["Secção do condutor","Compreender os fatores de seleção da secção.","Corrente admissível, queda de tensão, curto-circuito, temperatura e instalação influenciam a escolha.","Explica por que a secção não é escolhida apenas pela potência."],
    ["Terminais e conectores","Realizar ligações mecanicamente estáveis.","O conector deve ser compatível com material, secção e tipo de condutor.","Escolhe entre borne, ponteira e terminal de olhal."],
    ["Tubos, calhas e caixas","Planear encaminhamento e acessibilidade.","A canalização protege os condutores e deve permitir instalação e manutenção adequadas.","Seleciona o encaminhamento para uma divisão técnica."],
    ["Grau IP","Interpretar proteção contra sólidos e água.","Os dois algarismos do código IP descrevem níveis distintos de proteção do invólucro.","Compara necessidades de uma sala seca e de um local húmido."],
    ["Etiquetagem","Identificar circuitos, cabos e dispositivos.","Uma identificação coerente reduz erros de operação, ensaio e manutenção.","Cria etiquetas para origem, destino, circuito e proteção."],
    ["Bancada de montagem","Preparar e verificar uma montagem técnica.","Organização, inspeção e sequência de ensaio fazem parte da qualidade da execução.","Monta uma caixa de treino e confirma continuidade."],
  ]), checks:[
    {q:"Antes de usar uma ferramenta isolada, o que se verifica?",options:["Estado e marcações","A cor apenas","O peso apenas"],answer:0},{q:"Para medir tensão, onde devem estar os cabos do multímetro?",options:["Nos bornes indicados para tensão e comum","Ambos no borne de corrente","Em qualquer borne"],answer:0},{q:"Um detetor sem contacto substitui sempre a verificação de ausência de tensão?",options:["Não","Sim","Só em cabos flexíveis"],answer:0},{q:"A secção de um condutor depende apenas da potência?",options:["Não","Sim","Só em CC"],answer:0},{q:"Uma ponteira é especialmente útil em quê?",options:["Condutores flexíveis em bornes adequados","Tubos rígidos","Medição de frequência"],answer:0},{q:"O primeiro algarismo de IP refere-se principalmente a quê?",options:["Entrada de sólidos e acesso","Tensão nominal","Cor do invólucro"],answer:0},{q:"Por que se etiquetam circuitos?",options:["Para reduzir erros e facilitar manutenção","Para aumentar a corrente","Para substituir ensaios"],answer:0},{q:"O conector deve ser escolhido segundo quê?",options:["Tipo, material e secção do condutor","Forma da caixa apenas","Marca da ferramenta"],answer:0},{q:"O que protege mecanicamente os condutores num percurso?",options:["Canalização adequada","O diferencial","O contador"],answer:0}
  ]},
  { id:"instalador", name:"Instalador", role:"Circuitos e montagem", color:"#7c4dff", levels:makeLevels("instalador",[
    ["Planta elétrica","Passar da planta arquitetónica ao traçado elétrico.","A planta localiza utilizações, comandos, percursos e quadros.","Marca pontos de luz, tomadas e circuitos numa divisão."],
    ["Circuito de iluminação","Compreender alimentação, comando e retorno.","O dispositivo de comando deve atuar no condutor ativo do circuito.","Segue L, retorno, N e PE num ponto de luz."],
    ["Interruptor simples","Ligar um ponto de comando a uma carga.","O interruptor abre ou fecha o percurso da fase para a carga.","Interpreta os bornes e desenha o esquema funcional."],
    ["Comutação de escada","Comandar uma luz a partir de dois locais.","Dois comutadores desviam o percurso entre condutores de ligação.","Segue os estados possíveis dos dois comutadores."],
    ["Tomadas","Compreender ligações e continuidade do PE.","A polaridade, aperto, proteção e continuidade do condutor de proteção são essenciais.","Inspeciona uma ligação de tomada num painel didático."],
    ["Caixas de derivação","Organizar ligações sem perder rastreabilidade.","As ligações devem ficar acessíveis, protegidas e feitas com conectores adequados.","Agrupa fase, neutro, retornos e PE corretamente."],
    ["Circuitos dedicados","Reconhecer cargas que exigem circuito próprio.","Potência, simultaneidade, ambiente e regras aplicáveis determinam a separação.","Analisa forno, termoacumulador e máquina de lavar."],
    ["Queda de tensão","Relacionar comprimento, corrente e secção.","A queda aumenta com corrente e comprimento e diminui com maior secção.","Compara duas alimentações da mesma carga com comprimentos diferentes."],
    ["Continuidade e isolamento","Preparar ensaios antes da energização.","Os ensaios verificam condutores de proteção, isolamento e ausência de ligações indevidas.","Ordena inspeção visual, ensaios e energização."],
    ["Projeto de instalação","Executar um pequeno circuito a partir do esquema.","Uma instalação correta liga projeto, materiais, montagem, identificação e ensaios.","Planeia uma divisão com iluminação e tomadas."],
  ]), checks:[
    {q:"Num circuito de iluminação, qual condutor deve ser comandado?",options:["O condutor ativo","O PE","A bainha"],answer:0},{q:"Para que serve o retorno?",options:["Levar a fase comandada à carga","Substituir o PE","Medir resistência"],answer:0},{q:"A comutação de escada permite quê?",options:["Comandar uma luz de dois locais","Duplicar a tensão","Eliminar o neutro"],answer:0},{q:"As ligações numa caixa de derivação devem ficar como?",options:["Acessíveis e protegidas","Escondidas sem caixa","Soltas"],answer:0},{q:"O que aumenta normalmente a queda de tensão?",options:["Maior comprimento e corrente","Maior secção","Menor carga"],answer:0},{q:"Quando se realizam ensaios iniciais?",options:["Antes da colocação em serviço","Só após uma avaria","Nunca"],answer:0},{q:"O PE deve manter continuidade até onde?",options:["Massas e pontos previstos","Apenas ao quadro","Ao interruptor apenas"],answer:0},{q:"Um circuito dedicado é considerado sobretudo por quê?",options:["Características da carga e regras aplicáveis","Cor da ficha","Altura do teto"],answer:0},{q:"O que representa uma planta elétrica?",options:["Localização e organização da instalação","A fatura mensal","A marca das ferramentas"],answer:0}
  ]},
  { id:"tecnico", name:"Técnico", role:"Proteções e quadros", color:"#ec7a14", levels:makeLevels("tecnico",[
    ["Sobrecarga e curto-circuito","Distinguir os dois tipos de sobreintensidade.","A sobrecarga surge num circuito saudável excessivamente carregado; o curto-circuito resulta de uma ligação de impedância muito baixa.","Classifica três cenários de corrente excessiva."],
    ["Disjuntores","Interpretar corrente nominal e curva de disparo.","O disjuntor protege canalizações contra sobreintensidades quando coordenado com o circuito.","Relaciona carga, condutor e calibre da proteção."],
    ["Diferenciais","Compreender corrente residual e sensibilidade.","O diferencial compara correntes nos condutores ativos e atua quando existe desequilíbrio acima do limiar.","Interpreta IΔn e o botão de teste."],
    ["Ligação à terra","Compreender elétrodos, PE e equipotencialidade.","A proteção depende de um caminho de defeito e da atuação coordenada dos dispositivos.","Segue uma corrente de defeito desde uma massa até à origem."],
    ["Sobretensões","Distinguir sobretensão transitória e permanente.","A origem e duração da sobretensão determinam o dispositivo e a coordenação necessários.","Classifica descarga atmosférica indireta e perda de neutro."],
    ["Seletividade","Coordenar proteções em série.","A seletividade procura limitar o corte ao setor afetado, mantendo o restante serviço.","Compara curvas e níveis de proteção a montante e jusante."],
    ["Poder de corte","Relacionar proteção com corrente de curto-circuito presumida.","O dispositivo deve conseguir interromper a corrente de defeito esperada no ponto de instalação.","Verifica se a marcação é adequada ao local."],
    ["Organização do quadro","Separar, identificar e distribuir circuitos.","Um quadro legível facilita operação, ensaio, ampliação e manutenção.","Organiza corte geral, proteção e circuitos finais."],
    ["Equilíbrio trifásico","Distribuir cargas entre fases.","Uma distribuição equilibrada reduz assimetrias e utilização excessiva de uma fase.","Distribui cargas monofásicas por L1, L2 e L3."],
    ["Projeto de quadro","Selecionar e coordenar aparelhagem.","O projeto junta esquema, características da alimentação, cargas, canalizações, proteções e ensaios.","Constrói um diagrama unifilar de um pequeno quadro."],
  ]), checks:[
    {q:"O que caracteriza um curto-circuito?",options:["Ligação de impedância muito baixa","Consumo normal prolongado","Ausência de carga"],answer:0},{q:"O disjuntor protege principalmente contra quê?",options:["Sobreintensidades","Humidade ambiente","Erros de etiquetagem"],answer:0},{q:"O diferencial deteta quê?",options:["Desequilíbrio de corrente residual","Potência contratada","Cor dos condutores"],answer:0},{q:"O que significa IΔn?",options:["Corrente diferencial nominal de atuação","Potência do quadro","Resistência do cabo"],answer:0},{q:"Para que serve a seletividade?",options:["Limitar o corte à parte afetada","Aumentar a tensão","Eliminar ensaios"],answer:0},{q:"O poder de corte deve ser adequado a quê?",options:["Corrente de curto-circuito presumida","Comprimento da etiqueta","Número de tomadas apenas"],answer:0},{q:"Uma sobretensão transitória é normalmente como?",options:["Curta e de elevada variação","Uma sobrecarga contínua","Uma falha mecânica"],answer:0},{q:"Por que se equilibram cargas trifásicas?",options:["Para reduzir assimetrias entre fases","Para eliminar o PE","Para duplicar a frequência"],answer:0},{q:"O diagrama unifilar mostra o quê?",options:["Estrutura elétrica simplificada","Fotografia do quadro","Consumo diário"],answer:0}
  ]},
  { id:"especialista", name:"Especialista", role:"Medição e diagnóstico", color:"#d02f63", levels:makeLevels("especialista",[
    ["Método de diagnóstico","Investigar por evidência e sequência.","Confirmar o sintoma, delimitar o circuito, medir e validar evita substituições por tentativa.","Cria uma árvore de diagnóstico para uma carga inoperacional."],
    ["Medição de tensão","Medir diferença de potencial com ligação em paralelo.","A função, bornes, categoria e alcance devem ser adequados antes de tocar nos pontos de teste.","Planeia uma medição num painel didático."],
    ["Continuidade","Verificar um percurso com o circuito desenergizado.","A continuidade não deve ser medida num circuito energizado.","Localiza uma interrupção num condutor de treino."],
    ["Resistência de isolamento","Avaliar o isolamento entre condutores.","O ensaio usa tensão própria e exige cargas sensíveis desligadas quando aplicável.","Interpreta resultados comparativos de um circuito."],
    ["Corrente de carga","Selecionar método em série ou pinça.","A medição deve respeitar o instrumento, o circuito e a corrente esperada.","Escolhe entre multímetro e pinça amperimétrica."],
    ["Polaridade","Confirmar a correta ligação dos condutores ativos.","A polaridade assegura que comandos e proteções unipolares atuam no condutor previsto.","Segue a fase até ao dispositivo de comando."],
    ["Disparo de diferencial","Localizar fugas sem anular a proteção.","A divisão por circuitos e a medição permitem isolar a origem do defeito.","Ordena os passos para localizar o circuito afetado."],
    ["Queda de tensão anormal","Relacionar sintomas com ligações resistivas.","Uma ligação deficiente pode provocar queda, aquecimento e funcionamento instável.","Compara tensão sem carga e sob carga."],
    ["Relatório técnico","Registar condições, método, valores e conclusão.","Um diagnóstico reproduzível separa observações, medições, limites e ações.","Preenche um relatório de ensaio didático."],
    ["Caso final integrado","Diagnosticar sem saltar etapas.","Segurança, esquema, inspeção, medição e confirmação formam um único processo.","Resolve uma avaria simulada do sintoma à validação."],
  ]), checks:[
    {q:"Qual é o primeiro passo de um diagnóstico organizado?",options:["Confirmar o sintoma","Substituir peças","Aumentar o disjuntor"],answer:0},{q:"A tensão mede-se normalmente de que forma?",options:["Em paralelo","Em série com a carga","Com o circuito sempre desligado"],answer:0},{q:"A continuidade deve ser medida num circuito energizado?",options:["Não","Sim","Só a 230 V"],answer:0},{q:"Para medir corrente sem abrir o circuito pode usar-se o quê?",options:["Pinça amperimétrica adequada","Ohmímetro","Detetor de madeira"],answer:0},{q:"Uma queda de tensão que surge sob carga pode indicar quê?",options:["Ligação resistiva deficiente","Frequência perfeita","Etiqueta errada apenas"],answer:0},{q:"Como se investiga um disparo diferencial?",options:["Isolando circuitos e medindo sem anular a proteção","Bloqueando o diferencial","Trocando por calibre maior"],answer:0},{q:"Para que se confirma a polaridade?",options:["Para garantir atuação no condutor previsto","Para medir energia","Para escolher a caixa"],answer:0},{q:"Um relatório técnico deve distinguir quê?",options:["Observações, medições e conclusões","Cores favoritas","Apenas o resultado final"],answer:0},{q:"Depois de uma reparação, o que falta?",options:["Ensaiar e confirmar o resultado","Apenas fechar a caixa","Apagar o registo"],answer:0}
  ]},
];

export const allLevels = categories.flatMap((category)=>category.levels.map((level)=>({...level,category})));
