"use client";

import { useEffect, useMemo, useState } from "react";
import { Award, BookOpen, Check, ChevronRight, Flame, Gauge, Home, LockKeyhole, ShieldCheck, Sparkles, Star, Trophy, UserRound, X, Zap } from "lucide-react";
import { Progress } from "@/components/ui/progress";
import { allLevels, categories, type Check, type CourseLevel } from "./curriculum";

type View="percurso"|"manual"|"aula"|"desafio"|"perfil";
type User={id:string;name:string;email:string;avatar?:string};
type Data={xp:number;level:number;streak:number;completedLessons:string[]};
const initial:Data={xp:0,level:1,streak:0,completedLessons:[]};
const legacyStorageKey="voltz-progress-v1";
const asset=(name:string)=>`${import.meta.env.BASE_URL}${name}`;
const lowerFirst=(text:string)=>text.charAt(0).toLocaleLowerCase("pt-PT")+text.slice(1);
const shuffle=<T,>(items:T[])=>{const out=[...items];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out};
const shuffleCheck=(item:Check)=>{const correct=item.options[item.answer];const options=shuffle([...item.options]) as [string,string,string];return {...item,options,answer:options.indexOf(correct)}};
const xpForScore=(score:number)=>score===10?250:score===9?225:score===8?200:0;
const photos:Record<string,{src:string;alt:string;caption:string;credit:string;href:string}>={
  "aprendiz-1":{src:"https://www.foxvalleymetrology.com/wp-content/uploads/2025/08/img_3451-min-scaled.jpg",alt:"Multímetro digital com pontas de prova ligadas aos bornes corretos",caption:"V, A e Ω aparecem no seletor e nos bornes de um multímetro real",credit:"Fox Valley Metrology",href:"https://www.foxvalleymetrology.com/blog/how-to-use-a-multimeter/"},
  "aprendiz-2":{src:"https://bkpmedia.s3.us-west-1.amazonaws.com/downloads/kb_attachments/Ohms_Law.jpg",alt:"Circuito com fonte, resistência e corrente usado para explicar a Lei de Ohm",caption:"U, R e I representadas no mesmo circuito",credit:"B&K Precision",href:"https://www.bkprecision.com/knowledge/technical-notes/163/understanding-constant-voltage-cv-and-constant-current-cc-modes-in-regulated-power-supplies"},
  "ajudante-4":{src:"https://sawdustgirl.com/wp-content/uploads/2013/09/examine-extension-cords.jpg",alt:"Cabo elétrico com isolamento danificado",caption:"Inspeção real do isolamento de um cabo",credit:"Sawdust Girl",href:"https://sawdustgirl.com/extension-cord-safety/"},
  "tecnico-3":{src:"https://ozdenosgb.com/storage/blogs/kacak_akim.jpg",alt:"Interruptor diferencial num quadro elétrico",caption:"Identificação visual de um interruptor diferencial",credit:"Özden OSGB",href:"https://ozdenosgb.com/blog/kacak-akim-rolesi"},
  "ajudante-8":{src:"https://media.adeo.com/media/4758182/media.jpeg",alt:"Tomada elétrica exposta a humidade",caption:"O invólucro deve corresponder às influências externas",credit:"Leroy Merlin",href:"https://www.leroymerlin.pl/porady/instalacje/instalacja-elektryczna/zalana-instalacja-elektryczna-co-robic.html"},
};
const manualChapters=[
  {title:"O mapa da eletricidade",tag:"Começa aqui",text:"Antes das fórmulas, fixa quatro ideias: uma fonte cria tensão, um percurso fechado permite corrente, a carga transforma energia e a proteção limita as consequências de um defeito.",detail:"Imagina a tensão como a diferença que empurra as cargas, a corrente como a quantidade que atravessa o circuito e a resistência como a oposição encontrada. A analogia ajuda a começar, mas a eletricidade não é água: usa-a apenas para perceber a relação entre as grandezas.",points:["Tensão: diferença de potencial, medida em volt (V)","Corrente: movimento de carga, medido em ampere (A)","Resistência: oposição à corrente, medida em ohm (Ω)"],visual:"basics"},
  {title:"Fase, neutro e proteção",tag:"Condutores",text:"Numa alimentação monofásica, L é o condutor ativo, N pertence ao circuito funcional de retorno e PE é o condutor de proteção. PE não deve transportar corrente durante o funcionamento normal.",detail:"As cores ajudam a identificar, mas nunca são uma prova suficiente: instalações antigas, alterações ou erros podem não respeitar a convenção. A função deve ser confirmada pelo esquema, inspeção e procedimentos de verificação adequados. Em Portugal e na harmonização europeia, é comum encontrar castanho na fase, azul no neutro e verde/amarelo na proteção.",points:["L — fase: condutor ativo","N — neutro: condutor do circuito funcional","PE — proteção: caminho previsto para correntes de defeito"],visual:"conductors"},
  {title:"Como nasce um circuito",tag:"Percurso fechado",text:"Fonte, proteção, comando, carga e condutores formam uma cadeia funcional. Um interruptor aberto interrompe o percurso; quando fecha, a corrente pode circular e a carga transforma energia.",detail:"Exemplo: num ponto de luz, a proteção alimenta o circuito, o interruptor comanda o condutor ativo e a lâmpada é a carga. O neutro completa o circuito funcional e o PE protege as massas metálicas quando aplicável. Um circuito final é simplesmente o circuito que alimenta diretamente tomadas, iluminação ou outro equipamento de utilização.",points:["Proteção limita consequências de sobreintensidades","Comando abre ou fecha a alimentação da carga","Carga transforma energia elétrica em luz, calor ou movimento"],visual:"circuit"},
  {title:"Série e paralelo",tag:"Comparação visual",text:"Em série existe um único percurso e a mesma corrente atravessa os elementos. Em paralelo existem vários ramos e a tensão aplicada é comum a cada ramo.",detail:"Nas habitações, as cargas são normalmente ligadas em paralelo para receberem a tensão prevista e poderem funcionar de forma independente. Se uma lâmpada de um ramo for desligada, as outras podem continuar ligadas. Em série, abrir um ponto interrompe o único percurso.",points:["Série: um percurso e corrente comum","Paralelo: vários ramos e tensão comum","Cargas domésticas funcionam sobretudo em paralelo"],visual:"parallel"},
  {title:"Lei de Ohm sem medo",tag:"Cálculo",text:"A relação U = R × I descreve o comportamento de um elemento resistivo. Conhecendo duas grandezas, podes calcular a terceira, desde que uses unidades compatíveis.",detail:"Exemplo resolvido: uma resistência de 46 Ω ligada a 230 V conduz, no modelo simples, I = U ÷ R = 230 ÷ 46 = 5 A. Primeiro escreve os dados, depois escolhe a forma da fórmula, substitui os valores e confirma a unidade. O resultado é um cálculo didático; não autoriza escolher cabos ou proteções sem analisar as restantes condições.",points:["U em volt (V)","I em ampere (A)","R em ohm (Ω)"],visual:"ohm"},
  {title:"Potência e consumo",tag:"Energia",text:"Potência indica a rapidez com que a energia é transformada. Energia consumida depende da potência e do tempo de funcionamento.",detail:"Um equipamento de 1 kW ligado durante 2 horas utiliza 2 kWh. Um equipamento de 2 kW durante 1 hora também utiliza 2 kWh. kW indica potência; kWh indica energia acumulada. Em situações simples, P = U × I ajuda a relacionar potência, tensão e corrente, mas equipamentos reais podem exigir informação adicional.",points:["Potência: watt (W) ou quilowatt (kW)","Energia: quilowatt-hora (kWh)","Energia = potência × tempo"],visual:"power"},
  {title:"Proteções não são todas iguais",tag:"Quadro elétrico",text:"O disjuntor atua contra sobreintensidades; o diferencial deteta um desequilíbrio entre correntes nos condutores ativos. O PE e a ligação à terra integram o sistema de proteção.",detail:"Sobrecarga é corrente excessiva num circuito sem ligação direta de baixa impedância; curto-circuito é uma ligação de impedância muito baixa. Corrente residual é a diferença que indica que parte da corrente seguiu um caminho não previsto. Coordenação significa que condutores, terra e dispositivos devem funcionar em conjunto para desligar nas condições previstas.",points:["Disjuntor: sobrecarga e curto-circuito","Diferencial: desequilíbrio ou corrente residual","PE: caminho de proteção, não substitui o diferencial"],visual:"protection"},
  {title:"Como estudar no Voltz",tag:"Preparação final",text:"Lê o princípio, observa a imagem ou o esquema, explica por palavras tuas e resolve o exemplo antes de responder. Voltar atrás faz parte da aprendizagem.",detail:"Cada desafio tem 10 perguntas. A primeira resposta a cada pergunta conta para a nota e são necessárias 8 respostas certas para desbloquear o nível seguinte. Depois de um erro, recebes a resposta correta e uma explicação; podes repetir com as opções noutra posição, mas o erro continua registado. Os níveis ensinam conceitos e não autorizam trabalhos regulamentados.",points:["10 perguntas por nível, sobre a aula anterior","8 certas à primeira tentativa para avançar","Manual sempre disponível para consulta"],visual:"ready"},
];
const manualImages:Record<string,{src:string;alt:string;caption:string;href:string;credit:string}>={
  basics:{src:"https://cdn.tmi.yokogawa.com/1/9275/details/High%20Current%20Measurement_Components%20of%20Electrical%20Circuit_Yokogawa%20Test%20Measurement.png",alt:"Diagrama de tensão, corrente e resistência num circuito com lâmpada",caption:"Tensão, corrente e resistência no mesmo circuito",href:"https://tmi.yokogawa.com/us/library/resources/application-notes/high-current-measurement-application-note/",credit:"Yokogawa Test & Measurement"},
  circuit:{src:"https://miro.medium.com/v2/resize%3Afit%3A1092/1%2A294y_rkSNKBHIEUi3E110g.jpeg",alt:"Circuito simples com fonte, interruptor e lâmpada",caption:"Um percurso fechado entre fonte, comando e carga",href:"https://tasweeb.medium.com/electric-circuit-89338190e57b",credit:"Tasweeb Fatima"},
  parallel:{src:"https://www.benzoenergy.com/pub/media/blog/lithium_cells.jpg",alt:"Comparação real entre lâmpadas ligadas em série e em paralelo",caption:"Observa a diferença física entre os dois percursos",href:"https://www.benzoenergy.com/blog/post/how-to-connect-lithium-batteries-in-series-and-parallel.html",credit:"Benzo Energy"},
  ohm:{src:"https://www.electricalsafetyfirst.org.uk/media/1773/ohms-law.jpg",alt:"Diagrama circular com as fórmulas da Lei de Ohm",caption:"As três formas principais da Lei de Ohm",href:"https://www.electricalsafetyfirst.org.uk/ohms-law-calculator/",credit:"Electrical Safety First"},
  power:{src:"https://mr2.homeflow-assets.co.uk/files/site_asset/image/6498/8745/_x_/1st_image_accurate_meter_readings_Kilowatt_hour_single_stator_power_company_meter_Watthour_meter_of_electricity_for_use_in_home_appliance.png",alt:"Contador de energia elétrica com leitura em quilowatt-hora",caption:"O contador regista energia consumida em kWh",href:"https://www.lighthouse-property.co.uk/blog/market-update/how-to-take-accurate-meter-readings",credit:"Lighthouse Property"},
  protection:{src:"https://cenerg.ru/wp-content/uploads/2019/06/uzo-i-diff-avtomat2324354.jpg",alt:"Quadro elétrico com disjuntores e diferenciais identificados",caption:"Proteções instaladas e organizadas num quadro real",href:"https://cenerg.ru/articles/uzo-i-diff-avtomat-v-chem-raznica/",credit:"CentroEnergoEkspertiza"},
};
const categoryPhotos:Record<string,{src:string;alt:string;caption:string;credit:string;href:string}>={
  aprendiz:photos["aprendiz-1"],
  ajudante:photos["ajudante-4"],
  instalador:manualImages.circuit,
  tecnico:manualImages.protection,
  especialista:photos["aprendiz-1"],
};
type Teaching={terms:string;worked:string;labels:[string,string,string]};
const teaching:Record<string,Teaching>={
  "aprendiz-1":{terms:"Tensão (V): diferença de potencial. Corrente (A): movimento de carga. Resistência (Ω): oposição à corrente.",worked:"Num circuito de 12 V e 6 Ω, identifica primeiro U e R. Aplica I = U ÷ R. O resultado é 2 A.",labels:["12 V","6 Ω","2 A"]},
  "aprendiz-2":{terms:"U é tensão em volt, R é resistência em ohm e I é corrente em ampere.",worked:"Dados: U = 230 V e R = 46 Ω. Fórmula: I = U ÷ R. Cálculo: 230 ÷ 46 = 5 A.",labels:["230 V","46 Ω","5 A"]},
  "aprendiz-3":{terms:"Potência (kW) é a rapidez de transformação. Energia (kWh) acumula potência ao longo do tempo.",worked:"1 kW durante 2 h: E = 1 × 2 = 2 kWh. 2 kW durante 1 h: E = 2 × 1 = 2 kWh. Os consumos são iguais.",labels:["1 kW","2 h","2 kWh"]},
  "aprendiz-4":{terms:"CA muda de sentido periodicamente. CC mantém polaridade definida. Frequência indica ciclos por segundo.",worked:"Rede doméstica portuguesa: CA, 230 V e 50 Hz. Bateria e saída USB: CC. Procura os símbolos ~ para CA e ⎓ para CC.",labels:["CA ~","50 Hz","CC ⎓"]},
  "aprendiz-5":{terms:"Fonte fornece energia, proteção limita consequências de defeitos, comando abre ou fecha, carga transforma energia e condutores formam o percurso.",worked:"Segue a cadeia completa: fonte → proteção → interruptor → lâmpada → retorno. Interruptor aberto interrompe o caminho; fechado permite corrente.",labels:["Fonte","Proteção","Comando + carga"]},
  "aprendiz-6":{terms:"Série tem um percurso e corrente comum. Paralelo tem ramos e tensão comum.",worked:"Duas lâmpadas domésticas devem funcionar de forma independente. Ligadas em paralelo, desligar uma não abre o ramo da outra.",labels:["Série","Ramos","Paralelo"]},
  "aprendiz-7":{terms:"L é fase ativa, N é neutro funcional e PE é proteção. A cor ajuda, mas não prova a função.",worked:"Num esquema monofásico, segue L até à carga, N no retorno e PE até às massas. Confirma sempre pelo esquema e verificação adequada.",labels:["L","N","PE"]},
  "aprendiz-8":{terms:"Frequência f mede ciclos por segundo. Período T é o tempo de um ciclo. Valor eficaz relaciona o efeito térmico da CA.",worked:"Para 50 Hz, T = 1 ÷ 50 = 0,02 s. Cada ciclo demora 20 ms. A indicação 230 V refere-se ao valor eficaz nominal.",labels:["50 Hz","20 ms","230 V"]},
  "aprendiz-9":{terms:"Símbolo representa função; ligação mostra relação; referência identifica o componente.",worked:"Começa na alimentação, segue a proteção e o comando, e termina na carga. Não confundas o desenho físico com o símbolo elétrico.",labels:["Proteção","Comando","Carga"]},
  "aprendiz-10":{terms:"Dados da carga, corrente prevista e condições de instalação orientam o projeto.",worked:"Regista tensão e potência, calcula a corrente, identifica o circuito e só depois considera condutor, proteção e queda de tensão.",labels:["Carga","Corrente","Proteção"]},
  "ajudante-1":{terms:"Isolamento reduz contacto; categoria indica utilização; inspeção confirma o estado.",worked:"Antes de usar, procura cortes, desgaste e marcações. Uma ferramenta danificada é retirada de serviço, não reparada de forma improvisada.",labels:["Isolamento","Marcação","Inspeção"]},
  "ajudante-2":{terms:"COM é o borne comum; VΩ serve medições próprias; A/mA são bornes de corrente.",worked:"Para tensão CA: preto em COM, vermelho em V, seletor em V~ e alcance adequado. Nunca deixes o cabo no borne A por engano.",labels:["COM","V~","Categoria"]},
  "ajudante-3":{terms:"Deteção preliminar localiza tensão; ausência de tensão exige método e instrumento adequados.",worked:"Testa o instrumento numa fonte conhecida, verifica os pontos previstos e volta a confirmar o instrumento. Um detetor sem contacto não basta.",labels:["Testar","Verificar","Retestar"]},
  "ajudante-4":{terms:"Alma conduz, isolamento separa eletricamente e bainha protege o conjunto.",worked:"Compara rigidez, número de condutores e ambiente. Escolhe o cabo pela aplicação e instalação, não apenas pela aparência.",labels:["Alma","Isolamento","Bainha"]},
  "ajudante-5":{terms:"Corrente admissível, queda de tensão e esforço térmico limitam a secção.",worked:"Duas cargas iguais podem exigir secções diferentes se comprimento, temperatura ou modo de instalação mudarem. Verifica todos os fatores.",labels:["Corrente","Comprimento","Secção"]},
  "ajudante-6":{terms:"Borne aperta, ponteira prepara multifilar e olhal cria ligação aparafusada.",worked:"Identifica material, secção e tipo do condutor. Escolhe o terminal compatível e confirma mecanicamente a ligação.",labels:["Condutor","Terminal","Aperto"]},
  "ajudante-7":{terms:"Tubo e calha protegem percursos; caixa aloja ligações e mantém acesso.",worked:"Traça o percurso, evita esmagamento e curvas inadequadas, e coloca caixas onde possam ser inspecionadas.",labels:["Percurso","Proteção","Acesso"]},
  "ajudante-8":{terms:"Primeiro algarismo IP: sólidos/acesso. Segundo: água. Maior número significa ensaio mais exigente, não proteção universal.",worked:"Compara uma sala seca com um local húmido. Identifica a influência externa antes de escolher o invólucro.",labels:["Sólidos","IP","Água"]},
  "ajudante-9":{terms:"Origem, destino, circuito e proteção tornam a identificação rastreável.",worked:"Cria uma etiqueta consistente nas duas extremidades e no quadro. Confirma que corresponde ao esquema atualizado.",labels:["Origem","Circuito","Destino"]},
  "ajudante-10":{terms:"Organização evita erros; inspeção encontra defeitos; ensaio confirma o resultado.",worked:"Prepara materiais, monta desenergizado, inspeciona apertos e só depois executa os ensaios previstos.",labels:["Preparar","Montar","Ensaiar"]},
  "instalador-1":{terms:"Planta localiza utilizações, traçado representa percursos e legenda explica símbolos.",worked:"Marca iluminação, comandos e tomadas. Agrupa utilizações por circuito e liga cada símbolo à legenda.",labels:["Planta","Circuitos","Legenda"]},
  "instalador-2":{terms:"Fase alimenta, retorno é fase comandada, neutro completa o circuito funcional.",worked:"Segue L da proteção ao interruptor, o retorno até à lâmpada e N de volta. PE acompanha a proteção das massas.",labels:["L","Retorno","N + PE"]},
  "instalador-3":{terms:"Comum recebe fase; saída leva fase comandada; contacto abre ou fecha.",worked:"Com o contacto aberto a lâmpada apaga. Ao fechar, o percurso da fase até à carga fica completo.",labels:["Entrada","Contacto","Saída"]},
  "instalador-4":{terms:"Comum e viajantes permitem dois pontos de comando.",worked:"Cada comutador liga o comum a um dos viajantes. A luz acende quando existe um percurso completo entre ambos.",labels:["Comum","Viajantes","Comum"]},
  "instalador-5":{terms:"Fase, neutro e PE têm funções distintas; aperto e continuidade reduzem riscos.",worked:"Num painel didático, identifica os bornes, verifica continuidade do PE e confirma a ausência de cobre exposto.",labels:["L","N","PE"]},
  "instalador-6":{terms:"Derivação distribui, conector assegura ligação e caixa mantém proteção e acesso.",worked:"Agrupa condutores pela função e circuito, usa conectores compatíveis e mantém identificação legível.",labels:["Entrada","Derivação","Saídas"]},
  "instalador-7":{terms:"Circuito dedicado alimenta uma utilização definida; simultaneidade estima cargas em conjunto.",worked:"Compara forno, termoacumulador e máquina. Analisa potência, ambiente e regras aplicáveis antes de separar circuitos.",labels:["Carga","Condições","Circuito"]},
  "instalador-8":{terms:"Queda de tensão cresce com corrente e comprimento e reduz com maior secção.",worked:"Compara o mesmo equipamento a 5 m e 30 m. Mantendo tudo o resto, o percurso mais longo apresenta maior queda.",labels:["Corrente","Comprimento","ΔU"]},
  "instalador-9":{terms:"Continuidade verifica percurso; isolamento avalia separação; energização vem depois dos ensaios.",worked:"Ordena: inspeção visual, continuidade do PE, isolamento e restantes ensaios previstos, só depois energização.",labels:["Inspecionar","Ensaiar","Energizar"]},
  "instalador-10":{terms:"Projeto, materiais, montagem, identificação e ensaios formam uma sequência única.",worked:"Parte da planta, define circuitos, seleciona materiais, representa ligações e prepara o plano de ensaios.",labels:["Projeto","Montagem","Ensaios"]},
  "tecnico-1":{terms:"Sobrecarga é excesso num circuito íntegro; curto-circuito é ligação de impedância muito baixa.",worked:"Vários equipamentos podem causar sobrecarga gradual. Contacto direto entre condutores ativos pode originar curto-circuito elevado.",labels:["Normal","Sobrecarga","Curto"]},
  "tecnico-2":{terms:"In é corrente nominal; curva descreve disparo; poder de corte limita a corrente interrompível.",worked:"Relaciona corrente da carga, capacidade do condutor e calibre. Aumentar o disjuntor sem rever o circuito pode retirar proteção.",labels:["Carga","Condutor","Disjuntor"]},
  "tecnico-3":{terms:"Corrente residual é desequilíbrio; IΔn é sensibilidade nominal; teste verifica mecanismo.",worked:"O diferencial compara correntes nos ativos. Se parte seguir outro caminho, o desequilíbrio pode fazê-lo atuar.",labels:["Entrada","ΔI","Saída"]},
  "tecnico-4":{terms:"Elétrodo liga à terra; PE interliga massas; equipotencialidade reduz diferenças perigosas.",worked:"Segue um defeito desde a massa pelo PE e sistema de terra até permitir a atuação coordenada da proteção.",labels:["Massa","PE","Terra"]},
  "tecnico-5":{terms:"Transitória é breve; permanente dura; coordenação escolhe dispositivos por origem e nível.",worked:"Descarga indireta tende a produzir impulso transitório. Perda de neutro pode originar condição prolongada diferente.",labels:["Origem","Duração","Proteção"]},
  "tecnico-6":{terms:"Montante fica antes, jusante depois e seletividade limita a zona desligada.",worked:"Num defeito de circuito final, procura que a proteção mais próxima atue sem cortar desnecessariamente toda a instalação.",labels:["Montante","Defeito","Jusante"]},
  "tecnico-7":{terms:"Corrente presumida é a esperada no ponto; poder de corte é a capacidade do dispositivo.",worked:"Compara a corrente de curto-circuito prevista com a marcação. O poder de corte não pode ser inferior ao necessário.",labels:["Icc","Comparar","Corte"]},
  "tecnico-8":{terms:"Corte geral, proteção e circuitos finais devem ser separados e identificados.",worked:"Organiza da alimentação para as saídas, etiqueta cada circuito e reserva acesso para operação e ensaio.",labels:["Entrada","Proteções","Saídas"]},
  "tecnico-9":{terms:"L1, L2 e L3 são fases; equilíbrio distribui cargas; assimetria indica distribuição desigual.",worked:"Distribui cargas monofásicas semelhantes pelas três fases e compara as correntes resultantes.",labels:["L1","L2","L3"]},
  "tecnico-10":{terms:"Unifilar simplifica ligações; aparelhagem executa funções; coordenação garante conjunto coerente.",worked:"Reúne alimentação, cargas, canalizações e proteções num diagrama e confirma cada relação antes de montar.",labels:["Alimentação","Quadro","Circuitos"]},
  "especialista-1":{terms:"Sintoma é observado; hipótese é explicação possível; evidência confirma ou rejeita.",worked:"Confirma a falha, delimita o circuito, mede uma variável e compara o resultado esperado antes de substituir componentes.",labels:["Sintoma","Medição","Conclusão"]},
  "especialista-2":{terms:"Tensão é diferença entre pontos; mede-se em paralelo; categoria protege no ambiente previsto.",worked:"Seleciona função e bornes, estima o valor, liga em paralelo no painel didático e lê a unidade.",labels:["Ponto A","V","Ponto B"]},
  "especialista-3":{terms:"Continuidade indica percurso de baixa resistência e exige circuito desenergizado.",worked:"Isola o circuito, confirma ausência de tensão e mede por troços até localizar a interrupção.",labels:["Início","Abertura","Fim"]},
  "especialista-4":{terms:"Isolamento separa condutores; tensão de ensaio é própria; cargas sensíveis podem exigir desligamento.",worked:"Prepara o circuito segundo o procedimento, ensaia entre conjuntos definidos e compara com os critérios aplicáveis.",labels:["Condutor","Isolamento","Condutor"]},
  "especialista-5":{terms:"Medição em série abre o percurso; pinça lê campo num condutor; alcance limita o instrumento.",worked:"Se não quiseres abrir o circuito, seleciona pinça adequada e envolve apenas um condutor ativo.",labels:["Condutor","Pinça","A"]},
  "especialista-6":{terms:"Polaridade confirma o condutor ativo no dispositivo previsto.",worked:"Segue a fase da origem até à proteção e ao comando. Confirma que a interrupção unipolar atua no condutor definido.",labels:["Origem","Comando","Carga"]},
  "especialista-7":{terms:"Fuga cria desequilíbrio; divisão por circuitos delimita; medir confirma sem anular proteção.",worked:"Regista o disparo, desliga circuitos finais, repõe o diferencial e reintroduz circuitos de forma controlada.",labels:["Disparo","Isolar","Medir"]},
  "especialista-8":{terms:"Ligação resistiva causa queda sob carga, aquecimento e instabilidade.",worked:"Mede sem carga e sob carga. Uma diferença anormal ajuda a localizar o ponto de elevada resistência.",labels:["Sem carga","ΔV","Com carga"]},
  "especialista-9":{terms:"Condição descreve contexto; método permite repetir; valores sustentam conclusão.",worked:"Regista instrumento, pontos, resultados e limites. Separa factos observados da interpretação técnica.",labels:["Método","Valores","Conclusão"]},
  "especialista-10":{terms:"Segurança, esquema, inspeção, medição e confirmação encerram o diagnóstico.",worked:"Começa pelo sintoma, cria hipóteses, mede por etapas, corrige no caso simulado e repete o ensaio final.",labels:["Inspecionar","Diagnosticar","Confirmar"]}
};

export default function FullVoltzApp({user,loadRemote,saveRemote,onSignOut}:{user:User;loadRemote:()=>Promise<Data|null>;saveRemote:(data:Data)=>Promise<void>;onSignOut:()=>void}){
  const storageKey=`voltz-progress-v1:${user.id}`;
  const [view,setView]=useState<View>("percurso");
  const [data,setData]=useState<Data>(initial);
  const [categoryIndex,setCategoryIndex]=useState(0);
  const [selected,setSelected]=useState(allLevels[0]);
  const [slide,setSlide]=useState(0);
  const [quiz,setQuiz]=useState<Check[]>([]);
  const [question,setQuestion]=useState(0);
  const [answer,setAnswer]=useState<number|null>(null);
  const [score,setScore]=useState(0);
  const [missedCurrent,setMissedCurrent]=useState(false);
  const [finished,setFinished]=useState(false);
  const [manualStep,setManualStep]=useState(0);
  const [resetOpen,setResetOpen]=useState(false);
  useEffect(()=>{let local:Data|null=null;try{const saved=localStorage.getItem(storageKey)||localStorage.getItem(legacyStorageKey);if(saved){local=JSON.parse(saved);setData(local!)}localStorage.removeItem(legacyStorageKey)}catch{}void loadRemote().then(remote=>{if(remote){setData(remote);localStorage.setItem(storageKey,JSON.stringify(remote))}else if(local)void saveRemote(local)}).catch(()=>{})},[storageKey]);
  async function save(next:Data){setData(next);try{localStorage.setItem(storageKey,JSON.stringify(next))}catch{}void saveRemote(next).catch(()=>{})}
  const manualRead=data.completedLessons.includes("manual-iniciacao");
  const completedCount=data.completedLessons.filter(x=>x.startsWith("course-")).length;
  const currentIndex=Math.min(completedCount,allLevels.length-1);
  const isUnlocked=(id:string)=>manualRead&&allLevels.findIndex(x=>x.id===id)<=completedCount;
  function openLevel(level:typeof allLevels[number]){if(!isUnlocked(level.id))return;setSelected(level);setSlide(0);setView("aula")}
  function buildQuiz(level:typeof allLevels[number]){const others=shuffle(level.category.levels.filter(x=>x.id!==level.id));const objectives=others.map(x=>x.objective);const theories=others.map(x=>x.theory);const practices=others.map(x=>x.practice);const correctTheory=level.theory;const correctPractice=level.practice;const formula=level.formula||`Princípio: ${level.title}`;const checks:Check[]=[
    {q:`Qual é o objetivo do nível “${level.title}”?`,options:[level.objective,objectives[0],objectives[1]],answer:0,explanation:`O objetivo é ${level.objective.toLowerCase()}`},
    {q:`Que afirmação descreve corretamente “${level.title}”?`,options:[correctTheory,theories[0],theories[1]],answer:0,explanation:correctTheory},
    {q:"Qual destas tarefas aplica diretamente o que acabaste de aprender?",options:[correctPractice,practices[0],practices[1]],answer:0,explanation:`A aplicação proposta na aula é: ${correctPractice}`},
    {q:"Que relação ou princípio deves recordar neste nível?",options:[formula,others[0].formula||others[0].title,others[1].formula||others[1].title],answer:0,explanation:`A referência apresentada na aula é “${formula}”.`},
    {q:`Que par pertence ao mesmo nível?`,options:[`${level.title} — ${level.objective}`,`${level.title} — ${objectives[2]}`,`${others[2].title} — ${level.objective}`],answer:0,explanation:`“${level.title}” está ligado ao objetivo “${level.objective}”.`},
    {q:"Antes de escolher uma resposta, o que deves conseguir explicar?",options:[correctTheory,theories[2],theories[3]],answer:0,explanation:`A ideia essencial é: ${correctTheory}`},
    {q:"Qual é o exemplo prático correto para este conceito?",options:[correctPractice,practices[2],practices[3]],answer:0,explanation:`Este exemplo verifica o conceito: ${correctPractice}`},
    {q:`Qual destas sínteses corresponde a “${level.title}”?`,options:[`${level.objective} ${correctTheory}`,`${objectives[4]} ${theories[4]}`,`${objectives[5]} ${theories[5]}`],answer:0,explanation:`A síntese junta o objetivo e o princípio explicados nesta aula.`},
    {q:"Que evidência mostra que compreendeste este nível?",options:[`Conseguir explicar o princípio e aplicá-lo: ${correctPractice}`,`Memorizar apenas o título “${level.title}”`,`Escolher uma opção sem justificar`],answer:0,explanation:"Compreender significa explicar o princípio e aplicá-lo a um caso, não apenas memorizar."},
    {q:"Qual é a conclusão tecnicamente coerente com a aula?",options:[correctTheory,theories[6],theories[7]],answer:0,explanation:correctTheory}
  ];if(level.id==="aprendiz-1")checks.splice(4,4,
    {q:"Uma fonte de 12 V alimenta uma resistência de 6 Ω. Qual é a corrente?",options:["2 A","6 A","72 A"],answer:0,explanation:"Pela Lei de Ohm, I = U ÷ R = 12 ÷ 6 = 2 A."},
    {q:"Para procurar a tensão indicada numa tomada de um painel didático, que grandeza selecionas?",options:["V — tensão","A — corrente","Ω — resistência"],answer:0,explanation:"A tensão é medida em volt e identificada por V. O procedimento real exige equipamento e competência adequados."},
    {q:"O visor indica 2 A. Que grandeza foi medida?",options:["Corrente","Tensão","Resistência"],answer:0,explanation:"Ampere, símbolo A, é a unidade da corrente elétrica."},
    {q:"Mantendo 12 V, a resistência passa de 6 Ω para 12 Ω. O que acontece à corrente no modelo simples?",options:["Diminui para 1 A","Aumenta para 4 A","Mantém-se em 2 A"],answer:0,explanation:"I = 12 ÷ 12 = 1 A. Com a mesma tensão, aumentar a resistência reduz a corrente."}
  );if(level.id==="aprendiz-2")checks.splice(4,4,
    {q:"Uma carga resistiva ideal tem 24 V e 12 Ω. Qual é a corrente?",options:["2 A","0,5 A","288 A"],answer:0,explanation:"I = U ÷ R = 24 ÷ 12 = 2 A."},
    {q:"Mantendo R = 10 Ω, a tensão sobe de 10 V para 20 V. O que acontece à corrente?",options:["Duplica, de 1 A para 2 A","Reduz para metade","Não muda"],answer:0,explanation:"I = U ÷ R. Com resistência constante, duplicar a tensão duplica a corrente."},
    {q:"Mantendo U = 12 V, a resistência sobe de 6 Ω para 12 Ω. Qual é a nova corrente?",options:["1 A","2 A","12 A"],answer:0,explanation:"I = 12 ÷ 12 = 1 A; duplicar a resistência reduz a corrente para metade."},
    {q:"Queres calcular resistência conhecendo tensão e corrente. Que forma usas?",options:["R = U ÷ I","R = U × I","R = I ÷ U"],answer:0,explanation:"Reorganizando U = R × I, obtém-se R = U ÷ I."}
  );if(level.id==="aprendiz-3")checks.splice(4,4,
    {q:"Um aquecedor de 1,5 kW funciona durante 3 h. Quanta energia utiliza?",options:["4,5 kWh","2 kWh","0,5 kWh"],answer:0,explanation:"E = P × t = 1,5 × 3 = 4,5 kWh."},
    {q:"Dois aparelhos usam 2 kWh. Um funciona 2 h e outro 1 h. Qual tem maior potência?",options:["O que funciona apenas 1 h","O que funciona 2 h","Têm obrigatoriamente a mesma potência"],answer:0,explanation:"Para usar a mesma energia em menos tempo, o segundo aparelho tem maior potência: 2 kW em vez de 1 kW."},
    {q:"Uma carga de 2 kW funciona durante 30 minutos. Qual é a energia?",options:["1 kWh","4 kWh","60 kWh"],answer:0,explanation:"30 minutos são 0,5 h. E = 2 × 0,5 = 1 kWh."},
    {q:"Um equipamento usa 6 kWh em 3 h. Qual foi a potência média no modelo?",options:["2 kW","18 kW","0,5 kW"],answer:0,explanation:"P = E ÷ t = 6 ÷ 3 = 2 kW."}
  );if(level.id==="aprendiz-4")checks.splice(2,6,
    {q:"A forma de onda sobe e desce, atravessando o zero periodicamente. Que tipo representa?",options:["CA","CC","Uma resistência"],answer:0,explanation:"Uma grandeza que alterna periodicamente de sentido é corrente alternada.",visual:"ac-wave"},
    {q:"A linha mantém polaridade e valor no mesmo sentido. Que tipo representa?",options:["CC","CA","Frequência"],answer:0,explanation:"A corrente contínua mantém polaridade definida.",visual:"dc-line"},
    {q:"Como classificas normalmente a rede doméstica portuguesa e uma bateria?",options:["Rede: CA; bateria: CC","Rede: CC; bateria: CA","Ambas são sempre CA"],answer:0,explanation:"A rede doméstica fornece CA; uma bateria fornece CC.",visual:"ac-dc-devices"},
    {q:"O que significa 50 Hz na rede de CA?",options:["50 ciclos por segundo","50 volts por ciclo","50 mudanças de aparelho"],answer:0,explanation:"Hertz mede frequência: 50 Hz correspondem a 50 ciclos por segundo."},
    {q:"Que símbolo procuras para identificar tensão alternada num aparelho?",options:["V~","V⎓","Ω"],answer:0,explanation:"O til ~ identifica grandeza alternada; o símbolo ⎓ identifica contínua."},
    {q:"Uma saída USB fornece normalmente que tipo de tensão?",options:["CC","CA a 50 Hz","Nenhuma das duas"],answer:0,explanation:"A saída USB fornece tensão contínua regulada."}
  );if(level.id==="aprendiz-5")checks.splice(2,6,
    {q:"Neste esquema, o interruptor está fechado. O que acontece à lâmpada?",options:["Acende, porque existe percurso fechado","Apaga, porque falta neutro","Nada, porque a proteção impede corrente"],answer:0,explanation:"Com fonte, proteção, comando fechado, carga e retorno, o percurso fica completo.",visual:"closed-circuit"},
    {q:"O interruptor cria uma abertura no condutor ativo. Qual é o resultado?",options:["A corrente é interrompida e a lâmpada apaga","A corrente aumenta","O neutro transforma-se em fase"],answer:0,explanation:"Abrir o comando interrompe o percurso da corrente até à carga.",visual:"open-circuit"},
    {q:"Que elementos completam o percurso funcional mostrado?",options:["L até à carga e N no retorno","Apenas PE","Dois condutores PE"],answer:0,explanation:"No modelo monofásico, L alimenta a carga através do comando e N completa o retorno.",visual:"closed-circuit"},
    {q:"Se existir tensão mas o interruptor estiver aberto, há corrente contínua pela lâmpada?",options:["Não","Sim, sempre","Só porque existe proteção"],answer:0,explanation:"A tensão pode existir a montante do interruptor, mas o percurso aberto impede corrente na carga.",visual:"open-circuit"},
    {q:"Qual é a função do dispositivo antes do interruptor neste esquema?",options:["Proteção do circuito","Produzir luz","Substituir o neutro"],answer:0,explanation:"O dispositivo de proteção está a montante do comando e da carga.",visual:"closed-circuit"},
    {q:"Onde deve atuar o interruptor neste modelo introdutório?",options:["No condutor ativo L antes da carga","No PE","Em paralelo direto com a fonte"],answer:0,explanation:"O comando da iluminação atua no condutor ativo que alimenta a carga.",visual:"open-circuit"}
  );if(level.id==="aprendiz-6")checks.splice(2,6,
    {q:"L1 abriu neste circuito em série. O que acontece a L2?",options:["L2 apaga","L2 fica mais forte","L2 mantém-se igual"],answer:0,explanation:"Em série existe um único percurso; abrir L1 interrompe-o para todos os elementos.",visual:"series-open"},
    {q:"L1 abriu num ramo paralelo. O que acontece a L2?",options:["L2 pode continuar ligada","L2 apaga sempre","A fonte deixa de ter tensão"],answer:0,explanation:"O ramo de L2 continua a formar um percurso fechado independente.",visual:"parallel-open"},
    {q:"Qual dos dois desenhos representa uma associação em paralelo?",options:["O desenho com dois ramos","O desenho com um único percurso","Nenhum"],answer:0,explanation:"Em paralelo, cada carga ocupa um ramo entre os mesmos dois pontos.",visual:"series-parallel"},
    {q:"Que grandeza é comum às duas lâmpadas ligadas em série?",options:["A corrente","A tensão individual","A potência"],answer:0,explanation:"Num circuito em série, a mesma corrente atravessa os elementos.",visual:"series-open"},
    {q:"Que grandeza é comum aos ramos do circuito em paralelo?",options:["A tensão","A corrente de cada carga obrigatoriamente","A resistência"],answer:0,explanation:"Os ramos ligados aos mesmos dois pontos têm a mesma tensão.",visual:"parallel-open"},
    {q:"Porque são as cargas domésticas normalmente ligadas em paralelo?",options:["Recebem a tensão prevista e funcionam de forma independente","Precisam da mesma corrente em sequência","Uma avaria deve desligar todas"],answer:0,explanation:"A ligação em paralelo permite funcionamento independente à tensão do circuito.",visual:"series-parallel"}
  );return shuffle(checks).map(shuffleCheck)}
  function startChallenge(){if(!manualRead){openManual();return}setQuiz(buildQuiz(selected));setQuestion(0);setAnswer(null);setScore(0);setMissedCurrent(false);setFinished(false);setView("desafio")}
  function choose(i:number){if(answer!==null)return;setAnswer(i);if(i===quiz[question].answer&&!missedCurrent)setScore(s=>s+1);if(i!==quiz[question].answer)setMissedCurrent(true)}
  function retryQuestion(){setQuiz(qs=>qs.map((x,i)=>i===question?shuffleCheck(x):x));setAnswer(null)}
  function nextQuestion(){if(question<quiz.length-1){setQuestion(q=>q+1);setAnswer(null);setMissedCurrent(false);return}const passed=score>=8;setFinished(true);if(passed&&!data.completedLessons.includes(`course-${selected.id}`)){const xp=data.xp+xpForScore(score);void save({...data,xp,level:Math.floor(xp/500)+1,completedLessons:[...data.completedLessons,`course-${selected.id}`]})}}
  function continueCourse(){const next=Math.min(allLevels.findIndex(x=>x.id===selected.id)+1,allLevels.length-1);setCategoryIndex(categories.findIndex(x=>x.id===allLevels[next].category.id));setView("percurso")}
  function openManual(){setManualStep(0);setView("manual")}
  function openCurrent(){if(!manualRead){openManual();return}const item=allLevels[currentIndex];setCategoryIndex(categories.findIndex(x=>x.id===item.category.id));openLevel(item)}
  function completeManual(){if(!manualRead)void save({...data,completedLessons:[...data.completedLessons,"manual-iniciacao"]});setView("percurso")}
  function resetProgress(){localStorage.removeItem(storageKey);setData(initial);void saveRemote(initial);setSelected(allLevels[0]);setCategoryIndex(0);setManualStep(0);setSlide(0);setQuiz([]);setQuestion(0);setAnswer(null);setScore(0);setFinished(false);setResetOpen(false);setView("percurso")}
  const nav=(target:View)=>{if(target==="desafio")startChallenge();else setView(target)};
  return <div className="app-shell course-app">
    <aside className="sidebar"><button className="brand" onClick={()=>setView("percurso")}><span><Zap fill="currentColor"/></span>Voltz</button><nav><Nav active={view==="percurso"} icon={<Home/>} label="Percurso" onClick={()=>nav("percurso")}/><Nav active={view==="manual"} icon={<BookOpen/>} label="Manual" onClick={openManual}/><Nav active={view==="aula"} icon={<Gauge/>} label="Aula visual" onClick={openCurrent}/><Nav active={view==="desafio"} icon={<Trophy/>} label="Desafio" onClick={startChallenge}/><Nav active={view==="perfil"} icon={<UserRound/>} label="Perfil" onClick={()=>nav("perfil")}/></nav><div className="sidebar-foot"><ShieldCheck/> Formação introdutória baseada em prática portuguesa</div></aside>
    <main className="main"><header className="topbar"><div className="mobile-brand"><Zap fill="currentColor"/> Voltz</div><span className="version-badge">v3.0 · contas sincronizadas</span><div className="stat flame"><Flame/><strong>{data.streak}</strong><span>dias</span></div><div className="stat"><Zap/><strong>{data.xp}</strong><span>XP</span></div><button className="avatar" aria-label="Abrir perfil" onClick={()=>setView("perfil")}>{user.avatar?<img src={user.avatar} alt="" referrerPolicy="no-referrer"/>:user.name[0]?.toUpperCase()||"A"}</button></header>
      {view==="percurso"&&<Journey data={data} user={user} categoryIndex={categoryIndex} setCategoryIndex={setCategoryIndex} openLevel={openLevel} openCurrent={openCurrent} openManual={openManual}/>} 
      {view==="manual"&&<Manual step={manualStep} setStep={setManualStep} done={manualRead} complete={completeManual}/>} 
      {view==="aula"&&<Lesson level={selected} slide={slide} setSlide={setSlide} startChallenge={startChallenge}/>} 
      {view==="desafio"&&<Challenge quiz={quiz.length?quiz:buildQuiz(selected)} question={question} answer={answer} score={score} finished={finished} choose={choose} retry={retryQuestion} next={nextQuestion} reset={startChallenge} continueCourse={continueCourse}/>} 
      {view==="perfil"&&<Profile user={user} data={data} resetProgress={()=>setResetOpen(true)} onSignOut={onSignOut}/>} 
    </main>
    <nav className="mobile-nav five-items" aria-label="Navegação principal"><Nav active={view==="percurso"} icon={<Home/>} label="Percurso" onClick={()=>nav("percurso")}/><Nav active={view==="manual"} icon={<BookOpen/>} label="Manual" onClick={openManual}/><Nav active={view==="aula"} icon={<Gauge/>} label="Aula" onClick={openCurrent}/><Nav active={view==="desafio"} icon={<Trophy/>} label="Desafio" onClick={startChallenge}/><Nav active={view==="perfil"} icon={<UserRound/>} label="Perfil" onClick={()=>nav("perfil")}/></nav>
    {resetOpen&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setResetOpen(false)}}><section className="confirm-modal" role="dialog" aria-modal="true" aria-labelledby="reset-title" aria-describedby="reset-description"><div className="modal-icon"><ShieldCheck/></div><h2 id="reset-title">Reiniciar todo o progresso?</h2><p id="reset-description">Esta ação apaga o manual lido, XP e níveis concluídos da tua conta em todos os dispositivos. Não pode ser anulada.</p><div className="modal-actions"><button className="ghost-button" onClick={()=>setResetOpen(false)}>Cancelar</button><button className="danger-button" onClick={resetProgress}>Apagar progresso</button></div></section></div>}
  </div>
}

function Nav({active,icon,label,onClick}:{active:boolean;icon:React.ReactNode;label:string;onClick:()=>void}){return <button className={`nav-item ${active?"active":""}`} onClick={onClick}>{icon}<span>{label}</span></button>}

function Journey({data,categoryIndex,setCategoryIndex,openLevel,openCurrent,openManual}:{data:Data;user:User;categoryIndex:number;setCategoryIndex:(n:number)=>void;openLevel:(l:typeof allLevels[number])=>void;openCurrent:()=>void;openManual:()=>void}){
  const category=categories[categoryIndex];const completed=data.completedLessons.filter(x=>x.startsWith("course-")).length;const manualRead=data.completedLessons.includes("manual-iniciacao");const percent=completed/50*100;
  return <div className="page journey-page full-journey">
    <section className="course-hero"><div><span className="eyebrow"><Sparkles/> Formação técnica progressiva</span><h1>{manualRead?"Da teoria ao diagnóstico.":"Primeiro, entende a base."}</h1><p>{manualRead?"50 níveis em cinco categorias, com explicações técnicas, aplicação e avaliação em cada etapa.":"Lê o Manual de Iniciação para aprenderes os termos e esquemas usados ao longo do curso."}</p><button className="primary-button" onClick={openCurrent}>{manualRead?`Continuar no nível ${Math.min(completed+1,50)}`:"Abrir manual"} <ChevronRight/></button></div><div className="course-meter"><strong>{completed}<small>/50</small></strong><span>níveis concluídos</span><Progress value={percent}/></div></section>
    <button className={`manual-entry ${manualRead?"done":"current"}`} onClick={openManual}><span>{manualRead?<Check/>:<BookOpen/>}</span><div><small>ETAPA OBRIGATÓRIA</small><strong>Manual de Iniciação Voltz</strong><p>{manualRead?"Manual lido · disponível para consulta a qualquer momento":"8 capítulos visuais · aprende os termos antes dos níveis"}</p></div><b>{manualRead?"Consultar":"Começar"}<ChevronRight/></b></button>
    <div className="category-tabs" role="tablist" aria-label="Categorias">{categories.map((c,i)=><button key={c.id} className={i===categoryIndex?"active":""} style={{"--cat":c.color} as React.CSSProperties} onClick={()=>setCategoryIndex(i)}><span>{i+1}</span><strong>{c.name}</strong><small>{c.role}</small></button>)}</div>
    <div className="section-head"><div><span className="eyebrow">Categoria {categoryIndex+1} de 5</span><h2>{category.name} · {category.role}</h2></div><span>{category.levels.filter(l=>data.completedLessons.includes(`course-${l.id}`)).length}/10</span></div>
    <section className="level-grid">{category.levels.map((level,i)=>{const global=allLevels.findIndex(x=>x.id===level.id);const done=data.completedLessons.includes(`course-${level.id}`);const unlocked=global<=completed;return <button key={level.id} className={`level-card ${done?"done":""} ${unlocked&&!done?"current":""}`} disabled={!unlocked} onClick={()=>openLevel({...level,category})}><span className="level-number">{done?<Check/>:unlocked?<Zap/>:<LockKeyhole/>}</span><span><small>Nível {i+1}</small><strong>{level.title}</strong><em>{done?"Concluído":unlocked?"Aula + 10 perguntas":"Bloqueado"}</em></span><ChevronRight/></button>})}</section>
    <p className="safety-note"><ShieldCheck/> Formação introdutória. O progresso é sincronizado com a tua conta para continuares noutro dispositivo. A execução de instalações em Portugal depende das qualificações e regras aplicáveis.</p>
  </div>
}

function Manual({step,setStep,done,complete}:{step:number;setStep:(n:number)=>void;done:boolean;complete:()=>void}){
  const chapter=manualChapters[step];return <div className="page manual-page"><header className="manual-head"><div><span className="eyebrow"><BookOpen/> Manual de Iniciação</span><h1>Eletricidade explicada do zero</h1><p>Consulta livre · {done?"marcado como lido":"leitura obrigatória antes do nível 1"}</p></div>{done&&<span className="manual-done"><Check/> Manual lido</span>}</header>
    <div className="manual-progress"><div>{manualChapters.map((c,i)=><button key={c.title} className={`${i===step?"active":""} ${i<step||done?"read":""}`} onClick={()=>setStep(i)} aria-label={`Capítulo ${i+1}: ${c.title}`}>{i<step||done?<Check/>:i+1}</button>)}</div><Progress value={(step+1)/manualChapters.length*100}/></div>
    <article className="manual-sheet"><div className="manual-copy"><span className="eyebrow">Capítulo {step+1} · {chapter.tag}</span><h2>{chapter.title}</h2><p>{chapter.text}</p><p className="manual-detail">{chapter.detail}</p><ul>{chapter.points.map(point=><li key={point}><Check/>{point}</li>)}</ul><aside><ShieldCheck/><span><strong>Importante</strong>Este manual ensina conceitos e linguagem técnica. Trabalhos em instalações devem respeitar as regras aplicáveis e ser executados por pessoas qualificadas quando exigido.</span></aside></div><ManualDiagram kind={chapter.visual}/></article>
    <div className="manual-actions"><button className="ghost-button" disabled={step===0} onClick={()=>setStep(step-1)}>Anterior</button><span>{step+1} de {manualChapters.length}</span><button className="primary-button" onClick={()=>step<manualChapters.length-1?setStep(step+1):complete()}>{step<manualChapters.length-1?"Próximo capítulo":done?"Voltar ao percurso":"Marcar como lido"}<ChevronRight/></button></div>
    <footer className="manual-sources">Referência institucional: <a href="https://www.dgeg.gov.pt/pt/areas-setoriais/energia/energia-eletrica/atividade-normativa/cte-64/" target="_blank" rel="noreferrer">DGEG · CTE 64</a> e <a href="https://www.dgeg.gov.pt/pt/areas-setoriais/energia/energia-eletrica/instalacoes-de-utilizacao-de-energia-eletrica/instalacoes-eletricas-de-servico-particular-tipo-a-b-e-c/" target="_blank" rel="noreferrer">instalações elétricas de serviço particular</a>.</footer>
  </div>
}

function ManualDiagram({kind}:{kind:string}){
  if(kind==="basics")return <div className="manual-diagram basics-local" role="img" aria-label="Circuito em português que relaciona tensão, corrente e resistência"><h3>As três grandezas no circuito</h3><svg viewBox="0 0 430 270" aria-hidden="true"><path d="M70 55 H350 V215 H70 V55"/><path className="current-arrow" d="M145 55 h75 m-14-12 14 12-14 12"/><circle cx="350" cy="135" r="34"/><path d="M330 115 l40 40 M370 115 l-40 40"/><rect x="45" y="100" width="50" height="90" rx="8"/><text x="52" y="135">12 V</text><text x="52" y="158">FONTE</text><text x="224" y="42">CORRENTE (A)</text><text x="305" y="188">RESISTÊNCIA (Ω)</text><text x="126" y="242">TENSÃO: diferença entre dois pontos (V)</text></svg><p>A fonte cria tensão; com o percurso fechado existe corrente; a resistência limita essa corrente.</p></div>;
  if(kind==="parallel")return <div className="manual-diagram manual-series" role="img" aria-label="Comparação em português de duas lâmpadas em série e em paralelo"><h3>Série e paralelo</h3><div><b>SÉRIE</b><span>🔋 ─ 💡 ─ 💡 ─ ↩</span><small>Um único percurso · corrente comum</small></div><div><b>PARALELO</b><span>🔋 ─┬─ 💡 ─┬─ ↩<br/>　 └─ 💡 ─┘</span><small>Dois ramos · tensão comum</small></div><p>Se uma lâmpada abrir: em série ambas apagam; em paralelo o outro ramo pode continuar.</p></div>;
  const image=manualImages[kind];if(image)return <figure className="manual-diagram manual-photo"><img src={image.src} alt={image.alt}/><figcaption><strong>{image.caption}</strong><a href={image.href} target="_blank" rel="noreferrer">Imagem: {image.credit}</a></figcaption></figure>;
  if(kind==="conductors")return <div className="manual-diagram conductors" role="img" aria-label="Esquema dos condutores fase L, neutro N e proteção PE"><h3>Função dos condutores</h3><div><span className="brown">L</span><b>Fase</b> condutor ativo</div><div><span className="blue-dot">N</span><b>Neutro</b> circuito funcional</div><div><span className="earth">PE</span><b>Proteção</b> corrente de defeito</div><p>As cores ajudam, mas confirma sempre a função pelo esquema e por verificação adequada.</p></div>;
  return <div className="manual-diagram ready-card"><img src={asset("faisca-mobile.webp")} alt="Faísca, mascote do Voltz"/><h3>Agora já falamos a mesma língua.</h3><p>Segue para Aprendiz · Nível 1.</p></div>;
}

function Lesson({level,slide,setSlide,startChallenge}:{level:typeof allLevels[number];slide:number;setSlide:(n:number)=>void;startChallenge:()=>void}){
  const [meterMode,setMeterMode]=useState<"V"|"A"|"Ω">("V");
  const [labVoltage,setLabVoltage]=useState(12);const [labResistance,setLabResistance]=useState(6);
  const [labPower,setLabPower]=useState(1);const [labHours,setLabHours]=useState(2);
  const guide=teaching[level.id];
  const hasLab=["aprendiz-1","aprendiz-2","aprendiz-3"].includes(level.id);
  const slides=[
    {tag:"1 · Objetivo",title:level.title,text:`No fim desta aula deves conseguir ${lowerFirst(level.objective)} Não precisas de decorar tudo: procura compreender o que muda, o que se mantém e porquê.`,kind:"target"},
    {tag:"2 · Vocabulário",title:"Palavras que vais usar",text:guide.terms,kind:"theory"},
    {tag:"3 · Princípio",title:"Como funciona",text:`${level.theory} Este é o princípio que deves conseguir explicar por palavras tuas antes de avançar para o exercício.`,kind:"theory"},
    {tag:`4 · ${hasLab?"Laboratório interativo":"Exemplo para resolver"}`,title:"Prevê antes de confirmar",text:`Situação: ${level.practice} Decide primeiro o que esperas que aconteça e explica porquê.`,kind:"practice"},
    {tag:"5 · Esquema técnico",title:"Segue o raciocínio visual",text:level.id==="aprendiz-4"?"Compara as duas colunas separadamente. CA: alternância periódica, rede doméstica e 50 Hz. CC: polaridade definida, bateria e USB.":level.id==="aprendiz-6"?"Compara os dois circuitos: série tem um único percurso; paralelo tem dois ramos independentes. Observa o efeito de abrir L1.":`Lê o esquema da esquerda para a direita: ${guide.labels.join(" → ")}. ${level.practice}`,kind:"practice"},
    {tag:"6 · Verificação",title:"O que tens de dominar",text:`Deves conseguir explicar ${level.title.toLowerCase()}, relacionar o conceito com o exemplo e justificar uma decisão. O desafio seguinte avalia apenas estas ideias desta aula.`,kind:"check"}
  ];const item=slides[slide];
  const visual=level.id==="aprendiz-1"&&slide===3?<MultimeterLab mode={meterMode} setMode={setMeterMode}/>:level.id==="aprendiz-2"&&slide===3?<OhmLab voltage={labVoltage} resistance={labResistance} setVoltage={setLabVoltage} setResistance={setLabResistance}/>:level.id==="aprendiz-3"&&slide===3?<PowerLab power={labPower} hours={labHours} setPower={setLabPower} setHours={setLabHours}/>:slide===4?<TechnicalVisual level={level} guide={guide}/>:<div className="tech-visual"><span>{item.kind==="target"?<Gauge/>:item.kind==="theory"?<Zap/>:item.kind==="practice"?<BookOpen/>:<Check/>}</span><small>{level.category.name} · Nível {level.category.levels.findIndex(x=>x.id===level.id)+1} · 2–5 min</small>{level.formula&&<strong>{level.formula}</strong>}</div>;
  const lessonHint=slide===5?"Se não conseguires justificar a resposta, volta ao princípio e ao exemplo resolvido.":slide===3&&level.id==="aprendiz-1"?"Seleciona V, A e Ω e observa como mudam a unidade, a ligação e o borne indicado.":slide===3&&level.id==="aprendiz-2"?"Escolhe o exemplo 230 V/46 Ω ou move os controlos; prevê I antes de a revelar.":slide===3&&level.id==="aprendiz-3"?"Altera potência e tempo; prevê a energia e só depois revela o resultado.":slide===3?"Faz uma previsão antes de abrires a solução explicada.":"Lê devagar, identifica os dados e explica cada ligação por palavras tuas.";
  return <div className="page lesson-page"><div className="lesson-top"><button onClick={()=>setSlide(0)} aria-label="Voltar ao início"><X/></button><Progress value={(slide+1)/slides.length*100}/><span>{slide+1}/{slides.length}</span></div><section className="lesson-card technical-lesson"><div className={`lesson-visual tech-${item.kind}`}>{visual}</div><div className="lesson-copy"><span className="eyebrow">{item.tag}</span><h1>{item.title}</h1><p>{item.text}</p>{slide===3&&<details className="worked-solution"><summary>Ver solução explicada</summary><p>{guide.worked}</p></details>}<div className="faisca-note"><img src={asset("faisca-mobile.webp")} width="62" height="80" alt="Faísca, mascote do Voltz"/><span><strong>Dica da Faísca</strong>{lessonHint}</span></div></div></section><div className="lesson-actions"><button className="ghost-button" disabled={slide===0} onClick={()=>setSlide(slide-1)}>Anterior</button><button className="primary-button" onClick={()=>slide<slides.length-1?setSlide(slide+1):startChallenge()}>{slide<slides.length-1?"Continuar":"Fazer 10 perguntas"}<ChevronRight/></button></div></div>
}

function MultimeterLab({mode,setMode}:{mode:"V"|"A"|"Ω";setMode:(m:"V"|"A"|"Ω")=>void}){const info={V:["Tensão","volt","Em paralelo · entrada VΩ"],A:["Corrente","ampere","Em série · entrada A própria"],Ω:["Resistência","ohm","Circuito desenergizado · entrada VΩ"]}[mode];return <div className="meter-lab"><small>ILUSTRAÇÃO DIDÁTICA · OS BORNES VARIAM ENTRE APARELHOS</small><div className="meter"><div className="meter-screen"><b>{mode==="V"?"12.0":mode==="A"?"2.00":"6.00"}</b><span>{mode}</span></div><div className="meter-dial">{mode}</div><div className="meter-ports"><span><i className="black"/>COM</span><span><i className="red"/>VΩ</span><span><i className="red"/>A</span></div></div><div className="meter-controls" aria-label="Escolher grandeza">{(["V","A","Ω"] as const).map(x=><button key={x} className={mode===x?"active":""} onClick={()=>setMode(x)}>{x}</button>)}</div><p><strong>{info[0]}</strong> · unidade: {info[1]}<br/>{info[2]}</p></div>}

function OhmLab({voltage,resistance,setVoltage,setResistance}:{voltage:number;resistance:number;setVoltage:(n:number)=>void;setResistance:(n:number)=>void}){const [revealed,setRevealed]=useState(false);const current=voltage/resistance;const changeV=(n:number)=>{setVoltage(n);setRevealed(false)};const changeR=(n:number)=>{setResistance(n);setRevealed(false)};return <div className="ohm-lab"><small>MODELO DE CARGA RESISTIVA IDEAL</small><div className="lab-presets"><button onClick={()=>{changeV(12);changeR(6)}}>12 V / 6 Ω</button><button onClick={()=>{changeV(230);changeR(46)}}>Exemplo 230 V / 46 Ω</button></div><div className="ohm-result"><span>U<strong>{voltage} V</strong></span><b>÷</b><span>R<strong>{resistance} Ω</strong></span><b>=</b><span>I<strong>{revealed?`${current.toFixed(1)} A`:"?"}</strong></span></div><label>Tensão <small>6–230 V</small><input aria-label="Tensão entre 6 e 230 volt" type="range" min="6" max="230" step="1" value={voltage} onChange={e=>changeV(Number(e.target.value))}/></label><label>Resistência <small>3–46 Ω</small><input aria-label="Resistência entre 3 e 46 ohm" type="range" min="3" max="46" step="1" value={resistance} onChange={e=>changeR(Number(e.target.value))}/></label><button className="lab-reveal" onClick={()=>setRevealed(true)}>Confirmar previsão</button><p>Se aumentares R sem alterar U, I desce.</p></div>}

function PowerLab({power,hours,setPower,setHours}:{power:number;hours:number;setPower:(n:number)=>void;setHours:(n:number)=>void}){const [revealed,setRevealed]=useState(false);const energy=power*hours;const changeP=(n:number)=>{setPower(n);setRevealed(false)};const changeT=(n:number)=>{setHours(n);setRevealed(false)};return <div className="ohm-lab power-lab"><small>LABORATÓRIO DE POTÊNCIA E ENERGIA</small><div className="lab-presets"><button onClick={()=>{changeP(1);changeT(2)}}>1 kW × 2 h</button><button onClick={()=>{changeP(2);changeT(1)}}>2 kW × 1 h</button></div><div className="ohm-result"><span>P<strong>{power.toFixed(1)} kW</strong></span><b>×</b><span>t<strong>{hours.toFixed(1)} h</strong></span><b>=</b><span>E<strong>{revealed?`${energy.toFixed(1)} kWh`:"?"}</strong></span></div><label>Potência <small>0,5–3 kW</small><input aria-label="Potência entre 0,5 e 3 quilowatt" type="range" min="0.5" max="3" step="0.5" value={power} onChange={e=>changeP(Number(e.target.value))}/></label><label>Tempo <small>0,5–4 h</small><input aria-label="Tempo entre 0,5 e 4 horas" type="range" min="0.5" max="4" step="0.5" value={hours} onChange={e=>changeT(Number(e.target.value))}/></label><button className="lab-reveal" onClick={()=>setRevealed(true)}>Revelar energia</button></div>}

function TechnicalVisual({level,guide}:{level:CourseLevel;guide:Teaching}){
  if(level.id==="aprendiz-1")return <div className="level-diagram ohm-circuit" role="img" aria-label="Circuito fechado de 12 volts com uma única carga resistiva de 6 ohm e corrente de 2 ampere"><h3>U = R × I</h3><svg viewBox="0 0 430 260" aria-hidden="true"><path d="M70 50 H350 V210 H70 V50"/><rect x="45" y="92" width="50" height="76" rx="7"/><text x="53" y="123">12 V</text><text x="51" y="145">FONTE</text><rect x="295" y="105" width="110" height="55" rx="8"/><text x="310" y="128">CARGA</text><text x="309" y="149">R = 6 Ω</text><path className="current-arrow" d="M135 50 h80 m-15-12 15 12-15 12"/><text x="145" y="35">I = 2 A</text></svg><p>12 V ÷ 6 Ω = 2 A</p><small>Existe uma única carga resistiva ideal de 6 Ω no modelo.</small></div>;
  if(level.id==="aprendiz-2")return <div className="level-diagram ohm-circuit" role="img" aria-label="Circuito resistivo ideal de 230 volts, 46 ohm e 5 ampere"><h3>Lei de Ohm no circuito</h3><svg viewBox="0 0 430 260" aria-hidden="true"><path d="M70 50 H350 V210 H70 V50"/><rect x="40" y="92" width="60" height="76" rx="7"/><text x="49" y="123">230 V</text><text x="48" y="145">FONTE</text><rect x="290" y="105" width="120" height="55" rx="8"/><text x="305" y="128">CARGA</text><text x="304" y="149">R = 46 Ω</text><path className="current-arrow" d="M135 50 h80 m-15-12 15 12-15 12"/><text x="145" y="35">I = 5 A</text></svg><p>I = 230 V ÷ 46 Ω = 5 A</p><small>Modelo didático resistivo ideal; não dimensiona uma instalação real.</small></div>;
  if(level.id==="aprendiz-3")return <div className="level-diagram energy-compare" role="img" aria-label="Comparação entre um quilowatt durante duas horas e dois quilowatt durante uma hora, ambos iguais a dois quilowatt-hora"><h3>Dois caminhos, a mesma energia</h3><div><span><b>1 kW</b><small>durante</small><b>2 h</b></span><strong>= 2 kWh</strong></div><div><span><b>2 kW</b><small>durante</small><b>1 h</b></span><strong>= 2 kWh</strong></div><p>Mais potência durante menos tempo pode resultar na mesma energia.</p></div>;
  if(level.id==="aprendiz-4")return <div className="level-diagram signals" role="img" aria-label="Comparação entre corrente alternada e corrente contínua"><h3>CA versus CC</h3><div><b>CA ~</b><svg viewBox="0 0 240 70" aria-hidden="true"><path d="M0 35 C20 0 40 0 60 35 S100 70 120 35 S160 0 180 35 S220 70 240 35"/></svg><small>muda periodicamente · 50 Hz</small></div><div><b>CC ⎓</b><svg viewBox="0 0 240 70" aria-hidden="true"><path d="M0 25 H240"/></svg><small>polaridade definida · bateria/USB</small></div></div>;
  if(level.id==="aprendiz-5")return <div className="level-diagram closed-wiring" role="img" aria-label="Circuito de iluminação com fase L, proteção, interruptor fechado, lâmpada e retorno pelo neutro N"><h3>Circuito de iluminação fechado</h3><svg viewBox="0 0 520 250" aria-hidden="true"><path className="live" d="M35 65 H115 M155 65 H220 M270 65 H390"/><path className="neutral" d="M390 185 H35"/><path d="M35 65 V185 M390 65 V100 M390 150 V185"/><rect x="115" y="42" width="40" height="46" rx="6"/><text x="119" y="70">PROT.</text><circle cx="245" cy="65" r="9"/><path d="M245 65 L270 65"/><text x="215" y="38">INTERRUPTOR</text><circle cx="390" cy="125" r="25"/><path d="M373 108 l34 34 M407 108 l-34 34"/><text x="423" y="130">LÂMPADA</text><text x="38" y="54">L</text><text x="38" y="207">N</text><path className="arrow" d="M170 65 h28 m-9-7 9 7-9 7"/></svg><p>L → proteção → interruptor → lâmpada → N</p><small>Ao abrir o interruptor, surge uma interrupção no percurso ativo.</small></div>;
  if(level.id==="aprendiz-6")return <div className="level-diagram series-parallel" role="img" aria-label="Comparação entre duas lâmpadas em série e duas lâmpadas em paralelo"><h3>Série versus paralelo</h3><div className="circuit-panel"><b>SÉRIE · mesma corrente</b><svg viewBox="0 0 360 125" aria-hidden="true"><path d="M35 25 H125 M165 25 H225 M265 25 H325 V100 H35 V25"/><circle cx="145" cy="25" r="20"/><circle cx="245" cy="25" r="20"/><path className="arrow" d="M75 25 h25 m-8-7 8 7-8 7"/><text x="135" y="31">L1</text><text x="235" y="31">L2</text><text x="45" y="92">Fonte</text></svg><small>Se L1 abrir, o único percurso fica interrompido e L2 apaga.</small></div><div className="circuit-panel"><b>PARALELO · mesma tensão</b><svg viewBox="0 0 360 150" aria-hidden="true"><path d="M35 25 H325 V125 H35 V25 M105 25 V125 M255 25 V125"/><circle cx="105" cy="75" r="20"/><circle cx="255" cy="75" r="20"/><path className="arrow" d="M45 25 h32 m-8-7 8 7-8 7"/><text x="95" y="81">L1</text><text x="245" y="81">L2</text><text x="45" y="116">Fonte</text></svg><small>Se L1 abrir, o ramo de L2 continua fechado e L2 mantém-se ligada.</small></div></div>;
  return <div className="level-diagram concept-flow" role="img" aria-label={`Esquema técnico de ${level.title}: ${guide.labels.join(", ")}`}><small>{level.category.name} · esquema do nível</small><h3>{level.title}</h3><div>{guide.labels.map((label,i)=><span key={`${label}-${i}`}><b>{i+1}</b>{label}</span>)}</div><p>Identifica → relaciona → confirma</p></div>;
}

function Challenge({quiz,question,answer,score,finished,choose,retry,next,reset,continueCourse}:{quiz:Check[];question:number;answer:number|null;score:number;finished:boolean;choose:(i:number)=>void;retry:()=>void;next:()=>void;reset:()=>void;continueCourse:()=>void}){
  const passed=score>=8;const earnedXp=xpForScore(score);if(finished)return <div className="page result-page"><div className="result-card"><div className="trophy"><Trophy/></div><span className="eyebrow">Avaliação concluída</span><h1>{passed?"Nível dominado!":"Revê e tenta novamente"}</h1><p>Acertaste {score} de 10 à primeira tentativa. {passed?"O nível seguinte foi desbloqueado.":"São necessárias 8 respostas certas à primeira tentativa."}</p><div className="reward-row"><div><Zap/><strong>+{earnedXp}</strong><span>XP · {score===10?"perfeito":score===9?"excelente":score===8?"aprovado":"não aprovado"}</span></div><div><Star/><strong>{score}/10</strong><span>primeiras tentativas</span></div></div><div className="result-actions">{passed&&<button className="primary-button" onClick={continueCourse}>Continuar percurso <ChevronRight/></button>}<button className={passed?"ghost-button":"primary-button"} onClick={reset}>Novo desafio</button></div></div></div>;
  const item=quiz[question];const correct=answer===item.answer;return <div className="page challenge-page"><div className="challenge-head"><span className="eyebrow">Pergunta {question+1} de 10</span><h1>{item.q}</h1><p>A primeira resposta conta para a nota. Depois de um erro podes rever e tentar novamente.</p></div>{item.visual&&<QuestionVisual kind={item.visual}/>}<div className="option-list">{item.options.map((text,i)=><button key={`${text}-${i}`} onClick={()=>choose(i)} className={`option ${answer!==null&&i===item.answer?"correct":""} ${answer===i&&i!==item.answer?"wrong":""}`}><span>{String.fromCharCode(65+i)}</span><strong>{text}</strong>{answer!==null&&i===item.answer&&<Check/>}{answer===i&&i!==item.answer&&<X/>}</button>)}</div>{answer!==null&&<div className={`feedback ${correct?"positive":"negative"}`}><div><strong>{correct?"Correto.":"Ainda não. Revê a explicação."}</strong><span>{correct?(item.explanation||"A resposta corresponde ao princípio apresentado na aula."):`Resposta correta: ${item.options[item.answer]}. ${item.explanation||"Volta ao princípio técnico da aula e compara cada opção."} As opções serão baralhadas, mas este erro continua registado na nota.`}</span></div><button className="primary-button" onClick={correct?next:retry}>{correct?(question<9?"Próxima":"Ver resultado"):"Tentar novamente"}<ChevronRight/></button></div>}</div>
}

function QuestionVisual({kind}:{kind:NonNullable<Check["visual"]>}){
  if(kind==="ac-dc-devices")return <div className="question-visual devices" role="img" aria-label="Rede doméstica com corrente alternada e bateria e USB com corrente contínua"><span>🏠<b>Rede · CA ~</b></span><span>🔋<b>Bateria · CC ⎓</b></span><span>🔌<b>USB · CC ⎓</b></span></div>;
  if(kind==="ac-wave"||kind==="dc-line")return <div className="question-visual wave-question" role="img" aria-label={kind==="ac-wave"?"Forma de onda que alterna acima e abaixo de zero":"Linha contínua acima de zero"}><b>{kind==="ac-wave"?"forma A":"forma B"}</b><svg viewBox="0 0 420 90" aria-hidden="true"><path className="axis" d="M10 45 H410"/><path d={kind==="ac-wave"?"M10 45 C45 0 80 0 115 45 S185 90 220 45 S290 0 325 45 S375 90 410 45":"M10 25 H410"}/></svg><small>{kind==="ac-wave"?"o valor atravessa o zero":"o valor mantém o mesmo sentido"}</small></div>;
  if(kind==="series-parallel")return <div className="question-visual mini-compare" role="img" aria-label="Circuito A com um percurso e circuito B com dois ramos"><MiniCircuit kind="series"/><MiniCircuit kind="parallel"/></div>;
  return <div className="question-visual circuit-question" role="img" aria-label={`Diagrama de circuito ${kind}`}><MiniCircuit kind={kind}/></div>
}
function MiniCircuit({kind}:{kind:"closed-circuit"|"open-circuit"|"series-open"|"parallel-open"|"series"|"parallel"}){const open=kind.includes("open");const parallel=kind.includes("parallel");if(parallel)return <div><b>{kind==="parallel"?"Circuito B":"Paralelo · L1 aberta"}</b><svg viewBox="0 0 360 150" aria-hidden="true"><path d="M30 25 H330 V125 H30 V25 M105 25 V52 M105 96 V125 M255 25 V125"/><circle className={open?"lamp-off":""} cx="105" cy="74" r="20"/><circle cx="255" cy="74" r="20"/><text x="94" y="80">L1</text><text x="244" y="80">L2</text><text x="38" y="116">Fonte</text></svg><small>{open?"Ramo L1 aberto · ramo L2 fechado":"Dois ramos entre os mesmos pontos"}</small></div>;return <div><b>{kind==="series"?"Circuito A":kind==="open-circuit"?"Interruptor aberto":"Série · L1 aberta"}</b><svg viewBox="0 0 360 130" aria-hidden="true"><path d={kind==="open-circuit"?"M30 25 H150 M185 25 H330 V105 H30 V25":"M30 25 H105 M150 25 H235 M275 25 H330 V105 H30 V25"}/>{kind==="open-circuit"?<><circle cx="150" cy="25" r="6"/><circle cx="185" cy="25" r="6"/><path d="M150 25 l27-18"/><circle cx="255" cy="65" r="19"/><text x="244" y="71">L</text></>:<><circle className={open?"lamp-off":""} cx="128" cy="25" r="20"/><circle cx="255" cy="25" r="20"/><text x="117" y="31">L1</text><text x="244" y="31">L2</text></>}<text x="38" y="97">Fonte</text></svg><small>{kind==="open-circuit"?"Existe uma interrupção no percurso":open?"Um único percurso interrompido":"Um único percurso"}</small></div>}

function Profile({user,data,resetProgress,onSignOut}:{user:User;data:Data;resetProgress:()=>void;onSignOut:()=>void}){const completed=data.completedLessons.filter(x=>x.startsWith("course-")).length;const rank=categories[Math.min(4,Math.floor(completed/10))];return <div className="page profile-page"><section className="profile-hero">{user.avatar?<img className="profile-avatar photo" src={user.avatar} alt="" referrerPolicy="no-referrer"/>:<div className="profile-avatar">{user.name[0]?.toUpperCase()||"A"}</div>}<div><span className="eyebrow">Perfil Voltz</span><h1>{user.name}</h1><p>{user.email} · progresso sincronizado na conta</p></div><button className="ghost-button profile-signout" onClick={onSignOut}>Terminar sessão</button></section><section className="stats-grid"><div><Zap/><strong>{data.xp}</strong><span>XP total</span></div><div><Award/><strong>{rank.name}</strong><span>Categoria atual</span></div><div><Trophy/><strong>{completed}/50</strong><span>Níveis</span></div></section><section className="progress-panel"><div className="section-head"><div><span className="eyebrow">Percurso sincronizado</span><h2>{rank.name} · {rank.role}</h2></div><span>{Math.round(completed/50*100)}%</span></div><Progress value={completed/50*100}/><p>O progresso fica ligado à tua conta e pode ser retomado noutro dispositivo.</p><button className="reset-progress" onClick={resetProgress}>Reiniciar progresso</button></section></div>}
