"use client";

import { useEffect, useMemo, useState } from "react";
import { Award, BookOpen, Check, ChevronRight, Flame, Gauge, Home, LockKeyhole, ShieldCheck, Sparkles, Star, Trophy, UserRound, X, Zap } from "lucide-react";
import { Progress } from "@/components/ui/progress";
import { allLevels, categories, type Check, type CourseLevel } from "./curriculum";

type View="percurso"|"manual"|"aula"|"desafio"|"perfil";
type User={name:string;email:string}|null;
type Data={xp:number;level:number;streak:number;completedLessons:string[]};
const initial:Data={xp:0,level:1,streak:0,completedLessons:[]};
const storageKey="voltz-progress-v1";
const asset=(name:string)=>`${import.meta.env.BASE_URL}${name}`;
const shuffle=<T,>(items:T[])=>{const out=[...items];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out};
const shuffleCheck=(item:Check)=>{const correct=item.options[item.answer];const options=shuffle([...item.options]) as [string,string,string];return {...item,options,answer:options.indexOf(correct)}};
const photos:Record<string,{src:string;alt:string;caption:string;credit:string;href:string}>={
  "aprendiz-1":{src:"https://www.foxvalleymetrology.com/wp-content/uploads/2025/08/img_3451-min-scaled.jpg",alt:"Multímetro digital com pontas de prova ligadas aos bornes corretos",caption:"V, A e Ω aparecem no seletor e nos bornes de um multímetro real",credit:"Fox Valley Metrology",href:"https://www.foxvalleymetrology.com/blog/how-to-use-a-multimeter/"},
  "aprendiz-2":{src:"https://bkpmedia.s3.us-west-1.amazonaws.com/downloads/kb_attachments/Ohms_Law.jpg",alt:"Circuito com fonte, resistência e corrente usado para explicar a Lei de Ohm",caption:"U, R e I representadas no mesmo circuito",credit:"B&K Precision",href:"https://www.bkprecision.com/knowledge/technical-notes/163/understanding-constant-voltage-cv-and-constant-current-cc-modes-in-regulated-power-supplies"},
  "ajudante-4":{src:"https://sawdustgirl.com/wp-content/uploads/2013/09/examine-extension-cords.jpg",alt:"Cabo elétrico com isolamento danificado",caption:"Inspeção real do isolamento de um cabo",credit:"Sawdust Girl",href:"https://sawdustgirl.com/extension-cord-safety/"},
  "tecnico-3":{src:"https://ozdenosgb.com/storage/blogs/kacak_akim.jpg",alt:"Interruptor diferencial num quadro elétrico",caption:"Identificação visual de um interruptor diferencial",credit:"Özden OSGB",href:"https://ozdenosgb.com/blog/kacak-akim-rolesi"},
  "ajudante-8":{src:"https://media.adeo.com/media/4758182/media.jpeg",alt:"Tomada elétrica exposta a humidade",caption:"O invólucro deve corresponder às influências externas",credit:"Leroy Merlin",href:"https://www.leroymerlin.pl/porady/instalacje/instalacja-elektryczna/zalana-instalacja-elektryczna-co-robic.html"},
};
const manualChapters=[
  {title:"O mapa da eletricidade",tag:"Começa aqui",text:"Antes das fórmulas, fixa quatro ideias: uma fonte cria tensão, um percurso fechado permite corrente, a carga transforma energia e a proteção limita as consequências de um defeito.",detail:"Imagina a tensão como a diferença que empurra as cargas, a corrente como a quantidade que atravessa o circuito e a resistência como a oposição encontrada. A analogia ajuda a começar, mas a eletricidade não é água: usa-a apenas para perceber a relação entre as grandezas.",points:["Tensão: diferença de potencial, medida em volt (V)","Corrente: movimento de carga, medido em ampere (A)","Resistência: oposição à corrente, medida em ohm (Ω)"],visual:"basics"},
  {title:"Fase, neutro e proteção",tag:"Condutores",text:"Numa alimentação monofásica, L é o condutor ativo, N pertence ao circuito funcional de retorno e PE é o condutor de proteção. PE não deve transportar corrente durante o funcionamento normal.",detail:"As cores ajudam a identificar, mas nunca são uma prova suficiente: instalações antigas, alterações ou erros podem não respeitar a convenção. A função deve ser confirmada pelo esquema, inspeção e procedimentos de verificação adequados. Em Portugal e na harmonização europeia, é comum encontrar castanho na fase, azul no neutro e verde/amarelo na proteção.",points:["L — fase: condutor ativo","N — neutro: condutor do circuito funcional","PE — proteção: caminho previsto para correntes de defeito"],visual:"conductors"},
  {title:"Como nasce um circuito",tag:"Percurso fechado",text:"Fonte, proteção, comando, carga e condutores formam uma cadeia funcional. Um interruptor aberto interrompe o percurso; quando fecha, a corrente pode circular e a carga transforma energia.",detail:"Exemplo: num ponto de luz, a proteção alimenta o circuito, o interruptor comanda o condutor ativo e a lâmpada é a carga. O neutro completa o circuito funcional e o PE protege as massas metálicas quando aplicável. Um circuito final é simplesmente o circuito que alimenta diretamente tomadas, iluminação ou outro equipamento de utilização.",points:["Proteção limita consequências de sobreintensidades","Comando abre ou fecha a alimentação da carga","Carga transforma energia elétrica em luz, calor ou movimento"],visual:"circuit"},
  {title:"Série e paralelo",tag:"Comparação visual",text:"Em série existe um único percurso e a mesma corrente atravessa os elementos. Em paralelo existem vários ramos e a tensão aplicada é comum a cada ramo.",detail:"Nas habitações, as cargas são normalmente ligadas em paralelo para receberem a tensão prevista e poderem funcionar de forma independente. Se uma lâmpada de um ramo for desligada, as outras podem continuar ligadas. Em série, abrir um ponto interrompe o único percurso.",points:["Série: um percurso e corrente comum","Paralelo: vários ramos e tensão comum","Cargas domésticas funcionam sobretudo em paralelo"],visual:"parallel"},
  {title:"Lei de Ohm sem medo",tag:"Cálculo",text:"A relação U = R × I descreve o comportamento de um elemento resistivo. Conhecendo duas grandezas, podes calcular a terceira, desde que uses unidades compatíveis.",detail:"Exemplo resolvido: uma resistência de 46 Ω ligada a 230 V conduz, no modelo simples, I = U ÷ R = 230 ÷ 46 = 5 A. Primeiro escreve os dados, depois escolhe a forma da fórmula, substitui os valores e confirma a unidade. O resultado é um cálculo didático; não autoriza escolher cabos ou proteções sem analisar as restantes condições.",points:["U em volt (V)","I em ampere (A)","R em ohm (Ω)"],visual:"ohm"},
  {title:"Potência e consumo",tag:"Energia",text:"Potência indica a rapidez com que a energia é transformada. Energia consumida depende da potência e do tempo de funcionamento.",detail:"Um equipamento de 1 kW ligado durante 2 horas utiliza 2 kWh. Um equipamento de 2 kW durante 1 hora também utiliza 2 kWh. kW indica potência; kWh indica energia acumulada. Em situações simples, P = U × I ajuda a relacionar potência, tensão e corrente, mas equipamentos reais podem exigir informação adicional.",points:["Potência: watt (W) ou quilowatt (kW)","Energia: quilowatt-hora (kWh)","Energia = potência × tempo"],visual:"power"},
  {title:"Proteções não são todas iguais",tag:"Quadro elétrico",text:"O disjuntor atua contra sobreintensidades; o diferencial deteta um desequilíbrio entre correntes nos condutores ativos. O PE e a ligação à terra integram o sistema de proteção.",detail:"Sobrecarga é corrente excessiva num circuito sem ligação direta de baixa impedância; curto-circuito é uma ligação de impedância muito baixa. Corrente residual é a diferença que indica que parte da corrente seguiu um caminho não previsto. Coordenação significa que condutores, terra e dispositivos devem funcionar em conjunto para desligar nas condições previstas.",points:["Disjuntor: sobrecarga e curto-circuito","Diferencial: desequilíbrio ou corrente residual","PE: caminho de proteção, não substitui o diferencial"],visual:"protection"},
  {title:"Como estudar no Voltz",tag:"Preparação final",text:"Lê o princípio, observa a imagem ou o esquema, explica por palavras tuas e resolve o exemplo antes de responder. Voltar atrás faz parte da aprendizagem.",detail:"Cada desafio tem 10 perguntas. A primeira resposta a cada pergunta conta para a nota e são necessárias 8 respostas certas para desbloquear o nível seguinte. Depois de um erro, recebes a resposta correta e uma explicação; podes repetir com as opções noutra posição, mas o erro continua registado. Os níveis ensinam conceitos e não autorizam trabalhos regulamentados.",points:["10 perguntas por nível, sobre a aula anterior","8 certas à primeira tentativa para avançar","Manual sempre disponível para consulta"],visual:"ready"},
];
const manualImages:Record<string,{src:string;alt:string;caption:string;href:string;credit:string}>={
  basics:{src:"https://cdn.tmi.yokogawa.com/1/9275/details/High%20Current%20Measurement_Components%20of%20Electrical%20Circuit_Yokogawa%20Test%20Measurement.png",alt:"Diagrama de tensão, corrente e resistência num circuito com lâmpada",caption:"Tensão, corrente e resistência no mesmo circuito",href:"https://tmi.yokogawa.com/us/library/resources/application-notes/high-current-measurement-application-note/",credit:"Yokogawa Test & Measurement"},
  circuit:{src:"https://miro.medium.com/v2/resize%3Afit%3A1092/1%2A294y_rkSNKBHIEUi3E110g.jpeg",alt:"Circuito simples com fonte, interruptor e lâmpada",caption:"Um percurso fechado entre fonte, comando e carga",href:"https://tasweeb.medium.com/electric-circuit-89338190e57b",credit:"Tasweeb Fatima"},
  parallel:{src:"https://www.benzoenergy.com/pub/media/blog/lithium_cells.jpg",alt:"Comparação real entre lâmpadas ligadas em série e em paralelo",caption:"Observa a diferença física entre os dois percursos",href:"https://www.benzoenergy.com/blog/post/how-to-connect-lithium-batteries-in-series-and-parallel.html",credit:"Benzo Energy"},
  ohm:{src:"https://www.electricalsafetyfirst.org.uk/media/1773/ohms-law.jpg",alt:"Diagrama circular com as fórmulas da Lei de Ohm",caption:"As três formas principais da Lei de Ohm",href:"https://www.electricalsafetyfirst.org.uk/ohms-law-calculator/",credit:"Electrical Safety First"},
  power:{src:"https://mr2.homeflow-assets.co.uk/files/site_asset/image/6498/8745/_x_/1st_image_accurate_meter_readings_Kilowatt_hour_single_stator_power_company_meter_Watthour_meter_of_electricity_for_use_in_home_appliance.png",alt:"Contador de energia elétrica com leitura em quilowatt-hora",caption:"O contador regista energia consumida em kWh",href:"https://www.lighthouse-property.co.uk/blog/market-update/how-to-take-accurate-meter-readings",credit:"Lighthouse Property"},
  protection:{src:"https://cenerg.ru/wp-content/uploads/2019/06/uzo-i-diff-avtomat2324354.jpg",alt:"Quadro elétrico com disjuntores e diferenciais identificados",caption:"Proteções instaladas e organizadas num quadro real",href:"https://cenerg.ru/articles/uzo-i-diff-avtomat-v-chem-raznica/",credit:"CentroEnergoEkspertiza"},
};
const categoryPhotos:Record<string,{src:string;alt:string;caption:string;credit:string;href:string}>={
  aprendiz:photos["aprendiz-1"],
  ajudante:photos["ajudante-4"],
  instalador:manualImages.circuit,
  tecnico:manualImages.protection,
  especialista:photos["aprendiz-1"],
};

export default function FullVoltzApp({user,signInPath,signOutPath}:{user:User;signInPath:string;signOutPath:string}){
  const [view,setView]=useState<View>("percurso");
  const [data,setData]=useState<Data>(initial);
  const [categoryIndex,setCategoryIndex]=useState(0);
  const [selected,setSelected]=useState(allLevels[0]);
  const [slide,setSlide]=useState(0);
  const [quiz,setQuiz]=useState<Check[]>([]);
  const [question,setQuestion]=useState(0);
  const [answer,setAnswer]=useState<number|null>(null);
  const [score,setScore]=useState(0);
  const [missedCurrent,setMissedCurrent]=useState(false);
  const [finished,setFinished]=useState(false);
  const [manualStep,setManualStep]=useState(0);
  useEffect(()=>{try{const saved=localStorage.getItem(storageKey);if(saved)setData(JSON.parse(saved))}catch{}},[]);
  async function save(next:Data){setData(next);try{localStorage.setItem(storageKey,JSON.stringify(next))}catch{}}
  const manualRead=data.completedLessons.includes("manual-iniciacao");
  const completedCount=data.completedLessons.filter(x=>x.startsWith("course-")).length;
  const currentIndex=Math.min(completedCount,allLevels.length-1);
  const isUnlocked=(id:string)=>manualRead&&allLevels.findIndex(x=>x.id===id)<=completedCount;
  function openLevel(level:typeof allLevels[number]){if(!isUnlocked(level.id))return;setSelected(level);setSlide(0);setView("aula")}
  function buildQuiz(level:typeof allLevels[number]){const others=shuffle(level.category.levels.filter(x=>x.id!==level.id));const objectives=others.map(x=>x.objective);const theories=others.map(x=>x.theory);const practices=others.map(x=>x.practice);const correctTheory=level.theory;const correctPractice=level.practice;const formula=level.formula||`Princípio: ${level.title}`;const checks:Check[]=[
    {q:`Qual é o objetivo do nível “${level.title}”?`,options:[level.objective,objectives[0],objectives[1]],answer:0,explanation:`O objetivo é ${level.objective.toLowerCase()}`},
    {q:`Que afirmação descreve corretamente “${level.title}”?`,options:[correctTheory,theories[0],theories[1]],answer:0,explanation:correctTheory},
    {q:"Qual destas tarefas aplica diretamente o que acabaste de aprender?",options:[correctPractice,practices[0],practices[1]],answer:0,explanation:`A aplicação proposta na aula é: ${correctPractice}`},
    {q:"Que relação ou princípio deves recordar neste nível?",options:[formula,others[0].formula||others[0].title,others[1].formula||others[1].title],answer:0,explanation:`A referência apresentada na aula é “${formula}”.`},
    {q:`Que par pertence ao mesmo nível?`,options:[`${level.title} — ${level.objective}`,`${level.title} — ${objectives[2]}`,`${others[2].title} — ${level.objective}`],answer:0,explanation:`“${level.title}” está ligado ao objetivo “${level.objective}”.`},
    {q:"Antes de escolher uma resposta, o que deves conseguir explicar?",options:[correctTheory,theories[2],theories[3]],answer:0,explanation:`A ideia essencial é: ${correctTheory}`},
    {q:"Qual é o exemplo prático correto para este conceito?",options:[correctPractice,practices[2],practices[3]],answer:0,explanation:`Este exemplo verifica o conceito: ${correctPractice}`},
    {q:`Qual destas sínteses corresponde a “${level.title}”?`,options:[`${level.objective} ${correctTheory}`,`${objectives[4]} ${theories[4]}`,`${objectives[5]} ${theories[5]}`],answer:0,explanation:`A síntese junta o objetivo e o princípio explicados nesta aula.`},
    {q:"Que evidência mostra que compreendeste este nível?",options:[`Conseguir explicar o princípio e aplicá-lo: ${correctPractice}`,`Memorizar apenas o título “${level.title}”`,`Escolher uma opção sem justificar`],answer:0,explanation:"Compreender significa explicar o princípio e aplicá-lo a um caso, não apenas memorizar."},
    {q:"Qual é a conclusão tecnicamente coerente com a aula?",options:[correctTheory,theories[6],theories[7]],answer:0,explanation:correctTheory}
  ];return shuffle(checks).map(shuffleCheck)}
  function startChallenge(){if(!manualRead){openManual();return}setQuiz(buildQuiz(selected));setQuestion(0);setAnswer(null);setScore(0);setMissedCurrent(false);setFinished(false);setView("desafio")}
  function choose(i:number){if(answer!==null)return;setAnswer(i);if(i===quiz[question].answer&&!missedCurrent)setScore(s=>s+1);if(i!==quiz[question].answer)setMissedCurrent(true)}
  function retryQuestion(){setQuiz(qs=>qs.map((x,i)=>i===question?shuffleCheck(x):x));setAnswer(null)}
  function nextQuestion(){if(question<quiz.length-1){setQuestion(q=>q+1);setAnswer(null);setMissedCurrent(false);return}const passed=score>=8;setFinished(true);if(passed&&!data.completedLessons.includes(`course-${selected.id}`)){const xp=data.xp+250;void save({...data,xp,level:Math.floor(xp/500)+1,completedLessons:[...data.completedLessons,`course-${selected.id}`]})}}
  function continueCourse(){const next=Math.min(allLevels.findIndex(x=>x.id===selected.id)+1,allLevels.length-1);setCategoryIndex(categories.findIndex(x=>x.id===allLevels[next].category.id));setView("percurso")}
  function openManual(){setManualStep(0);setView("manual")}
  function openCurrent(){if(!manualRead){openManual();return}const item=allLevels[currentIndex];setCategoryIndex(categories.findIndex(x=>x.id===item.category.id));openLevel(item)}
  function completeManual(){if(!manualRead)void save({...data,completedLessons:[...data.completedLessons,"manual-iniciacao"]});setView("percurso")}
  function resetProgress(){if(!window.confirm("Queres apagar todo o progresso guardado neste navegador?"))return;localStorage.removeItem(storageKey);setData(initial);setSelected(allLevels[0]);setCategoryIndex(0);setView("percurso")}
  const nav=(target:View)=>{if(target==="desafio")startChallenge();else setView(target)};
  return <div className="app-shell course-app">
    <aside className="sidebar"><button className="brand" onClick={()=>setView("percurso")}><span><Zap fill="currentColor"/></span>Voltz</button><nav><Nav active={view==="percurso"} icon={<Home/>} label="Percurso" onClick={()=>nav("percurso")}/><Nav active={view==="manual"} icon={<BookOpen/>} label="Manual" onClick={openManual}/><Nav active={view==="aula"} icon={<Gauge/>} label="Aula visual" onClick={openCurrent}/><Nav active={view==="desafio"} icon={<Trophy/>} label="Desafio" onClick={startChallenge}/><Nav active={view==="perfil"} icon={<UserRound/>} label="Perfil" onClick={()=>nav("perfil")}/></nav><div className="sidebar-foot"><ShieldCheck/> Formação introdutória baseada em prática portuguesa</div></aside>
    <main className="main"><header className="topbar"><div className="mobile-brand"><Zap fill="currentColor"/> Voltz</div><span className="version-badge">v2.1 · aulas em 6 passos</span><div className="stat flame"><Flame/><strong>{data.streak}</strong><span>dias</span></div><div className="stat"><Zap/><strong>{data.xp}</strong><span>XP</span></div><button className="avatar" aria-label="Abrir perfil" onClick={()=>setView("perfil")}>{user?.name?.[0]?.toUpperCase()||"A"}</button></header>
      {view==="percurso"&&<Journey data={data} user={user} signInPath={signInPath} categoryIndex={categoryIndex} setCategoryIndex={setCategoryIndex} openLevel={openLevel} openCurrent={openCurrent} openManual={openManual}/>} 
      {view==="manual"&&<Manual step={manualStep} setStep={setManualStep} done={manualRead} complete={completeManual}/>} 
      {view==="aula"&&<Lesson level={selected} slide={slide} setSlide={setSlide} startChallenge={startChallenge}/>} 
      {view==="desafio"&&<Challenge quiz={quiz.length?quiz:buildQuiz(selected)} question={question} answer={answer} score={score} finished={finished} choose={choose} retry={retryQuestion} next={nextQuestion} reset={startChallenge} continueCourse={continueCourse}/>} 
      {view==="perfil"&&<Profile user={user} data={data} signInPath={signInPath} signOutPath={signOutPath} resetProgress={resetProgress}/>} 
    </main>
    <nav className="mobile-nav five-items" aria-label="Navegação principal"><Nav active={view==="percurso"} icon={<Home/>} label="Percurso" onClick={()=>nav("percurso")}/><Nav active={view==="manual"} icon={<BookOpen/>} label="Manual" onClick={openManual}/><Nav active={view==="aula"} icon={<Gauge/>} label="Aula" onClick={openCurrent}/><Nav active={view==="desafio"} icon={<Trophy/>} label="Desafio" onClick={startChallenge}/><Nav active={view==="perfil"} icon={<UserRound/>} label="Perfil" onClick={()=>nav("perfil")}/></nav>
  </div>
}

function Nav({active,icon,label,onClick}:{active:boolean;icon:React.ReactNode;label:string;onClick:()=>void}){return <button className={`nav-item ${active?"active":""}`} onClick={onClick}>{icon}<span>{label}</span></button>}

function Journey({data,user,signInPath,categoryIndex,setCategoryIndex,openLevel,openCurrent,openManual}:{data:Data;user:User;signInPath:string;categoryIndex:number;setCategoryIndex:(n:number)=>void;openLevel:(l:typeof allLevels[number])=>void;openCurrent:()=>void;openManual:()=>void}){
  const category=categories[categoryIndex];const completed=data.completedLessons.filter(x=>x.startsWith("course-")).length;const manualRead=data.completedLessons.includes("manual-iniciacao");const percent=completed/50*100;
  return <div className="page journey-page full-journey">
    <section className="course-hero"><div><span className="eyebrow"><Sparkles/> Formação técnica progressiva</span><h1>{manualRead?"Da teoria ao diagnóstico.":"Primeiro, entende a base."}</h1><p>{manualRead?"50 níveis em cinco categorias, com explicações técnicas, aplicação e avaliação em cada etapa.":"Lê o Manual de Iniciação para aprenderes os termos e esquemas usados ao longo do curso."}</p><button className="primary-button" onClick={openCurrent}>{manualRead?`Continuar no nível ${Math.min(completed+1,50)}`:"Abrir manual"} <ChevronRight/></button></div><div className="course-meter"><strong>{completed}<small>/50</small></strong><span>níveis concluídos</span><Progress value={percent}/></div></section>
    <button className={`manual-entry ${manualRead?"done":"current"}`} onClick={openManual}><span>{manualRead?<Check/>:<BookOpen/>}</span><div><small>ETAPA OBRIGATÓRIA</small><strong>Manual de Iniciação Voltz</strong><p>{manualRead?"Manual lido · disponível para consulta a qualquer momento":"8 capítulos visuais · aprende os termos antes dos níveis"}</p></div><b>{manualRead?"Consultar":"Começar"}<ChevronRight/></b></button>
    <div className="category-tabs" role="tablist" aria-label="Categorias">{categories.map((c,i)=><button key={c.id} className={i===categoryIndex?"active":""} style={{"--cat":c.color} as React.CSSProperties} onClick={()=>setCategoryIndex(i)}><span>{i+1}</span><strong>{c.name}</strong><small>{c.role}</small></button>)}</div>
    <div className="section-head"><div><span className="eyebrow">Categoria {categoryIndex+1} de 5</span><h2>{category.name} · {category.role}</h2></div><span>{category.levels.filter(l=>data.completedLessons.includes(`course-${l.id}`)).length}/10</span></div>
    <section className="level-grid">{category.levels.map((level,i)=>{const global=allLevels.findIndex(x=>x.id===level.id);const done=data.completedLessons.includes(`course-${level.id}`);const unlocked=global<=completed;return <button key={level.id} className={`level-card ${done?"done":""} ${unlocked&&!done?"current":""}`} disabled={!unlocked} onClick={()=>openLevel({...level,category})}><span className="level-number">{done?<Check/>:unlocked?<Zap/>:<LockKeyhole/>}</span><span><small>Nível {i+1}</small><strong>{level.title}</strong><em>{done?"Concluído":unlocked?"Aula + 10 perguntas":"Bloqueado"}</em></span><ChevronRight/></button>})}</section>
    <p className="safety-note"><ShieldCheck/> Formação introdutória. A execução de instalações e responsabilidades profissionais em Portugal dependem das qualificações e regras aplicáveis.</p>
  </div>
}

function Manual({step,setStep,done,complete}:{step:number;setStep:(n:number)=>void;done:boolean;complete:()=>void}){
  const chapter=manualChapters[step];return <div className="page manual-page"><header className="manual-head"><div><span className="eyebrow"><BookOpen/> Manual de Iniciação</span><h1>Eletricidade explicada do zero</h1><p>Consulta livre · {done?"marcado como lido":"leitura obrigatória antes do nível 1"}</p></div>{done&&<span className="manual-done"><Check/> Manual lido</span>}</header>
    <div className="manual-progress"><div>{manualChapters.map((c,i)=><button key={c.title} className={`${i===step?"active":""} ${i<step||done?"read":""}`} onClick={()=>setStep(i)} aria-label={`Capítulo ${i+1}: ${c.title}`}>{i<step||done?<Check/>:i+1}</button>)}</div><Progress value={(step+1)/manualChapters.length*100}/></div>
    <article className="manual-sheet"><div className="manual-copy"><span className="eyebrow">Capítulo {step+1} · {chapter.tag}</span><h2>{chapter.title}</h2><p>{chapter.text}</p><p className="manual-detail">{chapter.detail}</p><ul>{chapter.points.map(point=><li key={point}><Check/>{point}</li>)}</ul><aside><ShieldCheck/><span><strong>Importante</strong>Este manual ensina conceitos e linguagem técnica. Trabalhos em instalações devem respeitar as regras aplicáveis e ser executados por pessoas qualificadas quando exigido.</span></aside></div><ManualDiagram kind={chapter.visual}/></article>
    <div className="manual-actions"><button className="ghost-button" disabled={step===0} onClick={()=>setStep(step-1)}>Anterior</button><span>{step+1} de {manualChapters.length}</span><button className="primary-button" onClick={()=>step<manualChapters.length-1?setStep(step+1):complete()}>{step<manualChapters.length-1?"Próximo capítulo":done?"Voltar ao percurso":"Marcar como lido"}<ChevronRight/></button></div>
    <footer className="manual-sources">Referência institucional: <a href="https://www.dgeg.gov.pt/pt/areas-setoriais/energia/energia-eletrica/atividade-normativa/cte-64/" target="_blank" rel="noreferrer">DGEG · CTE 64</a> e <a href="https://www.dgeg.gov.pt/pt/areas-setoriais/energia/energia-eletrica/instalacoes-de-utilizacao-de-energia-eletrica/instalacoes-eletricas-de-servico-particular-tipo-a-b-e-c/" target="_blank" rel="noreferrer">instalações elétricas de serviço particular</a>.</footer>
  </div>
}

function ManualDiagram({kind}:{kind:string}){
  const image=manualImages[kind];if(image)return <figure className="manual-diagram manual-photo"><img src={image.src} alt={image.alt}/><figcaption><strong>{image.caption}</strong><a href={image.href} target="_blank" rel="noreferrer">Imagem: {image.credit}</a></figcaption></figure>;
  if(kind==="conductors")return <div className="manual-diagram conductors" role="img" aria-label="Esquema dos condutores fase L, neutro N e proteção PE"><h3>Função dos condutores</h3><div><span className="brown">L</span><b>Fase</b> condutor ativo</div><div><span className="blue-dot">N</span><b>Neutro</b> circuito funcional</div><div><span className="earth">PE</span><b>Proteção</b> corrente de defeito</div><p>As cores ajudam, mas confirma sempre a função pelo esquema e por verificação adequada.</p></div>;
  return <div className="manual-diagram ready-card"><img src={asset("faisca-mobile.webp")} alt="Faísca, mascote do Voltz"/><h3>Agora já falamos a mesma língua.</h3><p>Segue para Aprendiz · Nível 1.</p></div>;
}

function Lesson({level,slide,setSlide,startChallenge}:{level:typeof allLevels[number];slide:number;setSlide:(n:number)=>void;startChallenge:()=>void}){
  const photo=photos[level.id]||categoryPhotos[level.category.id];
  const worked=level.id==="aprendiz-2"?"Exemplo resolvido: U = 230 V e R = 46 Ω. Aplicamos I = U ÷ R. Logo, I = 230 ÷ 46 = 5 A. Antes de calcular, confirma sempre as unidades.":level.formula?`Usa ${level.formula} apenas depois de identificares os dados, as unidades e a grandeza desconhecida. Escreve cada passo e confirma se o resultado é plausível.`:`Começa por identificar a situação, o princípio envolvido e o resultado esperado. Só depois aplica: ${level.practice}`;
  const slides=[
    {tag:"1 · Objetivo",title:level.title,text:`No fim desta aula deves conseguir ${level.objective.toLowerCase()} Não precisas de decorar tudo: procura compreender o que muda, o que se mantém e porquê.`,kind:"target"},
    {tag:"2 · Vocabulário",title:"Palavras que vais usar",text:`O tema é “${level.title}”. Lê o objetivo com calma e identifica as grandezas, componentes ou ações mencionadas. Quando surgir um termo novo, relaciona-o com a função que desempenha no circuito.`,kind:"theory"},
    {tag:"3 · Princípio",title:"Como funciona",text:`${level.theory} Este é o princípio que deves conseguir explicar por palavras tuas antes de avançar para o exercício.`,kind:"theory"},
    {tag:"4 · Exemplo guiado",title:"Vamos raciocinar",text:worked,kind:"practice"},
    {tag:"5 · Observação",title:"Reconhece na prática",text:`${level.practice} Observa os elementos, identifica a função de cada um e não tires conclusões apenas pela cor ou pela aparência.`,kind:"practice"},
    {tag:"6 · Verificação",title:"O que tens de dominar",text:`Deves conseguir explicar ${level.title.toLowerCase()}, relacionar o conceito com o exemplo e justificar uma decisão. O desafio seguinte avalia apenas estas ideias desta aula.`,kind:"check"}
  ];const item=slides[slide];
  return <div className="page lesson-page"><div className="lesson-top"><button onClick={()=>setSlide(0)} aria-label="Voltar ao início"><X/></button><Progress value={(slide+1)/slides.length*100}/><span>{slide+1}/{slides.length}</span></div><section className="lesson-card technical-lesson"><div className={`lesson-visual tech-${item.kind}`}>{photo&&slide===4?<figure className="real-photo"><img src={photo.src} alt={photo.alt}/><figcaption><span><ShieldCheck/> {photo.caption}</span><a href={photo.href} target="_blank" rel="noreferrer">Imagem: {photo.credit}</a></figcaption></figure>:<div className="tech-visual"><span>{item.kind==="target"?<Gauge/>:item.kind==="theory"?<Zap/>:item.kind==="practice"?<BookOpen/>:<Check/>}</span><small>{level.category.name} · Nível {level.category.levels.findIndex(x=>x.id===level.id)+1} · 2–5 min</small>{level.formula&&<strong>{level.formula}</strong>}</div>}</div><div className="lesson-copy"><span className="eyebrow">{item.tag}</span><h1>{item.title}</h1><p>{item.text}</p><div className="faisca-note"><img src={asset("faisca-mobile.webp")} width="62" height="80" alt="Faísca, mascote do Voltz"/><span><strong>Dica da Faísca</strong>{slide===5?"Se não conseguires justificar a resposta, volta ao princípio e ao exemplo guiado.":"Compreende o princípio antes de memorizar o procedimento."}</span></div></div></section><div className="lesson-actions"><button className="ghost-button" disabled={slide===0} onClick={()=>setSlide(slide-1)}>Anterior</button><button className="primary-button" onClick={()=>slide<slides.length-1?setSlide(slide+1):startChallenge()}>{slide<slides.length-1?"Continuar":"Fazer 10 perguntas"}<ChevronRight/></button></div></div>
}

function Challenge({quiz,question,answer,score,finished,choose,retry,next,reset,continueCourse}:{quiz:Check[];question:number;answer:number|null;score:number;finished:boolean;choose:(i:number)=>void;retry:()=>void;next:()=>void;reset:()=>void;continueCourse:()=>void}){
  const passed=score>=8;if(finished)return <div className="page result-page"><div className="result-card"><div className="trophy"><Trophy/></div><span className="eyebrow">Avaliação concluída</span><h1>{passed?"Nível dominado!":"Revê e tenta novamente"}</h1><p>Acertaste {score} de 10 à primeira tentativa. {passed?"O nível seguinte foi desbloqueado.":"São necessárias 8 respostas certas à primeira tentativa."}</p><div className="reward-row"><div><Zap/><strong>+{passed?250:0}</strong><span>XP</span></div><div><Star/><strong>{score}/10</strong><span>primeiras tentativas</span></div></div><div className="result-actions">{passed&&<button className="primary-button" onClick={continueCourse}>Continuar percurso <ChevronRight/></button>}<button className={passed?"ghost-button":"primary-button"} onClick={reset}>Novo desafio</button></div></div></div>;
  const item=quiz[question];const correct=answer===item.answer;return <div className="page challenge-page"><div className="challenge-head"><span className="eyebrow">Pergunta {question+1} de 10</span><h1>{item.q}</h1><p>A primeira resposta conta para a nota. Depois de um erro podes rever e tentar novamente.</p></div><div className="option-list">{item.options.map((text,i)=><button key={`${text}-${i}`} onClick={()=>choose(i)} className={`option ${answer!==null&&i===item.answer?"correct":""} ${answer===i&&i!==item.answer?"wrong":""}`}><span>{String.fromCharCode(65+i)}</span><strong>{text}</strong>{answer!==null&&i===item.answer&&<Check/>}{answer===i&&i!==item.answer&&<X/>}</button>)}</div>{answer!==null&&<div className={`feedback ${correct?"positive":"negative"}`}><div><strong>{correct?"Correto.":"Ainda não. Revê a explicação."}</strong><span>{correct?(item.explanation||"A resposta corresponde ao princípio apresentado na aula."):`Resposta correta: ${item.options[item.answer]}. ${item.explanation||"Volta ao princípio técnico da aula e compara cada opção."} As opções serão baralhadas, mas este erro continua registado na nota.`}</span></div><button className="primary-button" onClick={correct?next:retry}>{correct?(question<9?"Próxima":"Ver resultado"):"Tentar novamente"}<ChevronRight/></button></div>}</div>
}

function Profile({data,resetProgress}:{user:User;data:Data;signInPath:string;signOutPath:string;resetProgress:()=>void}){const name="Aprendiz";const completed=data.completedLessons.filter(x=>x.startsWith("course-")).length;const rank=categories[Math.min(4,Math.floor(completed/10))];return <div className="page profile-page"><section className="profile-hero"><div className="profile-avatar">A</div><div><span className="eyebrow">Perfil Voltz</span><h1>{name}</h1><p>Progresso guardado neste dispositivo.</p></div></section><section className="stats-grid"><div><Zap/><strong>{data.xp}</strong><span>XP total</span></div><div><Award/><strong>{rank.name}</strong><span>Categoria atual</span></div><div><Trophy/><strong>{completed}/50</strong><span>Níveis</span></div></section><section className="progress-panel"><div className="section-head"><div><span className="eyebrow">Percurso técnico</span><h2>{rank.name} · {rank.role}</h2></div><span>{Math.round(completed/50*100)}%</span></div><Progress value={completed/50*100}/><p>O progresso fica guardado automaticamente neste navegador.</p><button className="reset-progress" onClick={resetProgress}>Reiniciar progresso</button></section></div>}
