"use client";

import { useEffect, useMemo, useState } from "react";
import { Award, BookOpen, Check, ChevronRight, Flame, Gauge, Home, LockKeyhole, ShieldCheck, Sparkles, Star, Trophy, UserRound, X, Zap } from "lucide-react";
import { Progress } from "@/components/ui/progress";
import { allLevels, categories, type Check, type CourseLevel } from "./curriculum";

type View="percurso"|"manual"|"aula"|"desafio"|"perfil";
type User={name:string;email:string}|null;
type Data={xp:number;level:number;streak:number;completedLessons:string[]};
const initial:Data={xp:0,level:1,streak:0,completedLessons:[]};
const storageKey="voltz-progress-v1";
const shuffle=<T,>(items:T[])=>{const out=[...items];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out};
const shuffleCheck=(item:Check)=>{const correct=item.options[item.answer];const options=shuffle([...item.options]) as [string,string,string];return {...item,options,answer:options.indexOf(correct)}};
const photos:Record<string,{src:string;alt:string;caption:string;credit:string;href:string}>={
  "ajudante-4":{src:"https://sawdustgirl.com/wp-content/uploads/2013/09/examine-extension-cords.jpg",alt:"Cabo elétrico com isolamento danificado",caption:"Inspeção real do isolamento de um cabo",credit:"Sawdust Girl",href:"https://sawdustgirl.com/extension-cord-safety/"},
  "tecnico-3":{src:"https://ozdenosgb.com/storage/blogs/kacak_akim.jpg",alt:"Interruptor diferencial num quadro elétrico",caption:"Identificação visual de um interruptor diferencial",credit:"Özden OSGB",href:"https://ozdenosgb.com/blog/kacak-akim-rolesi"},
  "ajudante-8":{src:"https://media.adeo.com/media/4758182/media.jpeg",alt:"Tomada elétrica exposta a humidade",caption:"O invólucro deve corresponder às influências externas",credit:"Leroy Merlin",href:"https://www.leroymerlin.pl/porady/instalacje/instalacja-elektryczna/zalana-instalacja-elektryczna-co-robic.html"},
};
const manualChapters=[
  {title:"O mapa da eletricidade",tag:"Começa aqui",text:"Antes das fórmulas, fixa quatro ideias: uma fonte cria tensão, um percurso fechado permite corrente, a carga transforma energia e a proteção limita consequências de defeitos.",points:["Tensão: diferença de potencial, medida em volt","Corrente: fluxo de carga, medido em ampere","Resistência: oposição à corrente, medida em ohm"],visual:"basics"},
  {title:"Fase, neutro e proteção",tag:"Condutores",text:"Numa alimentação monofásica, L é o condutor ativo, N pertence ao circuito de retorno do sistema e PE é o condutor de proteção. A função deve ser confirmada pelo esquema e por procedimentos adequados, não apenas pela cor.",points:["L — condutor de fase","N — condutor neutro","PE — condutor de proteção"],visual:"conductors"},
  {title:"Como nasce um circuito",tag:"Percurso fechado",text:"Fonte, proteção, comando, carga e condutores formam uma cadeia funcional. Se o percurso estiver aberto, a carga não recebe corrente; quando fecha, existe circulação conforme as características do circuito.",points:["Proteção antes do circuito final","Comando atua sobre a alimentação da carga","A carga transforma energia elétrica"],visual:"circuit"},
  {title:"Série e paralelo",tag:"Comparação visual",text:"Em série existe um único percurso e a corrente é comum aos elementos. Em paralelo existem ramos: a tensão é comum a cada ramo e as cargas podem funcionar de forma independente.",points:["Série: um percurso","Paralelo: vários ramos","Habitações usam sobretudo cargas em paralelo"],visual:"parallel"},
  {title:"Lei de Ohm sem medo",tag:"Cálculo",text:"A relação U = R × I ajuda a prever o comportamento de elementos resistivos. Se conheces duas grandezas, podes calcular a terceira respeitando as unidades.",points:["U em volt (V)","I em ampere (A)","R em ohm (Ω)"],visual:"ohm"},
  {title:"Potência e consumo",tag:"Energia",text:"Potência indica a rapidez com que a energia é transformada. O consumo depende da potência e do tempo: um equipamento de 1 kW durante 2 horas utiliza 2 kWh.",points:["P = U × I em condições simples","Energia = potência × tempo","kW não é o mesmo que kWh"],visual:"power"},
  {title:"Proteções não são todas iguais",tag:"Quadro elétrico",text:"Disjuntores atuam contra sobreintensidades; diferenciais detetam desequilíbrios de corrente residual. A ligação à terra e a coordenação das proteções fazem parte do sistema.",points:["Disjuntor: sobrecarga e curto-circuito","Diferencial: corrente residual","PE: caminho de proteção"],visual:"protection"},
  {title:"Como estudar no Voltz",tag:"Preparação final",text:"Lê o princípio, observa o esquema, explica por palavras tuas e só depois responde. Os níveis ensinam conceitos, mas não autorizam a execução de trabalhos regulamentados.",points:["10 perguntas por nível","8 certas para avançar","Podes consultar este manual quando quiseres"],visual:"ready"},
];
const manualImages:Record<string,{src:string;alt:string;caption:string;href:string;credit:string}>={
  basics:{src:"https://cdn.tmi.yokogawa.com/1/9275/details/High%20Current%20Measurement_Components%20of%20Electrical%20Circuit_Yokogawa%20Test%20Measurement.png",alt:"Diagrama de tensão, corrente e resistência num circuito com lâmpada",caption:"Tensão, corrente e resistência no mesmo circuito",href:"https://tmi.yokogawa.com/us/library/resources/application-notes/high-current-measurement-application-note/",credit:"Yokogawa Test & Measurement"},
  conductors:{src:"https://images.saymedia-content.com/.image/t_share/MTkyOTI5MjkzMTMzNjg1OTgx/wiring-a-uk-plug.jpg",alt:"Condutores castanho, azul e verde amarelo identificados",caption:"Identificação visual de fase, neutro e proteção",href:"https://storage.googleapis.com/dizoyfqahpyyle/what-is-blue-and-yellow-wire.html",credit:"SayMedia"},
  circuit:{src:"https://miro.medium.com/v2/resize%3Afit%3A1092/1%2A294y_rkSNKBHIEUi3E110g.jpeg",alt:"Circuito simples com fonte, interruptor e lâmpada",caption:"Um percurso fechado entre fonte, comando e carga",href:"https://tasweeb.medium.com/electric-circuit-89338190e57b",credit:"Tasweeb Fatima"},
  parallel:{src:"https://www.benzoenergy.com/pub/media/blog/lithium_cells.jpg",alt:"Comparação real entre lâmpadas ligadas em série e em paralelo",caption:"Observa a diferença física entre os dois percursos",href:"https://www.benzoenergy.com/blog/post/how-to-connect-lithium-batteries-in-series-and-parallel.html",credit:"Benzo Energy"},
  ohm:{src:"https://www.electricalsafetyfirst.org.uk/media/1773/ohms-law.jpg",alt:"Diagrama circular com as fórmulas da Lei de Ohm",caption:"As três formas principais da Lei de Ohm",href:"https://www.electricalsafetyfirst.org.uk/ohms-law-calculator/",credit:"Electrical Safety First"},
  power:{src:"https://mr2.homeflow-assets.co.uk/files/site_asset/image/6498/8745/_x_/1st_image_accurate_meter_readings_Kilowatt_hour_single_stator_power_company_meter_Watthour_meter_of_electricity_for_use_in_home_appliance.png",alt:"Contador de energia elétrica com leitura em quilowatt-hora",caption:"O contador regista energia consumida em kWh",href:"https://www.lighthouse-property.co.uk/blog/market-update/how-to-take-accurate-meter-readings",credit:"Lighthouse Property"},
  protection:{src:"https://cenerg.ru/wp-content/uploads/2019/06/uzo-i-diff-avtomat2324354.jpg",alt:"Quadro elétrico com disjuntores e diferenciais identificados",caption:"Proteções instaladas e organizadas num quadro real",href:"https://cenerg.ru/articles/uzo-i-diff-avtomat-v-chem-raznica/",credit:"CentroEnergoEkspertiza"},
};

export default function FullVoltzApp({user,signInPath,signOutPath}:{user:User;signInPath:string;signOutPath:string}){
  const [view,setView]=useState<View>("percurso");
  const [data,setData]=useState<Data>(initial);
  const [categoryIndex,setCategoryIndex]=useState(0);
  const [selected,setSelected]=useState(allLevels[0]);
  const [slide,setSlide]=useState(0);
  const [quiz,setQuiz]=useState<Check[]>([]);
  const [question,setQuestion]=useState(0);
  const [answer,setAnswer]=useState<number|null>(null);
  const [score,setScore]=useState(0);
  const [finished,setFinished]=useState(false);
  const [manualStep,setManualStep]=useState(0);
  useEffect(()=>{try{const saved=localStorage.getItem(storageKey);if(saved)setData(JSON.parse(saved))}catch{}},[]);
  async function save(next:Data){setData(next);try{localStorage.setItem(storageKey,JSON.stringify(next))}catch{}}
  const manualRead=data.completedLessons.includes("manual-iniciacao");
  const completedCount=data.completedLessons.filter(x=>x.startsWith("course-")).length;
  const currentIndex=Math.min(completedCount,allLevels.length-1);
  const isUnlocked=(id:string)=>manualRead&&allLevels.findIndex(x=>x.id===id)<=completedCount;
  function openLevel(level:typeof allLevels[number]){if(!isUnlocked(level.id))return;setSelected(level);setSlide(0);setView("aula")}
  function buildQuiz(level:typeof allLevels[number]){const others=level.category.levels.filter(x=>x.id!==level.id);const levelCheck:Check={q:`Qual é o objetivo principal do nível “${level.title}”?`,options:[level.objective,...shuffle(others).slice(0,2).map(x=>x.objective)] as [string,string,string],answer:0};return shuffle([levelCheck,...level.category.checks]).slice(0,10).map(shuffleCheck)}
  function startChallenge(){if(!manualRead){openManual();return}setQuiz(buildQuiz(selected));setQuestion(0);setAnswer(null);setScore(0);setFinished(false);setView("desafio")}
  function choose(i:number){if(answer!==null)return;setAnswer(i);if(i===quiz[question].answer)setScore(s=>s+1)}
  function retryQuestion(){setQuiz(qs=>qs.map((x,i)=>i===question?shuffleCheck(x):x));setAnswer(null)}
  function nextQuestion(){if(question<quiz.length-1){setQuestion(q=>q+1);setAnswer(null);return}const passed=score>=8;setFinished(true);if(passed&&!data.completedLessons.includes(`course-${selected.id}`)){const xp=data.xp+250;void save({...data,xp,level:Math.floor(xp/500)+1,completedLessons:[...data.completedLessons,`course-${selected.id}`]})}}
  function continueCourse(){const next=Math.min(allLevels.findIndex(x=>x.id===selected.id)+1,allLevels.length-1);setCategoryIndex(categories.findIndex(x=>x.id===allLevels[next].category.id));setView("percurso")}
  function openManual(){setManualStep(0);setView("manual")}
  function openCurrent(){if(!manualRead){openManual();return}const item=allLevels[currentIndex];setCategoryIndex(categories.findIndex(x=>x.id===item.category.id));openLevel(item)}
  function completeManual(){if(!manualRead)void save({...data,completedLessons:[...data.completedLessons,"manual-iniciacao"]});setView("percurso")}
  const nav=(target:View)=>{if(target==="desafio")startChallenge();else setView(target)};
  return <div className="app-shell course-app">
    <aside className="sidebar"><button className="brand" onClick={()=>setView("percurso")}><span><Zap fill="currentColor"/></span>Voltz</button><nav><Nav active={view==="percurso"} icon={<Home/>} label="Percurso" onClick={()=>nav("percurso")}/><Nav active={view==="manual"} icon={<BookOpen/>} label="Manual" onClick={openManual}/><Nav active={view==="aula"} icon={<Gauge/>} label="Aula visual" onClick={openCurrent}/><Nav active={view==="desafio"} icon={<Trophy/>} label="Desafio" onClick={startChallenge}/><Nav active={view==="perfil"} icon={<UserRound/>} label="Perfil" onClick={()=>nav("perfil")}/></nav><div className="sidebar-foot"><ShieldCheck/> Formação introdutória baseada em prática portuguesa</div></aside>
    <main className="main"><header className="topbar"><div className="mobile-brand"><Zap fill="currentColor"/> Voltz</div><div className="stat flame"><Flame/><strong>{data.streak}</strong><span>dias</span></div><div className="stat"><Zap/><strong>{data.xp}</strong><span>XP</span></div><button className="avatar" onClick={()=>setView("perfil")}>{user?.name?.[0]?.toUpperCase()||"A"}</button></header>
      {view==="percurso"&&<Journey data={data} user={user} signInPath={signInPath} categoryIndex={categoryIndex} setCategoryIndex={setCategoryIndex} openLevel={openLevel} openCurrent={openCurrent} openManual={openManual}/>} 
      {view==="manual"&&<Manual step={manualStep} setStep={setManualStep} done={manualRead} complete={completeManual}/>} 
      {view==="aula"&&<Lesson level={selected} slide={slide} setSlide={setSlide} startChallenge={startChallenge}/>} 
      {view==="desafio"&&<Challenge quiz={quiz.length?quiz:buildQuiz(selected)} question={question} answer={answer} score={score} finished={finished} choose={choose} retry={retryQuestion} next={nextQuestion} reset={startChallenge} continueCourse={continueCourse}/>} 
      {view==="perfil"&&<Profile user={user} data={data} signInPath={signInPath} signOutPath={signOutPath}/>} 
    </main>
    <nav className="mobile-nav five-items" aria-label="Navegação principal"><Nav active={view==="percurso"} icon={<Home/>} label="Percurso" onClick={()=>nav("percurso")}/><Nav active={view==="manual"} icon={<BookOpen/>} label="Manual" onClick={openManual}/><Nav active={view==="aula"} icon={<Gauge/>} label="Aula" onClick={openCurrent}/><Nav active={view==="desafio"} icon={<Trophy/>} label="Desafio" onClick={startChallenge}/><Nav active={view==="perfil"} icon={<UserRound/>} label="Perfil" onClick={()=>nav("perfil")}/></nav>
  </div>
}

function Nav({active,icon,label,onClick}:{active:boolean;icon:React.ReactNode;label:string;onClick:()=>void}){return <button className={`nav-item ${active?"active":""}`} onClick={onClick}>{icon}<span>{label}</span></button>}

function Journey({data,user,signInPath,categoryIndex,setCategoryIndex,openLevel,openCurrent,openManual}:{data:Data;user:User;signInPath:string;categoryIndex:number;setCategoryIndex:(n:number)=>void;openLevel:(l:typeof allLevels[number])=>void;openCurrent:()=>void;openManual:()=>void}){
  const category=categories[categoryIndex];const completed=data.completedLessons.filter(x=>x.startsWith("course-")).length;const manualRead=data.completedLessons.includes("manual-iniciacao");const percent=completed/50*100;
  return <div className="page journey-page full-journey">
    <section className="course-hero"><div><span className="eyebrow"><Sparkles/> Formação técnica progressiva</span><h1>{manualRead?"Da teoria ao diagnóstico.":"Primeiro, entende a base."}</h1><p>{manualRead?"50 níveis em cinco categorias, com explicações técnicas, aplicação e avaliação em cada etapa.":"Lê o Manual de Iniciação para aprenderes os termos e esquemas usados ao longo do curso."}</p><button className="primary-button" onClick={openCurrent}>{manualRead?`Continuar no nível ${Math.min(completed+1,50)}`:"Abrir manual"} <ChevronRight/></button></div><div className="course-meter"><strong>{completed}<small>/50</small></strong><span>níveis concluídos</span><Progress value={percent}/></div></section>
    <button className={`manual-entry ${manualRead?"done":"current"}`} onClick={openManual}><span>{manualRead?<Check/>:<BookOpen/>}</span><div><small>ETAPA OBRIGATÓRIA</small><strong>Manual de Iniciação Voltz</strong><p>{manualRead?"Manual lido · disponível para consulta a qualquer momento":"8 capítulos visuais · aprende os termos antes dos níveis"}</p></div><b>{manualRead?"Consultar":"Começar"}<ChevronRight/></b></button>
    <div className="category-tabs" role="tablist" aria-label="Categorias">{categories.map((c,i)=><button key={c.id} className={i===categoryIndex?"active":""} style={{"--cat":c.color} as React.CSSProperties} onClick={()=>setCategoryIndex(i)}><span>{i+1}</span><strong>{c.name}</strong><small>{c.role}</small></button>)}</div>
    <div className="section-head"><div><span className="eyebrow">Categoria {categoryIndex+1} de 5</span><h2>{category.name} · {category.role}</h2></div><span>{category.levels.filter(l=>data.completedLessons.includes(`course-${l.id}`)).length}/10</span></div>
    <section className="level-grid">{category.levels.map((level,i)=>{const global=allLevels.findIndex(x=>x.id===level.id);const done=data.completedLessons.includes(`course-${level.id}`);const unlocked=global<=completed;return <button key={level.id} className={`level-card ${done?"done":""} ${unlocked&&!done?"current":""}`} disabled={!unlocked} onClick={()=>openLevel({...level,category})}><span className="level-number">{done?<Check/>:unlocked?<Zap/>:<LockKeyhole/>}</span><span><small>Nível {i+1}</small><strong>{level.title}</strong><em>{done?"Concluído":unlocked?"Aula + 10 perguntas":"Bloqueado"}</em></span><ChevronRight/></button>})}</section>
    <p className="safety-note"><ShieldCheck/> Formação introdutória. A execução de instalações e responsabilidades profissionais em Portugal dependem das qualificações e regras aplicáveis.</p>
  </div>
}

function Manual({step,setStep,done,complete}:{step:number;setStep:(n:number)=>void;done:boolean;complete:()=>void}){
  const chapter=manualChapters[step];return <div className="page manual-page"><header className="manual-head"><div><span className="eyebrow"><BookOpen/> Manual de Iniciação</span><h1>Eletricidade explicada do zero</h1><p>Consulta livre · {done?"marcado como lido":"leitura obrigatória antes do nível 1"}</p></div>{done&&<span className="manual-done"><Check/> Manual lido</span>}</header>
    <div className="manual-progress"><div>{manualChapters.map((c,i)=><button key={c.title} className={`${i===step?"active":""} ${i<step||done?"read":""}`} onClick={()=>setStep(i)} aria-label={`Capítulo ${i+1}: ${c.title}`}>{i<step||done?<Check/>:i+1}</button>)}</div><Progress value={(step+1)/manualChapters.length*100}/></div>
    <article className="manual-sheet"><div className="manual-copy"><span className="eyebrow">Capítulo {step+1} · {chapter.tag}</span><h2>{chapter.title}</h2><p>{chapter.text}</p><ul>{chapter.points.map(point=><li key={point}><Check/>{point}</li>)}</ul><aside><ShieldCheck/><span><strong>Importante</strong>Este manual ensina conceitos e linguagem técnica. Trabalhos em instalações devem respeitar as regras aplicáveis e ser executados por pessoas qualificadas quando exigido.</span></aside></div><ManualDiagram kind={chapter.visual}/></article>
    <div className="manual-actions"><button className="ghost-button" disabled={step===0} onClick={()=>setStep(step-1)}>Anterior</button><span>{step+1} de {manualChapters.length}</span><button className="primary-button" onClick={()=>step<manualChapters.length-1?setStep(step+1):complete()}>{step<manualChapters.length-1?"Próximo capítulo":done?"Voltar ao percurso":"Marcar como lido"}<ChevronRight/></button></div>
    <footer className="manual-sources">Referência institucional: <a href="https://www.dgeg.gov.pt/pt/areas-setoriais/energia/energia-eletrica/atividade-normativa/cte-64/" target="_blank" rel="noreferrer">DGEG · CTE 64</a> e <a href="https://www.dgeg.gov.pt/pt/areas-setoriais/energia/energia-eletrica/instalacoes-de-utilizacao-de-energia-eletrica/instalacoes-eletricas-de-servico-particular-tipo-a-b-e-c/" target="_blank" rel="noreferrer">instalações elétricas de serviço particular</a>.</footer>
  </div>
}

function ManualDiagram({kind}:{kind:string}){
  const image=manualImages[kind];if(image)return <figure className="manual-diagram manual-photo"><img src={image.src} alt={image.alt}/><figcaption><strong>{image.caption}</strong><a href={image.href} target="_blank" rel="noreferrer">Imagem: {image.credit}</a></figcaption></figure>;
  return <div className="manual-diagram ready-card"><img src="/faisca-mobile.webp" alt="Faísca, mascote do Voltz"/><h3>Agora já falamos a mesma língua.</h3><p>Segue para Aprendiz · Nível 1.</p></div>;
}

function Lesson({level,slide,setSlide,startChallenge}:{level:typeof allLevels[number];slide:number;setSlide:(n:number)=>void;startChallenge:()=>void}){
  const photo=photos[level.id];const slides=[{tag:"Objetivo",title:level.title,text:level.objective,kind:"target"},{tag:"Conceito técnico",title:"Como funciona",text:level.theory,kind:"theory"},{tag:"Aplicação",title:"Na prática",text:level.practice,kind:"practice"},{tag:"Síntese",title:"O que tens de dominar",text:`Consegue explicar ${level.title.toLowerCase()}, interpretar o princípio e aplicá-lo num exercício antes de avançar.`,kind:"check"}];const item=slides[slide];
  return <div className="page lesson-page"><div className="lesson-top"><button onClick={()=>setSlide(0)} aria-label="Voltar ao início"><X/></button><Progress value={(slide+1)/slides.length*100}/><span>{slide+1}/{slides.length}</span></div><section className="lesson-card technical-lesson"><div className={`lesson-visual tech-${item.kind}`}>{photo&&slide===2?<figure className="real-photo"><img src={photo.src} alt={photo.alt}/><figcaption><span><ShieldCheck/> {photo.caption}</span><a href={photo.href} target="_blank" rel="noreferrer">Fotografia: {photo.credit}</a></figcaption></figure>:<div className="tech-visual"><span>{item.kind==="target"?<Gauge/>:item.kind==="theory"?<Zap/>:item.kind==="practice"?<BookOpen/>:<Check/>}</span><small>{level.category.name} · Nível {level.category.levels.findIndex(x=>x.id===level.id)+1}</small>{level.formula&&<strong>{level.formula}</strong>}</div>}</div><div className="lesson-copy"><span className="eyebrow">{item.tag}</span><h1>{item.title}</h1><p>{item.text}</p><div className="faisca-note"><img src="/faisca-mobile.webp" width="62" height="80" alt="Faísca"/><span><strong>Nota técnica</strong>Compreende o princípio antes de memorizar o procedimento.</span></div></div></section><div className="lesson-actions"><button className="ghost-button" disabled={slide===0} onClick={()=>setSlide(slide-1)}>Anterior</button><button className="primary-button" onClick={()=>slide<slides.length-1?setSlide(slide+1):startChallenge()}>{slide<slides.length-1?"Continuar":"Fazer 10 perguntas"}<ChevronRight/></button></div></div>
}

function Challenge({quiz,question,answer,score,finished,choose,retry,next,reset,continueCourse}:{quiz:Check[];question:number;answer:number|null;score:number;finished:boolean;choose:(i:number)=>void;retry:()=>void;next:()=>void;reset:()=>void;continueCourse:()=>void}){
  const passed=score>=8;if(finished)return <div className="page result-page"><div className="result-card"><div className="trophy"><Trophy/></div><span className="eyebrow">Avaliação concluída</span><h1>{passed?"Nível dominado!":"Revê e tenta novamente"}</h1><p>Acertaste {score} de 10. {passed?"O nível seguinte foi desbloqueado.":"São necessárias 8 respostas certas."}</p><div className="reward-row"><div><Zap/><strong>+{passed?250:0}</strong><span>XP</span></div><div><Star/><strong>{score}/10</strong><span>certas</span></div></div><div className="result-actions">{passed&&<button className="primary-button" onClick={continueCourse}>Continuar percurso <ChevronRight/></button>}<button className={passed?"ghost-button":"primary-button"} onClick={reset}>Novo desafio</button></div></div></div>;
  const item=quiz[question];const correct=answer===item.answer;return <div className="page challenge-page"><div className="challenge-head"><span className="eyebrow">Pergunta {question+1} de 10</span><h1>{item.q}</h1><p>Seleciona a resposta tecnicamente correta.</p></div><div className="option-list">{item.options.map((text,i)=><button key={`${text}-${i}`} onClick={()=>choose(i)} className={`option ${answer!==null&&i===item.answer?"correct":""} ${answer===i&&i!==item.answer?"wrong":""}`}><span>{String.fromCharCode(65+i)}</span><strong>{text}</strong>{answer!==null&&i===item.answer&&<Check/>}{answer===i&&i!==item.answer&&<X/>}</button>)}</div>{answer!==null&&<div className={`feedback ${correct?"positive":"negative"}`}><div><strong>{correct?"Correto.":"Revê o conceito."}</strong><span>{correct?"A resposta está de acordo com o princípio apresentado.":"As opções mudam de posição antes de tentares novamente."}</span></div><button className="primary-button" onClick={correct?next:retry}>{correct?(question<9?"Próxima":"Ver resultado"):"Tentar novamente"}<ChevronRight/></button></div>}</div>
}

function Profile({data}:{user:User;data:Data;signInPath:string;signOutPath:string}){const name="Aprendiz";const completed=data.completedLessons.filter(x=>x.startsWith("course-")).length;const rank=categories[Math.min(4,Math.floor(completed/10))];return <div className="page profile-page"><section className="profile-hero"><div className="profile-avatar">A</div><div><span className="eyebrow">Perfil Voltz</span><h1>{name}</h1><p>Progresso guardado neste dispositivo.</p></div></section><section className="stats-grid"><div><Zap/><strong>{data.xp}</strong><span>XP total</span></div><div><Award/><strong>{rank.name}</strong><span>Categoria atual</span></div><div><Trophy/><strong>{completed}/50</strong><span>Níveis</span></div></section><section className="progress-panel"><div className="section-head"><div><span className="eyebrow">Percurso técnico</span><h2>{rank.name} · {rank.role}</h2></div><span>{Math.round(completed/50*100)}%</span></div><Progress value={completed/50*100}/><p>O progresso fica guardado automaticamente neste navegador.</p></section></div>}
