import { allLevels, type Check } from "./curriculum.ts";
export const shuffle=<T,>(items:T[])=>{const out=[...items];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out};
export const shuffleCheck=(item:Check)=>{const correct=item.options[item.answer];const options=shuffle([...item.options]) as [string,string,string];return {...item,options,answer:options.indexOf(correct)}};
export function buildQuiz(level:typeof allLevels[number]){const others=shuffle(level.category.levels.filter(x=>x.id!==level.id));const objectives=others.map(x=>x.objective);const theories=others.map(x=>x.theory);const practices=others.map(x=>x.practice);const correctTheory=level.theory;const correctPractice=level.practice;const formula=level.formula||`Princípio: ${level.title}`;const checks:Check[]=[
    {q:`Qual é o objetivo do nível “${level.title}”?`,options:[level.objective,objectives[0],objectives[1]],answer:0,explanation:`O objetivo é ${level.objective.toLowerCase()}`},
    {q:`Que afirmação descreve corretamente “${level.title}”?`,options:[correctTheory,theories[0],theories[1]],answer:0,explanation:correctTheory},
    {q:"Qual destas tarefas aplica diretamente o que acabaste de aprender?",options:[correctPractice,practices[0],practices[1]],answer:0,explanation:`A aplicação proposta na aula é: ${correctPractice}`},
    {q:"Que relação ou princípio deves recordar neste nível?",options:[formula,others[0].formula||others[0].title,others[1].formula||others[1].title],answer:0,explanation:`A referência apresentada na aula é “${formula}”.`},
    {q:`Que par pertence ao mesmo nível?`,options:[`${level.title} — ${level.objective}`,`${level.title} — ${objectives[2]}`,`${others[2].title} — ${level.objective}`],answer:0,explanation:`“${level.title}” está ligado ao objetivo “${level.objective}”.`},
    {q:"Antes de escolher uma resposta, o que deves conseguir explicar?",options:[correctTheory,theories[2],theories[3]],answer:0,explanation:`A ideia essencial é: ${correctTheory}`},
    {q:"Qual é o exemplo prático correto para este conceito?",options:[correctPractice,practices[2],practices[3]],answer:0,explanation:`Este exemplo verifica o conceito: ${correctPractice}`},
    {q:`Qual destas sínteses corresponde a “${level.title}”?`,options:[`${level.objective} ${correctTheory}`,`${objectives[4]} ${theories[4]}`,`${objectives[5]} ${theories[5]}`],answer:0,explanation:`A síntese junta o objetivo e o princípio explicados nesta aula.`},
    {q:"Que evidência mostra que compreendeste este nível?",options:[`Conseguir explicar o princípio e aplicá-lo: ${correctPractice}`,`Memorizar apenas o título “${level.title}”`,`Escolher uma opção sem justificar`],answer:0,explanation:"Compreender significa explicar o princípio e aplicá-lo a um caso, não apenas memorizar."},
    {q:"Qual é a conclusão tecnicamente coerente com a aula?",options:[correctTheory,theories[6],theories[7]],answer:0,explanation:correctTheory}
  ];if(level.id==="aprendiz-1")checks.splice(4,4,
    {q:"Uma fonte de 12 V alimenta uma resistência de 6 Ω. Qual é a corrente?",options:["2 A","6 A","72 A"],answer:0,explanation:"Pela Lei de Ohm, I = U ÷ R = 12 ÷ 6 = 2 A."},
    {q:"Para procurar a tensão indicada numa tomada de um painel didático, que grandeza selecionas?",options:["V — tensão","A — corrente","Ω — resistência"],answer:0,explanation:"A tensão é medida em volt e identificada por V. O procedimento real exige equipamento e competência adequados."},
    {q:"O visor indica 2 A. Que grandeza foi medida?",options:["Corrente","Tensão","Resistência"],answer:0,explanation:"Ampere, símbolo A, é a unidade da corrente elétrica."},
    {q:"Mantendo 12 V, a resistência passa de 6 Ω para 12 Ω. O que acontece à corrente no modelo simples?",options:["Diminui para 1 A","Aumenta para 4 A","Mantém-se em 2 A"],answer:0,explanation:"I = 12 ÷ 12 = 1 A. Com a mesma tensão, aumentar a resistência reduz a corrente."}
  );if(level.id==="aprendiz-2")checks.splice(4,4,
    {q:"Uma carga resistiva ideal tem 24 V e 12 Ω. Qual é a corrente?",options:["2 A","0,5 A","288 A"],answer:0,explanation:"I = U ÷ R = 24 ÷ 12 = 2 A."},
    {q:"Mantendo R = 10 Ω, a tensão sobe de 10 V para 20 V. O que acontece à corrente?",options:["Duplica, de 1 A para 2 A","Reduz para metade","Não muda"],answer:0,explanation:"I = U ÷ R. Com resistência constante, duplicar a tensão duplica a corrente."},
    {q:"Mantendo U = 12 V, a resistência sobe de 6 Ω para 12 Ω. Qual é a nova corrente?",options:["1 A","2 A","12 A"],answer:0,explanation:"I = 12 ÷ 12 = 1 A; duplicar a resistência reduz a corrente para metade."},
    {q:"Queres calcular resistência conhecendo tensão e corrente. Que forma usas?",options:["R = U ÷ I","R = U × I","R = I ÷ U"],answer:0,explanation:"Reorganizando U = R × I, obtém-se R = U ÷ I."}
  );if(level.id==="aprendiz-3")checks.splice(4,4,
    {q:"Um aquecedor de 1,5 kW funciona durante 3 h. Quanta energia utiliza?",options:["4,5 kWh","2 kWh","0,5 kWh"],answer:0,explanation:"E = P × t = 1,5 × 3 = 4,5 kWh."},
    {q:"Dois aparelhos usam 2 kWh. Um funciona 2 h e outro 1 h. Qual tem maior potência?",options:["O que funciona apenas 1 h","O que funciona 2 h","Têm obrigatoriamente a mesma potência"],answer:0,explanation:"Para usar a mesma energia em menos tempo, o segundo aparelho tem maior potência: 2 kW em vez de 1 kW."},
    {q:"Uma carga de 2 kW funciona durante 30 minutos. Qual é a energia?",options:["1 kWh","4 kWh","60 kWh"],answer:0,explanation:"30 minutos são 0,5 h. E = 2 × 0,5 = 1 kWh."},
    {q:"Um equipamento usa 6 kWh em 3 h. Qual foi a potência média no modelo?",options:["2 kW","18 kW","0,5 kW"],answer:0,explanation:"P = E ÷ t = 6 ÷ 3 = 2 kW."}
  );if(level.id==="aprendiz-4")checks.splice(2,6,
    {q:"A forma de onda sobe e desce, atravessando o zero periodicamente. Que tipo representa?",options:["CA","CC","Uma resistência"],answer:0,explanation:"Uma grandeza que alterna periodicamente de sentido é corrente alternada.",visual:"ac-wave"},
    {q:"A linha mantém polaridade e valor no mesmo sentido. Que tipo representa?",options:["CC","CA","Frequência"],answer:0,explanation:"A corrente contínua mantém polaridade definida.",visual:"dc-line"},
    {q:"Como classificas normalmente a rede doméstica portuguesa e uma bateria?",options:["Rede: CA; bateria: CC","Rede: CC; bateria: CA","Ambas são sempre CA"],answer:0,explanation:"A rede doméstica fornece CA; uma bateria fornece CC.",visual:"ac-dc-devices"},
    {q:"O que significa 50 Hz na rede de CA?",options:["50 ciclos por segundo","50 volts por ciclo","50 mudanças de aparelho"],answer:0,explanation:"Hertz mede frequência: 50 Hz correspondem a 50 ciclos por segundo."},
    {q:"Que símbolo procuras para identificar tensão alternada num aparelho?",options:["V~","V⎓","Ω"],answer:0,explanation:"O til ~ identifica grandeza alternada; o símbolo ⎓ identifica contínua."},
    {q:"Uma saída USB fornece normalmente que tipo de tensão?",options:["CC","CA a 50 Hz","Nenhuma das duas"],answer:0,explanation:"A saída USB fornece tensão contínua regulada."}
  );if(level.id==="aprendiz-5")checks.splice(2,6,
    {q:"Neste esquema, o interruptor está fechado. O que acontece à lâmpada?",options:["Acende, porque existe percurso fechado","Apaga, porque falta neutro","Nada, porque a proteção impede corrente"],answer:0,explanation:"Com fonte, proteção, comando fechado, carga e retorno, o percurso fica completo.",visual:"closed-circuit"},
    {q:"O interruptor cria uma abertura no condutor ativo. Qual é o resultado?",options:["A corrente é interrompida e a lâmpada apaga","A corrente aumenta","O neutro transforma-se em fase"],answer:0,explanation:"Abrir o comando interrompe o percurso da corrente até à carga.",visual:"open-circuit"},
    {q:"Que elementos completam o percurso funcional mostrado?",options:["L até à carga e N no retorno","Apenas PE","Dois condutores PE"],answer:0,explanation:"No modelo monofásico, L alimenta a carga através do comando e N completa o retorno.",visual:"closed-circuit"},
    {q:"Se existir tensão mas o interruptor estiver aberto, há corrente contínua pela lâmpada?",options:["Não","Sim, sempre","Só porque existe proteção"],answer:0,explanation:"A tensão pode existir a montante do interruptor, mas o percurso aberto impede corrente na carga.",visual:"open-circuit"},
    {q:"Qual é a função do dispositivo antes do interruptor neste esquema?",options:["Proteção do circuito","Produzir luz","Substituir o neutro"],answer:0,explanation:"O dispositivo de proteção está a montante do comando e da carga.",visual:"closed-circuit"},
    {q:"Onde deve atuar o interruptor neste modelo introdutório?",options:["No condutor ativo L antes da carga","No PE","Em paralelo direto com a fonte"],answer:0,explanation:"O comando da iluminação atua no condutor ativo que alimenta a carga.",visual:"open-circuit"}
  );if(level.id==="aprendiz-6")checks.splice(2,6,
    {q:"L1 abriu neste circuito em série. O que acontece a L2?",options:["L2 apaga","L2 fica mais forte","L2 mantém-se igual"],answer:0,explanation:"Em série existe um único percurso; abrir L1 interrompe-o para todos os elementos.",visual:"series-open"},
    {q:"L1 abriu num ramo paralelo. O que acontece a L2?",options:["L2 pode continuar ligada","L2 apaga sempre","A fonte deixa de ter tensão"],answer:0,explanation:"O ramo de L2 continua a formar um percurso fechado independente.",visual:"parallel-open"},
    {q:"Qual dos dois desenhos representa uma associação em paralelo?",options:["O desenho com dois ramos","O desenho com um único percurso","Nenhum"],answer:0,explanation:"Em paralelo, cada carga ocupa um ramo entre os mesmos dois pontos.",visual:"series-parallel"},
    {q:"Que grandeza é comum às duas lâmpadas ligadas em série?",options:["A corrente","A tensão individual","A potência"],answer:0,explanation:"Num circuito em série, a mesma corrente atravessa os elementos.",visual:"series-open"},
    {q:"Que grandeza é comum aos ramos do circuito em paralelo?",options:["A tensão","A corrente de cada carga obrigatoriamente","A resistência"],answer:0,explanation:"Os ramos ligados aos mesmos dois pontos têm a mesma tensão.",visual:"parallel-open"},
    {q:"Porque são as cargas domésticas normalmente ligadas em paralelo?",options:["Recebem a tensão prevista e funcionam de forma independente","Precisam da mesma corrente em sequência","Uma avaria deve desligar todas"],answer:0,explanation:"A ligação em paralelo permite funcionamento independente à tensão do circuito.",visual:"series-parallel"}
  );return shuffle(checks).map(shuffleCheck)}
