import { useEffect, useState } from "react";
import { AtSign, Eye, EyeOff, LockKeyhole, Mail, Zap } from "lucide-react";
import FullVoltzApp from "./full-voltz-app";

export const SUPABASE_URL="https://utgtvdmafmehjgebyhqk.supabase.co";
export const SUPABASE_KEY="sb_publishable_RJmuDpACfRDdDjS66HRCSQ_hTtxAfht";
const sessionKey="voltz-auth-session";

export type AuthUser={id:string;email:string;name:string;avatar?:string};
export type AuthSession={access_token:string;refresh_token:string;expires_at?:number;user:{id:string;email?:string;user_metadata?:Record<string,string>}};

async function authFetch(path:string,body?:unknown,token?:string){const response=await fetch(`${SUPABASE_URL}/auth/v1/${path}`,{method:body?"POST":"GET",headers:{apikey:SUPABASE_KEY,"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})},body:body?JSON.stringify(body):undefined});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.msg||data.error_description||data.message||"Não foi possível autenticar.");return data}
function storeSession(session:AuthSession|null){if(session)localStorage.setItem(sessionKey,JSON.stringify(session));else localStorage.removeItem(sessionKey)}
async function restoreSession(){const hash=new URLSearchParams(location.hash.replace(/^#/,""));const recovery=hash.get("type")==="recovery";if(hash.get("access_token")){const session={access_token:hash.get("access_token")!,refresh_token:hash.get("refresh_token")!,expires_at:Math.floor(Date.now()/1000)+Number(hash.get("expires_in")||3600),user:{} as AuthSession["user"]};const user=await authFetch("user",undefined,session.access_token);session.user=user;storeSession(session);history.replaceState({},"",location.pathname+location.search);return {session,recovery}}const raw=localStorage.getItem(sessionKey);if(!raw)return {session:null,recovery:false};try{let session=JSON.parse(raw) as AuthSession;if(session.expires_at&&session.expires_at<Math.floor(Date.now()/1000)+60){const refreshed=await authFetch("token?grant_type=refresh_token",{refresh_token:session.refresh_token});session={...refreshed,expires_at:Math.floor(Date.now()/1000)+Number(refreshed.expires_in||3600)};storeSession(session)}else{const user=await authFetch("user",undefined,session.access_token);session={...session,user}}return {session,recovery:false}}catch{storeSession(null);return {session:null,recovery:false}}}
const mapUser=(session:AuthSession):AuthUser=>({id:session.user.id,email:session.user.email||"",name:session.user.user_metadata?.full_name||session.user.user_metadata?.name||session.user.email?.split("@")[0]||"Aprendiz",avatar:session.user.user_metadata?.avatar_url||session.user.user_metadata?.picture});

async function progressFetch(session:AuthSession,path:string,init:RequestInit={}){const response=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${session.access_token}`,Accept:"application/json",...(init.headers||{})}});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.message||"Não foi possível sincronizar o progresso.")}return response}
export async function loadCloudProgress(session:AuthSession,userId:string){const response=await progressFetch(session,`progress?user_id=eq.${encodeURIComponent(userId)}&select=xp,level,streak,completed_lessons`);const rows=await response.json();if(!rows[0])return null;return {xp:rows[0].xp,level:rows[0].level,streak:rows[0].streak,completedLessons:rows[0].completed_lessons||[]}}
export async function saveCloudProgress(session:AuthSession,userId:string,data:{xp:number;level:number;streak:number;completedLessons:string[]}){await progressFetch(session,"progress",{method:"POST",headers:{"Content-Type":"application/json",Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({user_id:userId,xp:data.xp,level:data.level,streak:data.streak,completed_lessons:data.completedLessons,updated_at:new Date().toISOString()})})}

async function syncEmailPreferences(session:AuthSession,user:AuthUser,consent?:boolean){const body:Record<string,unknown>={user_id:user.id,email:user.email,display_name:user.name,last_active_at:new Date().toISOString(),updated_at:new Date().toISOString()};if(typeof consent==="boolean")body.consent=consent;await progressFetch(session,"email_preferences?on_conflict=user_id",{method:"POST",headers:{"Content-Type":"application/json",Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(body)})}
async function loadEmailConsent(session:AuthSession,userId:string){const response=await progressFetch(session,`email_preferences?user_id=eq.${encodeURIComponent(userId)}&select=consent`);const rows=await response.json();return Boolean(rows[0]?.consent)}
async function sendEmailTests(session:AuthSession){const response=await fetch(`${SUPABASE_URL}/functions/v1/voltz-emails`,{method:"POST",headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({action:"send-test"})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"Não foi possível enviar os emails de teste.");return data}

export default function AuthApp(){const [session,setSession]=useState<AuthSession|null>(null);const [recovery,setRecovery]=useState(false);const [loading,setLoading]=useState(true);const [emailConsent,setEmailConsent]=useState(false);const [emailPreferencesReady,setEmailPreferencesReady]=useState(false);useEffect(()=>{restoreSession().then(result=>{setSession(result.session);setRecovery(result.recovery)}).finally(()=>setLoading(false))},[]);useEffect(()=>{if(!session){setEmailPreferencesReady(false);return}const user=mapUser(session);let active=true;syncEmailPreferences(session,user).then(()=>loadEmailConsent(session,user.id)).then(consent=>{if(active){setEmailConsent(consent);setEmailPreferencesReady(true)}}).catch(()=>{if(active)setEmailPreferencesReady(true)});return()=>{active=false}},[session]);if(loading)return <div className="auth-loading"><Zap fill="currentColor"/><strong>A ligar ao Voltz…</strong></div>;if(!session)return <AuthScreen onSession={setSession}/>;if(recovery)return <UpdatePassword session={session} onDone={()=>setRecovery(false)}/>;const user=mapUser(session);return <FullVoltzApp user={user} loadRemote={()=>loadCloudProgress(session,user.id)} saveRemote={async data=>{await saveCloudProgress(session,user.id,data);await syncEmailPreferences(session,user)}} emailConsent={emailConsent} emailPreferencesReady={emailPreferencesReady} onEmailConsent={async consent=>{await syncEmailPreferences(session,user,consent);setEmailConsent(consent)}} onSendEmailTests={()=>sendEmailTests(session)} onSignOut={async()=>{try{await authFetch("logout",{},session.access_token)}catch{}storeSession(null);localStorage.removeItem("voltz-progress-v1");setSession(null)}}/>}

function UpdatePassword({session,onDone}:{session:AuthSession;onDone:()=>void}){const [password,setPassword]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const response=await fetch(`${SUPABASE_URL}/auth/v1/user`,{method:"PUT",headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({password})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||"Não foi possível alterar a palavra-passe.");onDone()}catch(err){setError(err instanceof Error?err.message:"Ocorreu um erro.")}finally{setBusy(false)}}return <main className="auth-page"><section className="auth-brand"><div className="auth-logo"><Zap fill="currentColor"/> Voltz</div><h1>Cria uma nova<br/>palavra-passe.</h1><p>Escolhe uma palavra-passe segura para voltares às tuas aulas.</p></section><section className="auth-panel"><span className="eyebrow">Recuperação de conta</span><h2>Nova palavra-passe</h2><form onSubmit={submit}><label><span><LockKeyhole/> Palavra-passe</span><input type="password" autoComplete="new-password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mínimo 8 caracteres"/></label>{error&&<p className="auth-error" role="alert">{error}</p>}<button className="primary-button auth-submit" disabled={busy}>{busy?"A guardar…":"Guardar e continuar"}</button></form></section></main>}

function AuthScreen({onSession}:{onSession:(s:AuthSession)=>void}){const [mode,setMode]=useState<"login"|"signup"|"recover">("login");const [name,setName]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [showPassword,setShowPassword]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");const redirect=`${location.origin}${import.meta.env.BASE_URL}`;
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");setMessage("");try{if(mode==="recover"){await authFetch("recover",{email,redirect_to:redirect});setMessage("Enviámos um link de recuperação, se existir uma conta com este email.");return}const data=mode==="signup"?await authFetch("signup",{email,password,data:{full_name:name.trim()}}):await authFetch("token?grant_type=password",{email,password});if(!data.access_token){setMessage("Conta criada. Confirma o email e depois inicia sessão.");setMode("login");return}const session={...data,expires_at:Math.floor(Date.now()/1000)+Number(data.expires_in||3600)} as AuthSession;storeSession(session);onSession(session)}catch(err){setError(err instanceof Error?err.message:"Ocorreu um erro.")}finally{setBusy(false)}}
  function google(){const url=new URL(`${SUPABASE_URL}/auth/v1/authorize`);url.searchParams.set("provider","google");url.searchParams.set("redirect_to",redirect);location.href=url.toString()}
  return <main className="auth-page"><section className="auth-brand"><div className="auth-logo"><Zap fill="currentColor"/> Voltz</div><span className="eyebrow">Eletricidade sem aulas secas</span><h1>Aprende. Pratica.<br/>Evolui com segurança.</h1><p>O teu percurso, XP e níveis ficam guardados na tua conta para continuares em qualquer dispositivo.</p><div className="auth-benefits"><span>✓ 50 níveis progressivos</span><span>✓ Laboratórios e circuitos visuais</span><span>✓ Progresso sincronizado</span></div></section><section className="auth-panel"><div><span className="eyebrow">{mode==="signup"?"Nova conta":mode==="recover"?"Recuperar acesso":"Bem-vindo"}</span><h2>{mode==="signup"?"Criar conta Voltz":mode==="recover"?"Recuperar palavra-passe":"Entrar para aprender"}</h2><p>{mode==="recover"?"Indica o email associado à conta.":"É necessário entrar antes de aceder às aulas e desafios."}</p></div>{mode!=="recover"&&<><button className="google-button" onClick={google}><b>G</b> Continuar com Google</button><div className="auth-divider"><span>ou continua com email</span></div></>}<form onSubmit={submit}>{mode==="signup"&&<label><span><AtSign/> Nome</span><input type="text" autoComplete="name" required minLength={2} value={name} onChange={e=>setName(e.target.value)} placeholder="O teu nome"/></label>}<label><span><Mail/> Email</span><input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="nome@exemplo.pt"/></label>{mode!=="recover"&&<label><span><LockKeyhole/> Palavra-passe</span><div className="password-field"><input type={showPassword?"text":"password"} autoComplete={mode==="signup"?"new-password":"current-password"} minLength={8} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mínimo 8 caracteres"/><button type="button" aria-label={showPassword?"Ocultar palavra-passe":"Mostrar palavra-passe"} onClick={()=>setShowPassword(v=>!v)}>{showPassword?<EyeOff/>:<Eye/>}</button></div></label>}{error&&<p className="auth-error" role="alert">{error}</p>}{message&&<p className="auth-success" role="status">{message}</p>}<button className="primary-button auth-submit" disabled={busy}>{busy?"A processar…":mode==="signup"?"Criar conta":mode==="recover"?"Enviar link":"Entrar"}</button></form>{mode==="login"&&<button className="auth-link" onClick={()=>setMode("recover")}>Esqueci-me da palavra-passe</button>}<div className="auth-switch">{mode==="login"?<>Ainda não tens conta? <button onClick={()=>setMode("signup")}>Criar conta</button></>:<>Já tens conta? <button onClick={()=>setMode("login")}>Entrar</button></>}</div><small className="privacy-note"><AtSign/> Guardamos apenas os dados necessários à conta e ao progresso. Lembretes exigirão consentimento separado.</small></section></main>}
