import { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, BarChart3, Building2, ChevronRight, CircleUserRound, GraduationCap, Mail, MessageSquareText, RefreshCw, School, ServerCog, Shield, ShieldCheck, Users, Zap } from 'lucide-react';
import './voltz-admin.css';

type Section='dashboard'|'users'|'teachers'|'schools'|'statistics'|'feedback'|'reports'|'errors'|'emails'|'system';
type RequestFn=(action:string,input?:Record<string,unknown>)=>Promise<any>;
type Confirm={title:string;message:string;action:()=>Promise<void>}|null;
const nav:[Section,string,React.ReactNode][]=[
 ['dashboard','Dashboard',<BarChart3/>],['users','Utilizadores',<Users/>],['teachers','Professores',<GraduationCap/>],['schools','Escolas',<Building2/>],['statistics','Estatísticas',<Activity/>],['feedback','Feedback',<MessageSquareText/>],['reports','Reports',<ShieldCheck/>],['errors','Erros',<AlertTriangle/>],['emails','Emails',<Mail/>],['system','Sistema',<ServerCog/>],
];
const labels:Record<string,string>={user:'User',teacher:'Teacher',admin:'Admin',evaluation:'Em avaliação',active:'Ativa',partner:'Parceira',inactive:'Inativa',new:'Novo',review:'Em análise',resolved:'Resolvido',ignored:'Ignorado',archived:'Arquivado',open:'Aberto'};
const fmt=(v:any)=>v===null||v===undefined?'—':typeof v==='number'?v.toLocaleString('pt-PT'):String(v);
const date=(v:any)=>v?new Date(v).toLocaleString('pt-PT',{dateStyle:'short',timeStyle:'short'}):'—';

function Metric({label,value,icon}:{label:string;value:any;icon?:React.ReactNode}){return <article className="admin-metric">{icon}<span>{label}</span><strong>{fmt(value)}</strong></article>}
function Empty({children}:{children:React.ReactNode}){return <div className="admin-empty"><Zap/><p>{children}</p></div>}
function Chart({title,items}:{title:string;items:{date:string;value:number}[]}){const max=Math.max(1,...(items||[]).map(x=>Number(x.value)||0));return <section className="admin-card"><h3>{title}</h3>{!items?.length?<Empty>Dados insuficientes.</Empty>:<div className="admin-chart" role="img" aria-label={title}>{items.map((x,i)=><div key={`${x.date}-${i}`} className="admin-bar-wrap" title={`${x.date}: ${x.value}`}><div className="admin-bar" style={{height:`${Math.max(4,(Number(x.value)||0)/max*100)}%`}}/><small>{new Date(x.date).toLocaleDateString('pt-PT',{day:'2-digit',month:'2-digit'})}</small></div>)}</div>}</section>}

export default function VoltzAdmin({request,onExit}:{request:RequestFn;onExit:()=>void}){
 const [section,setSection]=useState<Section>('dashboard');
 const [range,setRange]=useState(7);
 const [data,setData]=useState<any>(null);
 const [busy,setBusy]=useState(false);
 const [error,setError]=useState('');
 const [confirm,setConfirm]=useState<Confirm>(null);
 const [version,setVersion]=useState(0);
 const [userSearch,setUserSearch]=useState('');
 const [userRole,setUserRole]=useState('all');
 const [userActivity,setUserActivity]=useState('all');
 const [selectedUser,setSelectedUser]=useState<any>(null);
 const [teacherSearch,setTeacherSearch]=useState('');
 const [teacherCandidates,setTeacherCandidates]=useState<any[]>([]);
 const [schoolDraft,setSchoolDraft]=useState<any>({name:'',city:'',website:'',contactEmail:'',status:'evaluation',internalNotes:''});
 const [editingSchool,setEditingSchool]=useState<string|null>(null);

 const load=async()=>{setBusy(true);setError('');try{
   if(section==='dashboard')setData(await request('summary',{days:range}));
   else if(section==='users')setData(await request('users',{search:userSearch,role:userRole,activity:userActivity,limit:50,offset:0}));
   else if(section==='teachers')setData(await request('teachers'));
   else if(section==='schools')setData(await request('schools'));
   else if(section==='statistics')setData(await request('statistics',{days:range}));
   else if(['feedback','reports','errors','emails','system'].includes(section))setData(await request(section));
 }catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar esta área.')}finally{setBusy(false)}};
 useEffect(()=>{void load()},[section,range,version]);

 const refresh=()=>setVersion(v=>v+1);
 const statusPill=(status:string)=><span className={`admin-status is-${status}`}>{labels[status]||status}</span>;
 async function openUser(id:string){setBusy(true);try{setSelectedUser(await request('user_detail',{id}))}catch(e){setError(e instanceof Error?e.message:'Erro ao abrir utilizador.')}finally{setBusy(false)}}
 async function findTeacherCandidate(){setBusy(true);setError('');try{const r=await request('users',{search:teacherSearch,role:'all',activity:'all',limit:10,offset:0});setTeacherCandidates(r.items||[])}catch(e){setError(e instanceof Error?e.message:'Não foi possível pesquisar.')}finally{setBusy(false)}}
 function askTeacher(u:any,enabled:boolean){setConfirm({title:enabled?'Dar acesso de Professor?':'Remover acesso de Professor?',message:`${u.name} (${u.email}) passará para ${enabled?'Teacher':'User'}.`,action:async()=>{await request('set_teacher',{id:u.id,enabled});setConfirm(null);setTeacherCandidates([]);refresh()}})}
 async function saveSchool(e:React.FormEvent){e.preventDefault();if(schoolDraft.status==='inactive'){setConfirm({title:'Inativar escola?',message:'A escola deixa de contar como ativa, mas os dados e associações são preservados.',action:async()=>{await request('save_school',{...schoolDraft,id:editingSchool||undefined});setConfirm(null);setEditingSchool(null);setSchoolDraft({name:'',city:'',website:'',contactEmail:'',status:'evaluation',internalNotes:''});refresh()}});return}await request('save_school',{...schoolDraft,id:editingSchool||undefined});setEditingSchool(null);setSchoolDraft({name:'',city:'',website:'',contactEmail:'',status:'evaluation',internalNotes:''});refresh()}
 function editSchool(s:any){setEditingSchool(s.id);setSchoolDraft({name:s.name||'',city:s.city||'',website:s.website||'',contactEmail:s.contactEmail||'',status:s.status||'evaluation',internalNotes:s.internalNotes||''});window.scrollTo({top:0,behavior:'smooth'})}
 async function setItem(kind:string,id:string,status:string,note=''){await request('set_item_status',{kind,id,status,note});refresh()}

 return <div className="admin-shell">
  <aside className="admin-side"><div className="admin-brand"><Shield/><div><strong>Voltz Admin</strong><span>Gestão operacional</span></div></div><nav>{nav.map(([id,label,icon])=><button key={id} className={section===id?'active':''} onClick={()=>{setSection(id);setSelectedUser(null)}}>{icon}<span>{label}</span></button>)}</nav><button className="admin-back" onClick={onExit}>← Voltar ao Voltz</button></aside>
  <main className="admin-main"><header className="admin-top"><div><span className="eyebrow"><ShieldCheck/> Administração</span><h1>Voltz Admin</h1><p>Visão geral da plataforma e gestão operacional.</p></div><button className="ghost-button" onClick={refresh} disabled={busy}><RefreshCw/> Atualizar</button></header>
  <div className="admin-mobile-nav">{nav.map(([id,label,icon])=><button key={id} className={section===id?'active':''} onClick={()=>setSection(id)}>{icon}<span>{label}</span></button>)}</div>
  {error&&<div className="admin-error" role="alert">{error}</div>}
  {busy&&!data&&<div className="admin-loading"><Zap/><strong>A carregar dados reais…</strong></div>}

  {section==='dashboard'&&data&&<><Range value={range} setValue={setRange}/><div className="admin-metrics admin-metrics-main"><Metric label="Utilizadores" value={data.totalUsers} icon={<Users/>}/><Metric label="Online agora" value={data.onlineNow} icon={<Activity/>}/><Metric label="Professores" value={data.teachers} icon={<GraduationCap/>}/><Metric label="Escolas" value={data.schools} icon={<School/>}/></div><div className="admin-metrics"><Metric label="Ativos hoje" value={data.activeToday}/><Metric label="Ativos 7 dias" value={data.activeWeek}/><Metric label="Novos esta semana" value={data.newWeek}/><Metric label="Novos este mês" value={data.newMonth}/><Metric label="Turmas" value={data.classesAvailable?data.classes:'Não disponível'}/><Metric label="Certificados" value={data.certificates}/><Metric label="Voltz Live" value={data.liveTotal}/><Metric label="Feedback pendente" value={data.feedbackPending}/><Metric label="Reports pendentes" value={data.reportsPending}/><Metric label="Erros abertos" value={data.errorsOpen}/></div><div className="admin-chart-grid"><Chart title="Crescimento de utilizadores" items={data.growth||[]}/><Chart title="Novos registos" items={data.registrations||[]}/><Chart title="Atividade por dia" items={data.activity||[]}/></div></>}

  {section==='users'&&<section className="admin-card"><div className="admin-card-head"><div><h2>Utilizadores</h2><p>Informação administrativa essencial, sem histórico pedagógico individual.</p></div></div><form className="admin-filters" onSubmit={e=>{e.preventDefault();void load()}}><input placeholder="Pesquisar nome ou email" value={userSearch} onChange={e=>setUserSearch(e.target.value)}/><select value={userRole} onChange={e=>setUserRole(e.target.value)}><option value="all">Todas as roles</option><option value="user">User</option><option value="teacher">Teacher</option><option value="admin">Admin</option></select><select value={userActivity} onChange={e=>setUserActivity(e.target.value)}><option value="all">Todos</option><option value="active">Ativos</option><option value="inactive">Inativos</option></select><button className="primary-button">Pesquisar</button></form>{data?.items?.length?<div className="admin-table-wrap"><table><thead><tr><th>Nome</th><th>Email</th><th>Role</th><th>Registo</th><th>Última atividade</th><th>Estado</th></tr></thead><tbody>{data.items.map((u:any)=><tr key={u.id} tabIndex={0} onClick={()=>void openUser(u.id)} onKeyDown={e=>{if(e.key==='Enter')void openUser(u.id)}}><td><strong>{u.name}</strong></td><td>{u.email}</td><td>{statusPill(u.role)}</td><td>{date(u.createdAt)}</td><td>{date(u.lastActiveAt)}</td><td>{u.online?statusPill('active'):statusPill('inactive')}</td></tr>)}</tbody></table></div>:<Empty>Ainda não existem utilizadores correspondentes aos filtros.</Empty>}{selectedUser&&<div className="admin-detail"><button className="admin-close" onClick={()=>setSelectedUser(null)}>×</button><CircleUserRound/><h3>{selectedUser.name}</h3><p>{selectedUser.email}</p><dl><div><dt>Role</dt><dd>{labels[selectedUser.role]||selectedUser.role}</dd></div><div><dt>Registo</dt><dd>{date(selectedUser.createdAt)}</dd></div><div><dt>Última atividade</dt><dd>{date(selectedUser.lastActiveAt)}</dd></div><div><dt>XP</dt><dd>{fmt(selectedUser.xp)}</dd></div><div><dt>Níveis concluídos</dt><dd>{fmt(selectedUser.completed)}/50</dd></div><div><dt>Certificado</dt><dd>{selectedUser.certificate?'Sim':'Não'}</dd></div></dl></div>}</section>}

  {section==='teachers'&&<><section className="admin-card"><h2>Dar acesso de Professor</h2><div className="admin-search-line"><input type="email" placeholder="email@exemplo.pt" value={teacherSearch} onChange={e=>setTeacherSearch(e.target.value)}/><button className="primary-button" onClick={()=>void findTeacherCandidate()} disabled={!teacherSearch.trim()}>Pesquisar</button></div>{teacherCandidates.map(u=><div className="admin-candidate" key={u.id}><div><strong>{u.name}</strong><span>{u.email} · {labels[u.role]||u.role}</span></div>{u.role==='user'?<button className="primary-button" onClick={()=>askTeacher(u,true)}>Dar acesso</button>:u.role==='teacher'?<span>Já é professor</span>:<span>Administrador</span>}</div>)}</section><section className="admin-card"><h2>Professores</h2>{data?.length?<div className="admin-list">{data.map((t:any)=><article key={t.id}><div><strong>{t.name}</strong><span>{t.email}</span><small>{t.school||'Sem escola associada'} · {date(t.lastActiveAt)}</small></div><div className="admin-row-actions"><select value={t.schoolId||''} onChange={async e=>{if(e.target.value)await request('assign_teacher_school',{userId:t.id,schoolId:e.target.value});refresh()}}><option value="">Associar escola…</option>{(Array.isArray((data as any).schools)?(data as any).schools:[]).map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button className="danger-link" onClick={()=>askTeacher(t,false)}>Remover Professor</button></div></article>)}</div>:<Empty>Ainda não existem professores.</Empty>}</section></>}

  {section==='schools'&&<><section className="admin-card"><h2>{editingSchool?'Editar escola':'Criar escola'}</h2><form className="admin-school-form" onSubmit={e=>void saveSchool(e)}><label>Nome<input required minLength={2} value={schoolDraft.name} onChange={e=>setSchoolDraft({...schoolDraft,name:e.target.value})}/></label><label>Cidade<input value={schoolDraft.city} onChange={e=>setSchoolDraft({...schoolDraft,city:e.target.value})}/></label><label>Website<input type="url" value={schoolDraft.website} onChange={e=>setSchoolDraft({...schoolDraft,website:e.target.value})}/></label><label>Email de contacto<input type="email" value={schoolDraft.contactEmail} onChange={e=>setSchoolDraft({...schoolDraft,contactEmail:e.target.value})}/></label><label>Estado<select value={schoolDraft.status} onChange={e=>setSchoolDraft({...schoolDraft,status:e.target.value})}><option value="evaluation">Em avaliação</option><option value="active">Ativa</option><option value="partner">Parceira</option><option value="inactive">Inativa</option></select></label><label className="wide">Notas internas<textarea rows={3} value={schoolDraft.internalNotes} onChange={e=>setSchoolDraft({...schoolDraft,internalNotes:e.target.value})}/></label><div className="wide admin-row-actions"><button className="primary-button">{editingSchool?'Guardar alterações':'Criar escola'}</button>{editingSchool&&<button type="button" className="ghost-button" onClick={()=>{setEditingSchool(null);setSchoolDraft({name:'',city:'',website:'',contactEmail:'',status:'evaluation',internalNotes:''})}}>Cancelar</button>}</div></form></section><section className="admin-school-grid">{data?.length?data.map((s:any)=><article className="admin-card" key={s.id}><div className="admin-card-head"><h3>{s.name}</h3>{statusPill(s.status)}</div><p>{s.city||'Cidade não indicada'}</p><div className="admin-school-stats"><span><strong>{s.teachers}</strong> professores</span><span><strong>{s.classes}</strong> turmas</span><span><strong>{s.students}</strong> alunos</span><span><strong>{s.liveThisMonth}</strong> Live este mês</span></div>{s.activityPercent===null&&<small>Atividade escolar agregada: dados ainda não disponíveis.</small>}<button className="ghost-button" onClick={()=>editSchool(s)}>Editar</button></article>):<Empty>Ainda não existem escolas registadas.</Empty>}</section></>}

  {section==='statistics'&&data&&<><Range value={range} setValue={setRange}/><div className="admin-metrics"><Metric label="Utilizadores totais" value={data.totalUsers}/><Metric label={`Novos (${range}d)`} value={data.newPeriod}/><Metric label={`Ativos (${range}d)`} value={data.activePeriod}/><Metric label="Taxa de utilização" value={`${data.usageRate}%`}/><Metric label="Níveis concluídos" value={data.levelsCompleted}/><Metric label="Conclusão do percurso" value={`${data.completionRate}%`}/><Metric label="Certificados" value={data.certificates}/><Metric label="Professores" value={data.teachers}/><Metric label="Escolas" value={data.schools}/></div><div className="admin-chart-grid"><Chart title="Crescimento" items={data.growth||[]}/><Chart title="Atividade" items={data.activity||[]}/></div><section className="admin-card"><h2>Voltz Live</h2><div className="admin-metrics"><Metric label="Sessões totais" value={data.live?.total}/><Metric label="Este mês" value={data.live?.month}/><Metric label="Participações" value={data.live?.participants}/><Metric label="Média / sessão" value={data.live?.avgParticipants}/></div></section><section className="admin-card"><h2>Estatísticas pedagógicas globais</h2>{data.pedagogyAvailable?<p>Dados disponíveis.</p>:<Empty>Dados insuficientes. O Voltz ainda não guarda respostas individuais agregáveis em student_answers.</Empty>}</section></>}

  {(['feedback','reports','errors'] as Section[]).includes(section)&&<Inbox kind={section as 'feedback'|'reports'|'errors'} items={data||[]} onStatus={setItem}/>} 
  {section==='emails'&&data&&<><div className="admin-metrics"><Metric label="Consentimentos ativos" value={data.consents}/><Metric label="Emails enviados" value={data.sent}/><Metric label="Falhas" value={data.failed}/><Metric label="Feedback" value={data.feedback}/><Metric label="Reminder 1" value={data.reminder1}/><Metric label="Reminder 2" value={data.reminder2}/><Metric label="Certificados" value={data.certificate}/><Metric label="Testes" value={data.test}/></div><section className="admin-card"><h2>Processamento de emails</h2><p>Último email registado: <strong>{date(data.lastSent)}</strong></p><p>Última atualização de preferências: <strong>{date(data.lastPreferenceUpdate)}</strong></p>{!data.sent&&!data.failed&&<Empty>Ainda não existem logs de envio. Os próximos envios serão registados sem guardar o corpo dos emails.</Empty>}</section></>}
  {section==='system'&&data&&<System data={data}/>} 
  </main>
  {confirm&&<div className="modal-backdrop"><section className="confirm-modal" role="dialog" aria-modal="true"><div className="modal-icon"><Shield/></div><h2>{confirm.title}</h2><p>{confirm.message}</p><div className="modal-actions"><button className="ghost-button" onClick={()=>setConfirm(null)}>Cancelar</button><button className="danger-button" onClick={()=>void confirm.action()}>Confirmar</button></div></section></div>}
 </div>
}

function Range({value,setValue}:{value:number;setValue:(v:number)=>void}){return <div className="admin-range" aria-label="Período"><span>Período:</span>{[1,7,30,90].map(n=><button key={n} className={value===n?'active':''} onClick={()=>setValue(n)}>{n===1?'Hoje':`${n} dias`}</button>)}</div>}

function Inbox({kind,items,onStatus}:{kind:'feedback'|'reports'|'errors';items:any[];onStatus:(kind:string,id:string,status:string,note?:string)=>Promise<void>}){const title=kind==='feedback'?'Feedback':kind==='reports'?'Reports':'Erros';const options=kind==='feedback'?['new','review','resolved','ignored']:kind==='reports'?['new','review','resolved','archived']:['open','review','resolved','ignored'];return <section className="admin-card"><h2>{title}</h2>{items?.length?<div className="admin-inbox">{items.map((x:any)=><article key={x.id}><div className="admin-card-head"><div><strong>{x.title||x.message||x.reason}</strong><small>{date(x.createdAt||x.firstSeenAt)} {x.source?`· ${x.source}`:''}</small></div><select value={x.status} onChange={e=>void onStatus(kind==='reports'?'report':kind==='errors'?'error':'feedback',x.id,e.target.value,x.internalNote||'')}>{options.map(s=><option key={s} value={s}>{labels[s]||s}</option>)}</select></div><p>{x.description||x.message}</p>{x.page&&<small>Página: {x.page}</small>}{x.route&&<small>Rota: {x.route}</small>}{x.occurrences&&<small>Ocorrências: {x.occurrences} · última: {date(x.lastSeenAt)}</small>}</article>)}</div>:<Empty>{kind==='feedback'?'Não existe feedback registado.':kind==='reports'?'Não existem reports pendentes.':'Sem erros registados.'}</Empty>}</section>}

function System({data}:{data:any}){const row=(label:string,status:any,detail?:string)=><div className="admin-health"><span>{label}</span><strong className={String(status).includes('operational')||status==='success'?'ok':''}>{status||'Não disponível'}</strong>{detail&&<small>{detail}</small>}</div>;return <><section className="admin-card"><h2>Saúde do sistema</h2>{row('Frontend',data.frontend)}{row('Supabase / Base de dados',data.database)}{row('Auth',data.auth)}{row('Edge Function voltz-admin',data.edgeFunction)}{row('Emails',data.emails?.status)}<p>Última verificação: <strong>{date(data.checkedAt)}</strong></p></section><section className="admin-card"><h2>GitHub / Deploy</h2>{data.github?.available?<>{row('GitHub Pages',data.github.pages?.conclusion||data.github.pages?.status)}{row('Último commit',data.github.commit?.sha,data.github.commit?.message)}<p>Atualizado: {date(data.github.pages?.at||data.github.commit?.at)}</p></>:<Empty>Estado GitHub não disponível neste momento.</Empty>}</section><section className="admin-card"><h2>Último erro</h2>{data.lastError?<p><strong>{data.lastError.source}</strong> — {data.lastError.message}<br/><small>{date(data.lastError.at)}</small></p>:<Empty>Sem erros registados.</Empty>}</section></>}
