import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { Activity, AlertTriangle, BarChart3, Building2, CircleUserRound, GraduationCap, Mail, MessageSquareText, RefreshCw, School, ServerCog, Shield, ShieldCheck, Users, Zap } from 'lucide-react';
import './voltz-admin.css';

type Section='dashboard'|'users'|'teachers'|'schools'|'statistics'|'feedback'|'reports'|'errors'|'emails'|'system';
type RequestFn=(action:string,input?:Record<string,unknown>)=>Promise<any>;
type Confirm={title:string;message:string;action:()=>Promise<void>}|null;
const nav:[Section,string,ReactNode][]=[['dashboard','Dashboard',<BarChart3/>],['users','Utilizadores',<Users/>],['teachers','Professores',<GraduationCap/>],['schools','Escolas',<Building2/>],['statistics','Estatísticas',<Activity/>],['feedback','Feedback',<MessageSquareText/>],['reports','Reports',<ShieldCheck/>],['errors','Erros',<AlertTriangle/>],['emails','Emails',<Mail/>],['system','Sistema',<ServerCog/>]];
const labels:Record<string,string>={user:'User',teacher:'Teacher',admin:'Admin',evaluation:'Em avaliação',active:'Ativa',partner:'Parceira',inactive:'Inativa',new:'Novo',review:'Em análise',resolved:'Resolvido',ignored:'Ignorado',archived:'Arquivado',open:'Aberto'};
const fmt=(v:any)=>v===null||v===undefined?'—':typeof v==='number'?v.toLocaleString('pt-PT'):String(v);
const date=(v:any)=>v?new Date(v).toLocaleString('pt-PT',{dateStyle:'short',timeStyle:'short'}):'—';
function Metric({label,value,icon}:{label:string;value:any;icon?:ReactNode}){return <article className="admin-metric">{icon}<span>{label}</span><strong>{fmt(value)}</strong></article>}
function Empty({children}:{children:ReactNode}){return <div className="admin-empty"><Zap/><p>{children}</p></div>}
function Chart({title,items}:{title:string;items:{date:string;value:number}[]}){const max=Math.max(1,...(items||[]).map(x=>Number(x.value)||0));return <section className="admin-card"><h3>{title}</h3>{!items?.length?<Empty>Dados insuficientes.</Empty>:<div className="admin-chart" role="img" aria-label={title}>{items.map((x,i)=><div key={`${x.date}-${i}`} className="admin-bar-wrap" title={`${x.date}: ${x.value}`}><div className="admin-bar" style={{height:`${Math.max(4,(Number(x.value)||0)/max*100)}%`}}/><small>{new Date(x.date).toLocaleDateString('pt-PT',{day:'2-digit',month:'2-digit'})}</small></div>)}</div>}</section>}

export default function VoltzAdmin({request,onExit}:{request:RequestFn;onExit:()=>void}){
 const [section,setSection]=useState<Section>('dashboard');
 const [range,setRange]=useState(7);
 const [data,setData]=useState<any>(null);
 const [busy,setBusy]=useState(false);
 const [error,setError]=useState('');
 const [confirm,setConfirm]=useState<Confirm>(null);
 const [version,setVersion]=useState(0);
 const [userSearch,setUserSearch]=useState('');
 const [userRole,setUserRole]=useState('all');
 const [userActivity,setUserActivity]=useState('all');
 const [userOffset,setUserOffset]=useState(0);
 const [selectedUser,setSelectedUser]=useState<any>(null);
 const [teacherSearch,setTeacherSearch]=useState('');
 const [teacherCandidates,setTeacherCandidates]=useState<any[]>([]);
 const [schoolDraft,setSchoolDraft]=useState<any>({name:'',city:'',website:'',contactEmail:'',status:'evaluation',internalNotes:''});
 const [editingSchool,setEditingSchool]=useState<string|null>(null);
 const pageSize=50;

 const load=async()=>{setBusy(true);setError('');try{let next:any=null;if(section==='dashboard')next=await request('summary',{days:range});else if(section==='users')next=await request('users',{search:userSearch,role:userRole,activity:userActivity,limit:pageSize,offset:userOffset});else if(section==='teachers')next=await request('teachers');else if(section==='schools')next=await request('schools');else if(section==='statistics')next=await request('statistics',{days:range});else if(['feedback','reports','errors','emails','system'].includes(section))next=await request(section);setData(next)}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar esta área.')}finally{setBusy(false)}};
 useEffect(()=>{void load()},[section,range,version,userOffset]);
 const refresh=()=>setVersion(v=>v+1);
 const statusPill=(status:string)=><span className={`admin-status is-${status}`}>{labels[status]||status}</span>;
 async function action(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Não foi possível concluir a ação.')}finally{setBusy(false)}}
 async function openUser(id:string){await action(async()=>setSelectedUser(await request('user_detail',{id})))}
 async function findTeacherCandidate(){await action(async()=>{const r=await request('users',{search:teacherSearch,role:'all',activity:'all',limit:10,offset:0});setTeacherCandidates(r.items||[])})}
 function askTeacher(u:any,enabled:boolean){setConfirm({title:enabled?'Dar acesso de Professor?':'Remover acesso de Professor?',message:`${u.name} (${u.email}) passará para ${enabled?'Teacher':'User'}.`,action:async()=>{await request('set_teacher',{id:u.id,enabled});setConfirm(null);setTeacherCandidates([]);refresh()}})}
 async function saveSchool(e:FormEvent){e.preventDefault();const doSave=async()=>{await request('save_school',{...schoolDraft,id:editingSchool||undefined});setConfirm(null);setEditingSchool(null);setSchoolDraft({name:'',city:'',website:'',contactEmail:'',status:'evaluation',internalNotes:''});refresh()};if(schoolDraft.status==='inactive'){setConfirm({title:'Inativar escola?',message:'A escola deixa de contar como ativa, mas os dados e associações são preservados.',action:doSave});return}await action(doSave)}
 function editSchool(s:any){setEditingSchool(s.id);setSchoolDraft({name:s.name||'',city:s.city||'',website:s.website||'',contactEmail:s.contactEmail||'',status:s.status||'evaluation',internalNotes:s.internalNotes||''});window.scrollTo({top:0,behavior:'smooth'})}
 async function assignSchool(userId:string,schoolId:string){if(!schoolId)return;await action(async()=>{await request('assign_teacher_school',{userId,schoolId});refresh()})}
 async function setItem(kind:string,id:string,status:string,note=''){await action(async()=>{await request('set_item_status',{kind,id,status,note});refresh()})}

 return <div className="admin-shell"><aside className="admin-side"><div className="admin-brand"><Shield/><div><strong>Voltz Admin</strong><span>Gestão operacional</span></div></div><nav>{nav.map(([id,label,icon])=><button key={id} className={section===id?'active':''} onClick={()=>{setSection(id);setSelectedUser(null);setUserOffset(0)}}>{icon}<span>{label}</span></button>)}</nav><button className="admin-back" onClick={onExit}>← Voltar ao Voltz</button></aside>
 <main className="admin-main"><header className="admin-top"><div><span className="eyebrow"><ShieldCheck/> Administração</span><h1>Voltz Admin</h1><p>Visão geral da plataforma e gestão operacional.</p></div><button className="ghost-button" onClick={refresh} disabled={busy}><RefreshCw/> Atualizar</button></header><div className="admin-mobile-nav">{nav.map(([id,label,icon])=><button key={id} className={section===id?'active':''} onClick={()=>{setSection(id);setUserOffset(0)}}>{icon}<span>{label}</span></button>)}</div>
 {error&&<div className="admin-error" role="alert">{error}</div>}{busy&&!data&&<div className="admin-loading"><Zap/><strong>A carregar dados reais…</strong></div>}

 {section==='dashboard'&&data&&<><Range value={range} setValue={setRange}/><div className="admin-metrics admin-metrics-main"><Metric label="Utilizadores" value={data.totalUsers} icon={<Users/>}/><Metric label="Online agora" value={data.onlineNow} icon={<Activity/>}/><Metric label="Professores" value={data.teachers} icon={<GraduationCap/>}/><Metric label="Escolas" value={data.schools} icon={<School/>}/></div><div className="admin-metrics"><Metric label="Ativos hoje" value={data.activeToday}/><Metric label="Ativos esta semana" value={data.activeWeek}/><Metric label="Novos esta semana" value={data.newWeek}/><Metric label="Novos este mês" value={data.newMonth}/><Metric label="Turmas" value={data.classesAvailable?data.classes:'Não disponível'}/><Metric label="Certificados" value={data.certificates}/><Metric label="Voltz Live realizados" value={data.liveTotal}/><Metric label="Feedback pendente" value={data.feedbackPending}/><Metric label="Reports pendentes" value={data.reportsPending}/><Metric label="Erros abertos" value={data.errorsOpen}/></div><div className="admin-chart-grid"><Chart title="Crescimento de utilizadores" items={data.growth||[]}/><Chart title="Novos registos" items={data.registrations||[]}/><Chart title="Utilização por dia" items={data.activity||[]}/></div></>}

 {section==='users'&&<section className="admin-card"><div className="admin-card-head"><div><h2>Utilizadores</h2><p>Informação administrativa essencial, sem histórico pedagógico individual.</p></div>{data?.total!==undefined&&<strong>{fmt(data.total)} total</strong>}</div><form className="admin-filters" onSubmit={e=>{e.preventDefault();setUserOffset(0);refresh()}}><input placeholder="Pesquisar nome ou email" value={userSearch} onChange={e=>setUserSearch(e.target.value)}/><select value={userRole} onChange={e=>setUserRole(e.target.value)}><option value="all">Todas as roles</option><option value="user">User</option><option value="teacher">Teacher</option><option value="admin">Admin</option></select><select value={userActivity} onChange={e=>setUserActivity(e.target.value)}><option value="all">Todos</option><option value="active">Ativos</option><option value="inactive">Inativos</option></select><button className="primary-button">Pesquisar</button></form>{data?.items?.length?<><div className="admin-table-wrap"><table><thead><tr><th>Nome</th><th>Email</th><th>Role</th><th>Data de registo</th><th>Última atividade</th><th>Estado</th></tr></thead><tbody>{data.items.map((u:any)=><tr key={u.id} tabIndex={0} onClick={()=>void openUser(u.id)} onKeyDown={e=>{if(e.key==='Enter')void openUser(u.id)}}><td><strong>{u.name}</strong></td><td>{u.email}</td><td>{statusPill(u.role)}</td><td>{date(u.createdAt)}</td><td>{date(u.lastActiveAt)}</td><td>{u.online?statusPill('active'):statusPill('inactive')}</td></tr>)}</tbody></table></div><div className="admin-pagination"><button className="ghost-button" disabled={userOffset===0} onClick={()=>setUserOffset(Math.max(0,userOffset-pageSize))}>Anterior</button><span>{userOffset+1}–{Math.min(userOffset+pageSize,data.total)} de {data.total}</span><button className="ghost-button" disabled={userOffset+pageSize>=data.total} onClick={()=>setUserOffset(userOffset+pageSize)}>Seguinte</button></div></>:<Empty>Ainda não existem utilizadores correspondentes aos filtros.</Empty>}{selectedUser&&<div className="admin-detail"><button className="admin-close" onClick={()=>setSelectedUser(null)} aria-label="Fechar detalhe">×</button><CircleUserRound/><h3>{selectedUser.name}</h3><p>{selectedUser.email}</p><dl><div><dt>Role</dt><dd>{labels[selectedUser.role]||selectedUser.role}</dd></div><div><dt>Data de registo</dt><dd>{date(selectedUser.createdAt)}</dd></div><div><dt>Última atividade</dt><dd>{date(selectedUser.lastActiveAt)}</dd></div><div><dt>Progresso geral</dt><dd>{selectedUser.completed}/50 níveis</dd></div><div><dt>XP</dt><dd>{fmt(selectedUser.xp)}</dd></div><div><dt>Certificado</dt><dd>{selectedUser.certificate?'Sim':'Não'}</dd></div></dl>{selectedUser.certificate?.code&&<p>Código: <strong>{selectedUser.certificate.code}</strong></p>}</div>}</section>}

 {section==='teachers'&&<><section className="admin-card"><h2>Dar acesso de Professor</h2><p>Pesquisa uma conta Voltz existente. A alteração fica registada no audit log.</p><div className="admin-search-line"><input type="email" placeholder="email@exemplo.pt" value={teacherSearch} onChange={e=>setTeacherSearch(e.target.value)}/><button className="primary-button" onClick={()=>void findTeacherCandidate()} disabled={!teacherSearch.trim()||busy}>Pesquisar</button></div>{teacherCandidates.map(u=><div className="admin-candidate" key={u.id}><div><strong>{u.name}</strong><span>{u.email} · {labels[u.role]||u.role}</span></div>{u.role==='user'?<button className="primary-button" onClick={()=>askTeacher(u,true)}>Dar acesso de Professor</button>:u.role==='teacher'?<span>Já é Professor</span>:<span>Conta admin</span>}</div>)}</section><section className="admin-card"><h2>Professores</h2>{data?.items?.length?<div className="admin-list">{data.items.map((t:any)=><article key={t.id}><div><strong>{t.name}</strong><span>{t.email}</span><small>{t.school||'Sem escola associada'} · {date(t.lastActiveAt)} · {t.online?'online':'offline'}</small></div><div className="admin-row-actions"><select value={t.schoolId||''} onChange={e=>void assignSchool(t.id,e.target.value)} aria-label={`Escola de ${t.name}`}><option value="">Associar escola…</option>{(data.schools||[]).map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button className="danger-link" onClick={()=>askTeacher(t,false)}>Remover acesso</button></div></article>)}</div>:<Empty>Ainda não existem professores.</Empty>}</section></>}

 {section==='schools'&&<><section className="admin-card"><h2>{editingSchool?'Editar escola':'Criar escola'}</h2><form className="admin-school-form" onSubmit={e=>void saveSchool(e)}><label>Nome<input required minLength={2} value={schoolDraft.name} onChange={e=>setSchoolDraft({...schoolDraft,name:e.target.value})}/></label><label>Cidade opcional<input value={schoolDraft.city} onChange={e=>setSchoolDraft({...schoolDraft,city:e.target.value})}/></label><label>Website opcional<input type="url" value={schoolDraft.website} onChange={e=>setSchoolDraft({...schoolDraft,website:e.target.value})}/></label><label>Email de contacto opcional<input type="email" value={schoolDraft.contactEmail} onChange={e=>setSchoolDraft({...schoolDraft,contactEmail:e.target.value})}/></label><label>Estado<select value={schoolDraft.status} onChange={e=>setSchoolDraft({...schoolDraft,status:e.target.value})}><option value="evaluation">Em avaliação</option><option value="active">Ativa</option><option value="partner">Parceira</option><option value="inactive">Inativa</option></select></label><label className="wide">Notas internas<textarea rows={3} value={schoolDraft.internalNotes} onChange={e=>setSchoolDraft({...schoolDraft,internalNotes:e.target.value})}/></label><div className="wide admin-row-actions"><button className="primary-button" disabled={busy}>{editingSchool?'Guardar alterações':'Criar escola'}</button>{editingSchool&&<button type="button" className="ghost-button" onClick={()=>{setEditingSchool(null);setSchoolDraft({name:'',city:'',website:'',contactEmail:'',status:'evaluation',internalNotes:''})}}>Cancelar</button>}</div></form></section><section className="admin-school-grid">{data?.length?data.map((s:any)=><article className="admin-card" key={s.id}><div className="admin-card-head"><h3>{s.name}</h3>{statusPill(s.status)}</div><p>{s.city||'Cidade não indicada'}</p><div className="admin-school-stats"><span><strong>{s.teachers}</strong> professores</span><span><strong>{s.classes}</strong> turmas registadas</span><span><strong>{s.students}</strong> alunos associados</span><span><strong>{s.liveThisMonth}</strong> Live este mês</span></div>{s.activityPercent===null&&<small>Atividade escolar agregada: dados ainda não disponíveis.</small>}<button className="ghost-button" onClick={()=>editSchool(s)}>Editar</button></article>):<Empty>Ainda não existem escolas registadas.</Empty>}</section></>}

 {section==='statistics'&&data&&<><Range value={range} setValue={setRange}/><div className="admin-metrics"><Metric label="Utilizadores totais" value={data.totalUsers}/><Metric label={`Novos (${range}d)`} value={data.newPeriod}/><Metric label={`Ativos (${range}d)`} value={data.activePeriod}/><Metric label="Taxa de utilização" value={`${data.usageRate}%`}/><Metric label="Níveis concluídos" value={data.levelsCompleted}/><Metric label="Conclusão do percurso" value={`${data.completionRate}%`}/><Metric label="Certificados emitidos" value={data.certificates}/><Metric label="Professores" value={data.teachers}/><Metric label="Escolas" value={data.schools}/><Metric label="Turmas" value={data.classesAvailable?data.classes:'Não disponível'}/></div><div className="admin-chart-grid"><Chart title="Crescimento de utilizadores" items={data.growth||[]}/><Chart title="Atividade semanal" items={data.activity||[]}/></div><section className="admin-card"><h2>Voltz Live</h2><div className="admin-metrics"><Metric label="Sessões totais" value={data.live?.total}/><Metric label="Sessões este mês" value={data.live?.month}/><Metric label="Participações totais" value={data.live?.participants}/><Metric label="Média participantes/sessão" value={data.live?.avgParticipants}/></div></section><section className="admin-card"><h2>Estatísticas pedagógicas globais</h2>{data.pedagogyAvailable?<p>Dados disponíveis.</p>:<Empty>Dados insuficientes. O Voltz ainda não possui student_answers, por isso não são calculadas perguntas mais erradas, taxa média de acerto ou desistências por nível.</Empty>}</section></>}

 {(['feedback','reports','errors'] as Section[]).includes(section)&&<Inbox kind={section as 'feedback'|'reports'|'errors'} items={data||[]} onStatus={setItem}/>} 
 {section==='emails'&&data&&<><div className="admin-metrics"><Metric label="Consentimentos ativos" value={data.consents}/><Metric label="Emails enviados" value={data.sent}/><Metric label="Falhas" value={data.failed}/><Metric label="Feedback emails" value={data.feedback}/><Metric label="Reminder 1" value={data.reminder1}/><Metric label="Reminder 2" value={data.reminder2}/><Metric label="Certificados enviados" value={data.certificate}/><Metric label="Emails de teste" value={data.test}/></div><section className="admin-card"><h2>Processamento de emails</h2><p>Último envio registado: <strong>{date(data.lastSent)}</strong></p><p>Última atividade das preferências: <strong>{date(data.lastPreferenceUpdate)}</strong></p>{!data.sent&&!data.failed&&<Empty>Ainda não existem logs de envio.</Empty>}</section></>}
 {section==='system'&&data&&<System data={data}/>} 
 </main>{confirm&&<div className="modal-backdrop"><section className="confirm-modal" role="dialog" aria-modal="true"><div className="modal-icon"><Shield/></div><h2>{confirm.title}</h2><p>{confirm.message}</p><div className="modal-actions"><button className="ghost-button" onClick={()=>setConfirm(null)}>Cancelar</button><button className="danger-button" disabled={busy} onClick={()=>void action(confirm.action)}>Confirmar</button></div></section></div>}</div>
}

function Range({value,setValue}:{value:number;setValue:(v:number)=>void}){return <div className="admin-range" aria-label="Período"><span>Período:</span>{[1,7,30,90].map(n=><button key={n} className={value===n?'active':''} onClick={()=>setValue(n)}>{n===1?'Hoje':`${n} dias`}</button>)}</div>}
function Inbox({kind,items,onStatus}:{kind:'feedback'|'reports'|'errors';items:any[];onStatus:(kind:string,id:string,status:string,note?:string)=>Promise<void>}){const title=kind==='feedback'?'Feedback':kind==='reports'?'Reports':'Erros';return <section className="admin-card"><h2>{title}</h2>{items?.length?<div className="admin-inbox">{items.map(x=><InboxItem key={x.id} kind={kind} item={x} onStatus={onStatus}/>)}</div>:<Empty>{kind==='feedback'?'Não existe feedback registado.':kind==='reports'?'Não existem reports pendentes.':'Sem erros abertos.'}</Empty>}</section>}
function InboxItem({kind,item,onStatus}:{kind:'feedback'|'reports'|'errors';item:any;onStatus:(kind:string,id:string,status:string,note?:string)=>Promise<void>}){const options=kind==='feedback'?['new','review','resolved','ignored']:kind==='reports'?['new','review','resolved','archived']:['open','review','resolved','ignored'];const [status,setStatus]=useState(item.status);const [note,setNote]=useState(item.internalNote||'');const apiKind=kind==='reports'?'report':kind==='errors'?'error':'feedback';return <article><div className="admin-card-head"><div><strong>{item.title||item.message||item.reason}</strong><small>{date(item.createdAt||item.firstSeenAt)} {item.source?`· ${item.source}`:''}</small></div>{statusPillStatic(status)}</div><p>{item.description||item.message}</p>{item.userEmail&&<small>Utilizador: {item.userEmail}</small>}{item.reporterEmail&&<small>Reportado por: {item.reporterEmail}</small>}{item.page&&<small>Página: {item.page}</small>}{item.route&&<small>Rota: {item.route}</small>}{item.occurrences&&<small>Ocorrências: {item.occurrences} · última: {date(item.lastSeenAt)}</small>}<div className="admin-inbox-actions"><select value={status} onChange={e=>setStatus(e.target.value)}>{options.map(s=><option key={s} value={s}>{labels[s]||s}</option>)}</select>{kind!=='errors'&&<textarea rows={2} placeholder="Nota interna" value={note} onChange={e=>setNote(e.target.value)}/>}<button className="ghost-button" onClick={()=>void onStatus(apiKind,item.id,status,note)}>Guardar estado</button></div></article>}
function statusPillStatic(status:string){return <span className={`admin-status is-${status}`}>{labels[status]||status}</span>}
function System({data}:{data:any}){const row=(label:string,status:any,detail?:string)=><div className="admin-health"><span>{label}</span><strong className={String(status).includes('operational')||status==='success'?'ok':''}>{status||'Não disponível'}</strong>{detail&&<small>{detail}</small>}</div>;return <><section className="admin-card"><h2>Saúde do sistema</h2>{row('Frontend',data.frontend)}{row('Supabase / Base de dados',data.database)}{row('Auth',data.auth)}{row('Edge Function voltz-admin',data.edgeFunction)}{row('Emails',data.emails?.status)}{row('Versão Voltz',data.version)}<p>Última verificação: <strong>{date(data.checkedAt)}</strong></p></section><section className="admin-card"><h2>GitHub / Deploy</h2>{data.github?.available?<>{row('GitHub Pages',data.github.pages?.conclusion||data.github.pages?.status)}{row('Último commit',data.github.commit?.sha,data.github.commit?.message)}<p>Último deploy/estado: {date(data.github.pages?.at||data.github.commit?.at)}</p></>:<Empty>Estado GitHub não disponível neste momento.</Empty>}</section><section className="admin-card"><h2>Último erro</h2>{data.lastError?<p><strong>{data.lastError.source}</strong> — {data.lastError.message}<br/><small>{date(data.lastError.at)}</small></p>:<Empty>Sem erros registados.</Empty>}</section></>}
