import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Archive, ArrowLeft, BarChart3, BookOpen, CheckCircle2, Clipboard, GraduationCap, LineChart, Plus, Radio, RefreshCw, Search, Sparkles, Users, X } from 'lucide-react';
import { allLevels, categories } from './curriculum';
import './voltz-teachers.css';

type Request=(action:string,input?:Record<string,unknown>)=>Promise<any>;
type Student={id:string;name:string;xp:number;completed:number;category:string;level:number;accuracy:number|null;answerCount:number;lastActiveAt:string|null;status:'good'|'normal'|'review'|'inactive'};
type ClassCard={id:string;name:string;year:string;description?:string;code:string;archived:boolean;students:number;avgProgress:number};
type ClassDetail={class:{id:string;name:string;year:string;description?:string;code:string;archived:boolean;createdAt:string};summary:{students:number;avgProgress:number;levelsCompleted:number;active:number;review:number};students:Student[];categories:{id:string;name:string;progress:number}[];topics:{topic:string;answers:number;students:number;accuracy:number}[];hardest:{topic:string;answers:number;students:number;accuracy:number}[];week:{levels:number;active:number};recommendations:any[];live:{available:boolean;linkedSessions:number}};

type Props={request:Request;onExit:()=>void;onOpenLive:()=>void};
const yearLabel=(value:string)=>value==='1'?'1.º':value==='2'?'2.º':value==='3'?'3.º':'Outro';
const dateLabel=(value?:string|null)=>{if(!value)return 'Sem atividade recente';const d=new Date(value);const diff=Math.floor((Date.now()-d.getTime())/86400000);return diff<=0?'Hoje':diff===1?'Há 1 dia':`Há ${diff} dias`};
const statusLabel=(s:Student['status'])=>s==='good'?'Bom progresso':s==='review'?'Pode beneficiar de revisão':s==='inactive'?'Sem atividade recente':'Normal';

export default function VoltzTeachers({request,onExit,onOpenLive}:Props){
 const [home,setHome]=useState<any>(null);const [detail,setDetail]=useState<ClassDetail|null>(null);const [student,setStudent]=useState<any>(null);const [tab,setTab]=useState('overview');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [createOpen,setCreateOpen]=useState(false);const [archiveConfirm,setArchiveConfirm]=useState(false);
 const loadHome=async()=>{setBusy(true);setError('');try{setHome(await request('teacher_home'));setDetail(null);setStudent(null)}catch(e){setError(e instanceof Error?e.message:'Erro ao carregar turmas.')}finally{setBusy(false)}};
 const openClass=async(id:string)=>{setBusy(true);setError('');try{setDetail(await request('class_detail',{classId:id}));setStudent(null);setTab('overview')}catch(e){setError(e instanceof Error?e.message:'Erro ao carregar turma.')}finally{setBusy(false)}};
 useEffect(()=>{void loadHome()},[]);
 const refresh=()=>detail?openClass(detail.class.id):loadHome();
 return <main className="teacher-shell">
  <header className="teacher-top"><button className="teacher-back" onClick={onExit}><ArrowLeft/> Voltar ao Voltz</button><div><span className="teacher-eyebrow"><GraduationCap/> ÁREA DE PROFESSORES</span><h1>Voltz Professores</h1><p>Acompanha a evolução das tuas turmas e identifica onde cada aluno precisa de mais apoio.</p></div><button className="teacher-refresh" onClick={refresh} aria-label="Atualizar"><RefreshCw/></button></header>
  {error&&<p className="teacher-error" role="alert">{error}</p>}
  {busy&&!home&&!detail&&<div className="teacher-loading">A carregar dados reais…</div>}
  {!detail&&home&&<TeacherHome data={home} onOpen={openClass} onCreate={()=>setCreateOpen(true)}/>} 
  {detail&&!student&&<ClassView data={detail} tab={tab} setTab={setTab} onBack={loadHome} onStudent={async id=>{setBusy(true);try{setStudent(await request('student_detail',{classId:detail.class.id,studentId:id}))}catch(e){setError(e instanceof Error?e.message:'Erro ao abrir aluno.')}finally{setBusy(false)}}} request={request} reload={()=>openClass(detail.class.id)} onArchive={()=>setArchiveConfirm(true)} onOpenLive={onOpenLive}/>} 
  {detail&&student&&<StudentView data={student} classId={detail.class.id} onBack={()=>setStudent(null)} request={request} reload={async()=>setStudent(await request('student_detail',{classId:detail.class.id,studentId:student.student.id}))}/>} 
  {createOpen&&<CreateClass request={request} onClose={()=>setCreateOpen(false)} onCreated={async id=>{setCreateOpen(false);await loadHome();await openClass(id)}}/>}
  {archiveConfirm&&detail&&<Confirm title={detail.class.archived?'Restaurar turma?':'Arquivar turma?'} text={detail.class.archived?'A turma volta a aceitar alunos e fica editável.':'A turma fica em modo histórico e deixa de aceitar novos alunos.'} confirm={detail.class.archived?'Restaurar':'Arquivar'} onCancel={()=>setArchiveConfirm(false)} onConfirm={async()=>{await request('archive_class',{classId:detail.class.id,archived:!detail.class.archived});setArchiveConfirm(false);await openClass(detail.class.id)}}/>}
 </main>
}

function TeacherHome({data,onOpen,onCreate}:{data:any;onOpen:(id:string)=>void;onCreate:()=>void}){const s=data.summary||{};return <div className="teacher-page"><section className="teacher-kpis"><Kpi label="Turmas" value={s.classes??0}/><Kpi label="Alunos" value={s.students??0}/><Kpi label="Progresso médio" value={`${s.avgProgress??0}%`}/><Kpi label="A rever conteúdos" value={s.review??0} alert/></section><div className="teacher-section-head"><div><span className="teacher-eyebrow">AS MINHAS TURMAS</span><h2>Turmas</h2></div><button className="teacher-primary" onClick={onCreate}><Plus/> Criar turma</button></div>{!data.classes?.length?<Empty text="Ainda não tens turmas. Cria a primeira e começa a acompanhar os teus alunos."/>:<section className="teacher-class-grid">{data.classes.map((c:ClassCard)=><article className={`teacher-class-card ${c.archived?'is-archived':''}`} key={c.id}><div><small>{yearLabel(c.year)} ano {c.archived?'· Arquivada':''}</small><h3>{c.name}</h3><p>{c.description||'Sem descrição.'}</p></div><div className="teacher-class-stats"><span><Users/>{c.students} alunos</span><span><BarChart3/>{c.avgProgress}% progresso médio</span></div><button onClick={()=>onOpen(c.id)}>Abrir turma</button></article>)}</section>}</div>}

function ClassView({data,tab,setTab,onBack,onStudent,request,reload,onArchive,onOpenLive}:{data:ClassDetail;tab:string;setTab:(v:string)=>void;onBack:()=>void;onStudent:(id:string)=>void;request:Request;reload:()=>void;onArchive:()=>void;onOpenLive:()=>void}){
 const [q,setQ]=useState('');const [filter,setFilter]=useState('all');const [recOpen,setRecOpen]=useState(false);const students=useMemo(()=>data.students.filter(s=>s.name.toLowerCase().includes(q.toLowerCase())&&(filter==='all'||s.status===filter)),[data.students,q,filter]);
 const tabs=[['overview','Visão geral'],['students','Alunos'],['topics','Matérias'],['stats','Estatísticas'],['recs','Recomendações'],['live','Voltz Live']];
 return <div className="teacher-page"><div className="teacher-class-title"><button onClick={onBack}><ArrowLeft/></button><div><span className="teacher-eyebrow">TURMA · {yearLabel(data.class.year)}</span><h2>{data.class.name}</h2><p>{data.class.description||'Sem descrição.'}</p></div><div className="teacher-code"><small>Código</small><strong>{data.class.code}</strong><button onClick={()=>navigator.clipboard?.writeText(data.class.code)} aria-label="Copiar código"><Clipboard/></button></div></div>
 <nav className="teacher-tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {tab==='overview'&&<><section className="teacher-kpis"><Kpi label="Alunos" value={data.summary.students}/><Kpi label="Progresso médio" value={`${data.summary.avgProgress}%`}/><Kpi label="Níveis concluídos" value={data.summary.levelsCompleted}/><Kpi label="A rever" value={data.summary.review} alert/></section><section className="teacher-panel"><h3>Progresso médio por categoria</h3>{data.categories.map(c=><ProgressRow key={c.id} name={c.name} value={c.progress}/>)}</section><section className="teacher-alert-grid"><article><AlertTriangle/><strong>{data.summary.review} alunos</strong><span>podem beneficiar de revisão ou estão sem atividade recente.</span></article><article><BookOpen/><strong>{data.hardest[0]?.topic||'Dados insuficientes'}</strong><span>Tema com maior dificuldade observada.</span></article><article><LineChart/><strong>+{data.week.levels} níveis</strong><span>concluídos esta semana desde a recolha destes dados.</span></article></section></>}
 {tab==='students'&&<><div className="teacher-toolbar"><label><Search/><input placeholder="Pesquisar aluno" value={q} onChange={e=>setQ(e.target.value)}/></label><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos</option><option value="review">A rever</option><option value="good">Bom progresso</option><option value="inactive">Sem atividade recente</option></select></div><section className="teacher-student-list">{students.map(s=><button key={s.id} onClick={()=>onStudent(s.id)}><div><strong>{s.name}</strong><span>{s.category} · Nível {s.level} · {s.completed}/50</span></div><div><b>{s.accuracy===null?'Dados insuficientes':`${s.accuracy}%`}</b><span>{dateLabel(s.lastActiveAt)}</span></div><em className={`student-status ${s.status}`}>{statusLabel(s.status)}</em></button>)}</section></>}
 {tab==='topics'&&<section className="teacher-panel"><h3>Matérias da turma</h3>{!data.topics.length?<Empty text="Ainda não existem respostas pedagógicas suficientes nesta turma."/>:data.topics.map(t=><div className="topic-row" key={t.topic}><div><strong>{t.topic}</strong><span>{t.students} alunos · {t.answers} respostas</span></div><b>{t.answers<5?'Dados insuficientes':`${t.accuracy}%`}</b></div>)}<h3 className="teacher-subtitle">Perguntas/temas com mais erros</h3>{!data.hardest.length?<p className="teacher-muted">Dados insuficientes.</p>:data.hardest.map((h,i)=><div className="hard-row" key={h.topic}><span>{i+1}</span><strong>{h.topic}</strong><b>{h.accuracy}% correto</b></div>)}</section>}
 {tab==='stats'&&<><section className="teacher-panel"><h3>Distribuição do progresso</h3>{data.categories.map(c=><ProgressRow key={c.id} name={c.name} value={c.progress}/>)}</section><section className="teacher-kpis compact"><Kpi label="Ativos esta semana" value={data.week.active}/><Kpi label="Níveis esta semana" value={data.week.levels}/><Kpi label="Taxa de acerto" value={classAccuracy(data.students)}/></section></>}
 {tab==='recs'&&<section className="teacher-panel"><div className="teacher-section-head"><div><h3>Recomendações</h3><p>Orientações de revisão sem bloquear o percurso.</p></div><button className="teacher-primary" onClick={()=>setRecOpen(true)}><Plus/> Recomendar</button></div>{!data.recommendations.length?<Empty text="Ainda não enviaste recomendações para esta turma."/>:data.recommendations.map(r=><div className="recommendation-row" key={r.id}><strong>{levelName(r.levelId)}</strong><span>{r.studentId?data.students.find(s=>s.id===r.studentId)?.name||'Aluno':'Toda a turma'}{r.message?` · ${r.message}`:''}</span></div>)}</section>}
 {tab==='live'&&<section className="teacher-panel teacher-live-panel"><Radio/><h3>Voltz Live para esta turma</h3><p>O Live já está disponível. Podes abrir o criador e jogar com a turma; a associação automática de resultados à turma fica preparada para a próxima integração.</p><button className="teacher-primary" onClick={onOpenLive}>Criar Voltz Live</button><small>{data.live.linkedSessions} sessões já associadas a esta turma.</small></section>}
 <div className="teacher-danger-zone"><button className="teacher-secondary" onClick={onArchive}>{data.class.archived?'Restaurar turma':'Arquivar turma'} <Archive/></button></div>
 {recOpen&&<RecommendModal classId={data.class.id} students={data.students} request={request} onClose={()=>setRecOpen(false)} onDone={async()=>{setRecOpen(false);reload()}}/>}</div>}

function StudentView({data,classId,onBack,request,reload}:{data:any;classId:string;onBack:()=>void;request:Request;reload:()=>void}){const topics=[...(data.topics||[])];const strong=topics.filter((t:any)=>t.accuracy>=80).slice(0,3);const review=topics.filter((t:any)=>t.accuracy<70).sort((a:any,b:any)=>a.accuracy-b.accuracy).slice(0,3);return <div className="teacher-page"><div className="teacher-class-title"><button onClick={onBack}><ArrowLeft/></button><div><span className="teacher-eyebrow">PERFIL PEDAGÓGICO</span><h2>{data.student.name}</h2><p>{data.student.completed}/50 níveis · {data.student.xp} XP · {data.accuracy===null?'Dados insuficientes':`${data.accuracy}% acerto`}</p></div></div><div className="student-detail-grid"><section className="teacher-panel"><h3><Sparkles/> Melhor desempenho observado</h3>{strong.length?strong.map((t:any)=><div className="topic-row" key={t.topic}><strong>{t.topic}</strong><b>{t.accuracy}%</b></div>):<p className="teacher-muted">Dados insuficientes.</p>}</section><section className="teacher-panel"><h3><BookOpen/> Pode beneficiar de revisão</h3>{review.length?review.map((t:any)=><div className="topic-row" key={t.topic}><strong>{t.topic}</strong><b>{t.accuracy}%</b></div>):<p className="teacher-muted">Sem sinal suficiente para recomendar revisão automática.</p>}</section></div><section className="teacher-panel"><h3>Histórico recente</h3>{!data.history?.length?<p className="teacher-muted">Ainda não existem respostas registadas desde a entrada na turma.</p>:data.history.slice(0,12).map((h:any,i:number)=><div className="history-row" key={i}><span>{h.correct?<CheckCircle2/>:<AlertTriangle/>}</span><strong>{h.topic}</strong><small>{new Date(h.at).toLocaleDateString('pt-PT')}</small></div>)}</section><button className="teacher-primary" onClick={async()=>{await request('recommend',{classId,studentId:data.student.id,levelId:(data.history?.[0]?.levelId)||'aprendiz-1',message:'Revê este conteúdo antes da próxima aula.'});await reload()}}>Recomendar revisão recente</button></div>}

export function StudentClassPanel({request,onReview}:{request:Request;onReview:(levelId:string)=>void}){const [data,setData]=useState<any>(null);const [code,setCode]=useState('');const [error,setError]=useState('');const [confirm,setConfirm]=useState<string|null>(null);const load=async()=>{try{setData(await request('student_context'));setError('')}catch(e){setError(e instanceof Error?e.message:'Erro ao carregar turmas.')}};useEffect(()=>{void load()},[]);return <section className="student-class-panel"><div className="student-class-head"><div><span className="teacher-eyebrow"><GraduationCap/> TURMAS</span><h3>As minhas turmas</h3></div></div>{error&&<p className="teacher-error">{error}</p>}<form onSubmit={async e=>{e.preventDefault();try{await request('join_class',{code});setCode('');await load()}catch(err){setError(err instanceof Error?err.message:'Código inválido.')}}}><label>Entrar numa turma<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="VOLTZ-8F3K2" maxLength={11}/></label><button className="teacher-primary">Entrar</button></form>{data?.classes?.length?data.classes.map((c:any)=><div className="student-class-row" key={c.id}><div><strong>{c.name}</strong><span>{yearLabel(c.year)} · {c.teacher}</span></div><button onClick={()=>setConfirm(c.id)}>Sair</button></div>):<p className="teacher-muted">Ainda não pertences a nenhuma turma.</p>}<div className="student-recommendations"><h4>Recomendado pelo professor</h4>{!data?.recommendations?.length?<p className="teacher-muted">Sem recomendações neste momento.</p>:data.recommendations.map((r:any)=><article key={r.id}><div><strong>{levelName(r.levelId)}</strong><span>{r.teacher} · {r.className}</span>{r.message&&<p>“{r.message}”</p>}</div><button onClick={async()=>{await request('mark_recommendation',{id:r.id,completed:false});onReview(r.levelId)}}>Rever agora</button></article>)}</div>{confirm&&<Confirm title="Sair da turma?" text="O professor deixa de ver novos dados teus nesta turma. O teu progresso geral no Voltz não é apagado." confirm="Sair" onCancel={()=>setConfirm(null)} onConfirm={async()=>{await request('leave_class',{classId:confirm});setConfirm(null);await load()}}/>}</section>}

function CreateClass({request,onClose,onCreated}:{request:Request;onClose:()=>void;onCreated:(id:string)=>void}){const [name,setName]=useState('');const [year,setYear]=useState('1');const [description,setDescription]=useState('');const [error,setError]=useState('');return <div className="teacher-modal-backdrop"><section className="teacher-modal" role="dialog" aria-modal="true"><button className="teacher-modal-x" onClick={onClose}><X/></button><span className="teacher-eyebrow">NOVA TURMA</span><h2>Criar turma</h2><label>Nome da turma<input value={name} onChange={e=>setName(e.target.value)} placeholder="Eletricidade — 1.º Ano"/></label><label>Ano<select value={year} onChange={e=>setYear(e.target.value)}><option value="1">1.º</option><option value="2">2.º</option><option value="3">3.º</option><option value="other">Outro</option></select></label><label>Descrição opcional<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={3}/></label>{error&&<p className="teacher-error">{error}</p>}<button className="teacher-primary" onClick={async()=>{try{const data=await request('create_class',{name,year,description});onCreated(data.id)}catch(e){setError(e instanceof Error?e.message:'Erro ao criar turma.')}}}>Criar turma</button></section></div>}

function RecommendModal({classId,students,request,onClose,onDone}:{classId:string;students:Student[];request:Request;onClose:()=>void;onDone:()=>void}){const [studentId,setStudentId]=useState('');const [levelId,setLevelId]=useState(allLevels[0].id);const [message,setMessage]=useState('');return <div className="teacher-modal-backdrop"><section className="teacher-modal"><button className="teacher-modal-x" onClick={onClose}><X/></button><span className="teacher-eyebrow">RECOMENDAÇÃO</span><h2>Recomendar revisão</h2><label>Destinatário<select value={studentId} onChange={e=>setStudentId(e.target.value)}><option value="">Toda a turma</option>{students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Conteúdo<select value={levelId} onChange={e=>setLevelId(e.target.value)}>{categories.map(c=><optgroup label={c.name} key={c.id}>{c.levels.map(l=><option key={l.id} value={l.id}>{l.title}</option>)}</optgroup>)}</select></label><label>Mensagem opcional<textarea rows={3} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Revê este nível antes da próxima aula."/></label><button className="teacher-primary" onClick={async()=>{await request('recommend',{classId,studentId:studentId||null,levelId,message});onDone()}}>Enviar recomendação</button></section></div>}

function Kpi({label,value,alert=false}:{label:string;value:string|number;alert?:boolean}){return <article className={`teacher-kpi ${alert?'alert':''}`}><span>{label}</span><strong>{value}</strong></article>}
function ProgressRow({name,value}:{name:string;value:number}){return <div className="teacher-progress-row"><div><strong>{name}</strong><span>{value}%</span></div><div><i style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div></div>}
function Empty({text}:{text:string}){return <div className="teacher-empty"><GraduationCap/><p>{text}</p></div>}
function Confirm({title,text,confirm,onCancel,onConfirm}:{title:string;text:string;confirm:string;onCancel:()=>void;onConfirm:()=>void|Promise<void>}){return <div className="teacher-modal-backdrop"><section className="teacher-modal confirm"><h2>{title}</h2><p>{text}</p><div><button className="teacher-secondary" onClick={onCancel}>Cancelar</button><button className="teacher-primary" onClick={()=>void onConfirm()}>{confirm}</button></div></section></div>}
function levelName(id:string){return allLevels.find(l=>l.id===id)?.title||id}
function classAccuracy(students:Student[]){const valid=students.filter(s=>s.accuracy!==null);return valid.length?`${Math.round(valid.reduce((a,s)=>a+(s.accuracy||0),0)/valid.length)}%`:'Dados insuficientes'}
